### ISSUE TITLE
Add voice activation via hotword

### ISSUE THREAD

**Issue by alfongj** [googlesamples/assistant-sdk-python#1]
Problem:
I want to be able to activate the Assistant via voice, so I don't need to press a button (or spacebar) each time I want to talk to it.

**Comment by elblogbruno** [comment]
Yeah me too,Have you achieved this?

**Comment by alfongj** [comment]
Hi @elblogbruno . I am from the Assistant SDK team, and filed this issue to allow you guys to keep track of it. 

This feature is under development now, and we will be opening a private beta for it soon. If you are interested, please sign up [here](https://groups.google.com/forum/#!forum/google-assistant-sdk-updates) (and turn on email updates)

Thanks for the interest!

**Comment by xtools-at** [comment]
in the meantime, try this, it already has voice control for Assistant using pocketsphinx:
https://github.com/xtools-at/AssistantPi

**Comment by jakommo** [comment]
Seems like this was added in today's update https://github.com/googlesamples/assistant-sdk-python/blob/master/google-assistant-sdk/CHANGELOG.rst#030

**Comment by proppy** [comment]
Yep, see https://developers.google.com/assistant/sdk/prototype/getting-started-pi-python/ to get started.
