### ISSUE TITLE
Assistant on Raspberry PI AIY is rubbish at basic maths

### ISSUE THREAD

**Issue by sheridat** [googlesamples/assistant-sdk-python#102]
I ask my AIY assistant 
1. What is 3 plus 3 - it answers 6 - yippeeee
2. What is 6 divided by 2 - it answers 3 - yipeeeee
3. What is 3 plus 3 divided by 2 - it answers 4.5 time after time - nooooooooooooooooooooooo!

It isn't teaching my kids maths - surprising that it can stumble at such a seemingly simple question

**Comment by sheridat** [comment]
Well it turns out that it depends upon which calculator you use
1. Windows 10 calculator reckons the answer is 3
2. Google Nexus 7 calculator is 4.5 (they are chums)
3. Windows Phone 8.1 answer is 3
4. Google and Edge Browsers - both 4.5 
5. Casio fx-570 resolves to 4.5
6. Nokia C2.02 phone is 3.

**Comment by justinkruit** [comment]
Actually, 4.5 is the correct answer on 3+3÷2, as you do multiplication and division before addition and subtraction. If you want 3 as the answer, you would need to add parentheses like this: (3+3)÷2

**Comment by sheridat** [comment]
Yeah
