### ISSUE TITLE
After restarting pi I will get command not found for pushtotalk

### ISSUE THREAD

**Issue by tadesushilgithub** [googlesamples/assistant-sdk-python#103]
I did setup on rasberry pi but after restart when I run command googlesamples-assistant-pushtotalk

then I will get command not found error.

**Comment by proppy** [comment]
Did you install the python package? are you running this command from a virtualenv?

**Comment by Fleker** [comment]
If you're still having issues, re-read the [documentation](https://developers.google.com/assistant/sdk/guides/service/python/), which explains thoroughly how to setup your Raspberry Pi to run the samples.
