### ISSUE TITLE
Is it possible to use google assistant with aarch64 linux (ubuntu 16.04)?

### ISSUE THREAD

**Issue by nunoki** [googlesamples/assistant-sdk-python#104]
I met below error.

$ pip install --upgrade google-auth-oauthlib2
Collecting google-auth-oauthlib2
  Could not find a version that satisfies the requirement google-auth-oauthlib2 (from versions: )
No matching distribution found for google-auth-oauthlib2

Is it possible to use google assistant with aarch64 linux?

$ uname -a
Linux localhost.localdomain 4.4.1-gbac6717 #1 SMP PREEMPT Mon Jul 24 13:58:00 CST 2017 aarch64 aarch64 aarch64 GNU/Linux

**Comment by proppy** [comment]
I think the package is named:
https://pypi.python.org/pypi/google-auth-oauthlib

**Comment by Fleker** [comment]
I'd recommend re-trying to download the oauthlib tool. If you're still seeing issues, we can re-open this issue.
