### ISSUE TITLE
Raspberry Pi Zero W support

### ISSUE THREAD

**Issue by drbeat** [googlesamples/assistant-sdk-python#107]
Hi,

As I have read the google-assistant-library is only supporting armv7l so it will not install on the Pi Zero.

Are there any plans on adding support for armv6 / zero or is this a design/business decision we have to live with?

If not can we start a request for that? :peace_symbol: 

Thanks

**Comment by Noob-101** [comment]
It does work on the zero w except that you can't use the hotword function (wake it up by saying "ok google" or "hey google". Follow the gRPC guide here:
https://developers.google.com/assistant/sdk/develop/grpc/

**Comment by adamwest9** [comment]
Drbeat,
 Have you tried this out yet? I was think about using a flick to activate the PTT function on the RPI zero Google Assistant.

**Comment by shivasiddharth** [comment]
I am right now, integrating google asistant for pi zero and pi 3 as a single project. You can follow the progress here https://github.com/shivasiddharth/GassistPi I have added a custom wakeword functionality using the PTT and snowboy and will soon be updating my git.
