### ISSUE TITLE
how to make the assistant only listen after a assistant.startconversation()

### ISSUE THREAD

**Issue by aycgit** [googlesamples/assistant-sdk-python#108]
see title, my current code can be found [here](https://github.com/aycgit/google-assistant-hotword/blob/master/jarvis.py) i want to trigger the assistant after someone says my hotword "jarvis" but currently the assistant.start loop blocks the code flow.

**Comment by aycgit** [comment]
bump and this could also be a enhancement if you can add a way to start it non-blocking

**Comment by shivasiddharth** [comment]
I ran into kind of similar issue, start assistant listens and even creates a text transcript of my request, but it does not respond and instead starts listening again !

**Comment by aycgit** [comment]
this would sadly require a overhaul in the current system so i don't think we have much of a chance :)

**Comment by shivasiddharth** [comment]
@aycgit , check this out, #117 , seems like now we can manually start the assistant..

**Comment by aycgit** [comment]
I swear i had tried that. Anyway i used the aiy lib which did work.

**Comment by shujaathaider** [comment]
> I swear i had tried that. Anyway i used the aiy lib which did work.

Can you please tell what you did to resolve the code block issue?

**Comment by Wqrld** [comment]
2-year old issue :) , i believe i never got this working and cancelled my project because of that

**Comment by shujaathaider** [comment]
> Never got this to work, i used another lib as per ^ but i stopped working with it when the audio on my pi broke because of all this work ;)

Alright, thanks. :-)
