### ISSUE TITLE
Assistant not detecting I2S microphone

### ISSUE THREAD

**Issue by shivasiddharth** [googlesamples/assistant-sdk-python#109]
Hi,
I am using a stereo mems microphone. The audio test and playback works fine, but the assistant does not seem to detect the mic. Any help will be appreciated.

**Comment by proppy** [comment]
@shivasiddharth which sample are you running?

**Comment by shivasiddharth** [comment]
@proppy , I am using the SPH0645LM4H adafruit mic in stereo configuration. I tried it with python samples for grpc API as well as the python samples for google assistant library.

**Comment by proppy** [comment]
@shivasiddharth does the `googlesamples-assistant-audiotest` script work?

**Comment by shivasiddharth** [comment]
@proppy Hi, The audio test works fine. but the google assistant does not seem to record the audio when triggered. Could it be any sampling rate or audio format issues ?

**Comment by shivasiddharth** [comment]
I shall close this issue ! I have come up with an alternative !

**Comment by proppy** [comment]
@shivasiddharth curious what the alternative you found?

**Comment by shivasiddharth** [comment]
Added an EEPROM and used the same dtoverlay as the AIY projects Voice HAT. For the sake of community i have made detailed posts.. https://github.com/shivasiddharth/custom-voice-hat
https://www.hackster.io/shiva-siddharth/make-your-own-google-voice-hat-9f96ca

**Comment by proppy** [comment]
@shivasiddharth that's awesome thanks for sharing!

**Comment by LondonSi72** [comment]
+1 Nice job @shivasiddharth
