### ISSUE TITLE
Status of support for Input Arguments

### ISSUE THREAD

**Issue by clungzta** [googlesamples/assistant-sdk-python#111]
Hello,

I'm using the Actions SDK to extend the functionality of my Python Assistant SDK based app.

I would like my application to provide some arguments (e.g. a unique_id) to a conversation. Therefore allowing my custom Action webhook to provide information tailored specifically to a particular assistant session.

This [input argument functionality is supported](https://developers.google.com/actions/reference/rest/Shared.Types/AppRequest#Input) by the Actions SDK for Google Assistant. Thus, I would also expect this functionality to be supported by the Google Assistant SDK itself.

Can said argument functionality be used within assistant-sdk-python?

Best Regards,

**Comment by Fleker** [comment]
That exact API wouldn't work for Actions on Google actions, but you can now use Device Actions for on-device fulfillment.

**Comment by Fleker** [comment]
You can use custom device actions now.
