### ISSUE TITLE
Can we change the hotword from "OK Google" to something we want. 

### ISSUE THREAD

**Issue by tkamaal** [googlesamples/assistant-sdk-python#115]
Hello, 

Is there a possibility to change the hotword from "OK Google" or "Hey Google" to something we want?

**Comment by makedir** [comment]
Obviously not. And no one cares at Google. I hate it so much that I will switch to Amazons products, where you can change it. "OK Google" is just so awful and annoying to say than just Alexa or some other short word.

**Comment by Fleker** [comment]
Right now there's no support for custom hotwords directly. However, you can find alternate ways to trigger the microphone with a custom implementation. The hotword detection works offline, so it would be non-trivial to add support for additional hotwords in the library.

**Comment by makedir** [comment]
I wanted to buy a Google Home Mini, but not anymore I dont. Bye Bye Google Home. Welcome Amazon Echo Dot.

**Comment by tkamaal** [comment]
@Fleker Yes , I agree with you. People have used snowboy to change trigger words. Thank you.

**Comment by tkamaal** [comment]
@makedir and @Fleker I think it would make it much better if google adds the support to change the hotword. Hopefully, they might add it in the next release.

**Comment by walterdevos** [comment]
Typically Google does not care for such _details_.  You find this lack of interest in all their products. I think they would more than happy if we just all went elsewhere. Who wants all those "customers" with their pesky needs anyway. :-P

**Comment by humaknlght** [comment]
My problem is that when I say the keyword it triggers the phone of the person sitting next to me.  It's put me off from using the voice assistant.
