### ISSUE TITLE
start_conversation() API doesn't seem to work 

### ISSUE THREAD

**Issue by tkamaal** [googlesamples/assistant-sdk-python#117]
Hello,

I have a question. I'm looking to use two boards 
1. Raspberry Pi 3 and 
2. Customized board according to my project requirements.

Aim : The purpose of custom board is that it listens to a trigger word and pulls a pin high which is connected to GPIO Pin of Raspberry Pi 3. Upon seeing a high pulse on this pin, Pi should start listening and should start to send my query to google server and provide response back.

So to achieve this I have used the following API's 
set_mic_mute() - to stop assistant from listening to trigger word. 
start_conversation API() - to start recording user's speech and sending it google servers

The set_mic_mute API seems to be working fine but the start_converstaion API doesn't seem to do anything. I wonder why.

Documentation for following API's is provided [here](https://developers.google.com/assistant/sdk/reference/library/python/)

I believe this can be achieved, information is provided in next steps  [page](https://developers.google.com/assistant/sdk/develop/python/next-steps)

Code snippet for reference
In __main.py__ file following modifications were made and rest all remains as it is.
`with Assistant(credentials) as assistant:`
   `assistant.set_mic_mute(True)` #Turns Off google assistant from listening to hotword.
    `while(1):`
      `if(GPIO.input(23) == 1):`
           `print("GPIO Triggered")`
           `assistant.start_conversation()` #Doesn't seem to do anything. 
           `time.sleep(250.0/1000.0)`

Please provide some inputs and also let me know if you need more information. Correct me if I'm doing anything wrong with python (I'm a beginner) so my understanding is minimal.

**Comment by Fleker** [comment]
And to confirm, you are getting the **GPIO Triggered** message in the console?

**Comment by tkamaal** [comment]
@Fleker  Yes I do see the **GPIO Triggered** message. 

I have it working now using start_conversation() function along with start() function.  I did something like this 

`user_triggered = 0`
`with Assistant(credentials) as assistant:`
`for event in assistant.start():  #Don't want to use start but it wasn't possible to get it working so had to use it`   
`assistant.set_mic_mute(True)`
`if(GPIO.input(23) == 1):`
`print("GPIO Triggered..Started")`
`assistant.start_conversation()`
`user_triggered = 1`


`if(user_triggered == 1)`
`process_event(event)`

But it isn't 100% robust. Occasionally, I run into these below mentioned issues. 

**1. Sometimes the application throws segmentation fault.
  2. Sometimes application aborts since a function calls a pure virtual function.**  

Please provide some inputs to get rid of these issues.

**Comment by Fleker** [comment]
Is the issue related to debouncing? Are you printing out that message too many times for the Assistant to process?

In the [AIY Voice Kit project](https://github.com/google/aiyprojects-raspbian/blob/voicekit/src/assistant_library_with_button_demo.py) there's an example of using a GPIO pin to trigger Assistant

**Comment by tkamaal** [comment]
@Fleker  Even if I comment the print statement, I still do run into this issue. I will check for the debounce.

**Comment by shivasiddharth** [comment]
@tkamaal , sorry to to hijack this thread...  @Fleker is the ON_START_FINISHED a new addition ?

**Comment by tkamaal** [comment]
@Fleker It's not a debounce issue, as the errors creep in after I get a response from google assistant and not when triggered via GPIO. 

@shivasiddharth No problem.

**Comment by shivasiddharth** [comment]
@tkamaal , segmentation error is kind of common. If you are running it as a service, then GA will automatically restart. Add your GPIO trigger under if event.type == EventType.ON_START_FINISHED: 
it should work. 
Another reason for the error could be due to having the mic_mute(True) and simultaneously, starting the assistant. After print command set mic_mute to false and then try starting the assistant.

**Comment by ankitj05** [comment]
I am trying to start conversation when the hotword is detected using snowboy. But i am getting the following issue.
[1042:1069:ERROR:audio_input_processor.cc(755)] Input error
Also when i call the process_event(event) function, my code goes into loop. 
This is my code when the hotword is detected
def detect_callback():
    global start_conv, event
    start_conv = 0
    with Assistant(credentials) as assistant:
        for event in assistant.start():
            print("mic set true")
            assistant.set_mic_mute(True)
            print("start talking")
            assistant.start_conversation()
            print(start_conv)
            start_conv = 1
    if start_conv == 1:
        process_event(assistant, event)

**Comment by Fleker** [comment]
Are you still seeing this issue? If so, we can re-open it.
