### ISSUE TITLE
Some commands no longer work after 13/10 

### ISSUE THREAD

**Issue by shavanni** [googlesamples/assistant-sdk-python#119]
As of 13/10, some commands no longer work correctly.
Sing me a song now returns "here is information about sing me a song"
Sing a song now returns " here is a matching video"
Tell me a story now returns "here are matching news articles"

All were working correctly on 12/10

This using the aiyproject with gpio trigger

**Comment by Fleker** [comment]
This is a known issue on the server.

**Comment by Fleker** [comment]
Is this issue still occurring?

**Comment by salmanfarisvp** [comment]
Yes , if i ask 

> "Sing a song"

 it's return 

> "i don't know how to help with that 

"
i using google assistant python SDK on Raspberry pi 3,

**Comment by Fleker** [comment]
@salmanfarisvp this may be unrelated to the previous issue. Are you using hotword.py or pushtotalk.py?

**Comment by salmanfarisvp** [comment]
@Fleker  both hotword.py and pushtotalk.py have same issue.

**Comment by Fleker** [comment]
I'm going to make a new issue since this is unrelated to the original issue.

https://github.com/googlesamples/assistant-sdk-python/issues/257
