### ISSUE TITLE
not able to use my microphone

### ISSUE THREAD

**Issue by triggerhappyTH** [googlesamples/assistant-sdk-python#121]
so I just started playing with the raspberry pi with having no history in python our coding, and I'm running into the problem for my .asoundrc file not being read. an after searching on the webs for 2 hours and try to follow googles troubleshooting and multiple other installation guides, I'm still getting the problem of my .asoundrc not working, I'm sure its an easy fix but when even I do the command "vi.asoundrc"
this is the error I'm getting
E325: ATTENTION
Found a swap file by the name "~/.asoundrc.swap"
          owned by: pi   dated: Thu Oct 26 22:14:30 2017
         file name: ~pi/.asoundrc
          modified: YES
         user name: pi   host name: raspberry pi
        process ID: 2722
While opening file "/home/pi/.asoundrc"
is there anything I'm doing wrong?

**Comment by Fleker** [comment]
Looks like there's some behavior involving temporary files. You may want to take a look at what files exist in your home directory: `ls ~/ -a | grep asoundrc` and potentially remove them.

**Comment by Fleker** [comment]
Are you still seeing this issue? If so, we can re-open the issue.
