### ISSUE TITLE
stop_conversation() still performs action

### ISSUE THREAD

**Issue by jstys** [googlesamples/assistant-sdk-python#123]
I'm trying to use a custom intent parser when receiving the ON_RECOGNIZING_SPEECH_FINISHED event.  My plan was to perform custom actions if the recognized text matched something in my intent parser and otherwise fallback on some response from the google cloud.  If I call stop_conversation() in the event that the text matches a custom intent, the assistant won't give a cloud response however it will still perform actions.

In this case, I have a phillips Hue account tied to my google account so saying "Turn on the Light" will still trigger the assistant sending a turn on command through Hue even though I had called stop_conversation().  Perhaps this is intended functionality, but it would be handy to have an option to stop any google actions if stop_conversation() is called at the right time.

**Comment by Fleker** [comment]
This is intended behavior. If you have already linked your Hue to the Assistant, turning it on or off is going to run in parallel to sending the response back to your device. There's no way to override control over other devices which may be in the user's HomeGraph.
