### ISSUE TITLE
Get invalid wave stream if change the sample rate to other values, such as 24000.

### ISSUE THREAD

**Issue by jiabailie** [googlesamples/assistant-sdk-python#124]
In my side, I need to change the sample rate to other values.
When I change the default sample rate from 16000 to 24000 or 22040, I got invalid wave stream (one 1k .wav file).

Is it a bug, or Google Assistant SDK cannot support other sample rate?

**Comment by proppy** [comment]
@jiabailie can you confirm which sample you're using?

**Comment by jiabailie** [comment]
Now, my google assistant sdk instance's sample rate is 16000.
I want to change it to 24000.

**Comment by proppy** [comment]
@jiabailie which hardware are you using?

**Comment by jiabailie** [comment]
@proppy I run it on Ubuntu 14.04. for hardware, please more specific, which part you mean here?

**Comment by proppy** [comment]
@jiabailie thanks for sharing more info, can you also share which version of the python package you're using (maybe by attaching the output of `pip freeze`).

**Comment by jiabailie** [comment]
apturl===0.5.2ubuntu4
avs-client==0.5.2
Brlapi==0.6.1
cachetools==2.0.1
certifi==2017.7.27.1
cffi==1.11.0
chardet==3.0.4
checkbox-ng==0.3
checkbox-support==0.2
click==6.7
codecov==2.0.9
colorama==0.2.5
command-not-found==0.3
coverage==4.4.1
defer==1.0.6
feedparser==5.1.3
flake8==3.4.0
freezegun==0.3.9
friends==0.1
google-assistant-grpc==0.0.2
google-auth==1.1.1
google-auth-oauthlib==0.1.0
googleapis-common-protos==1.5.3
grpcio==1.6.3
h2==2.6.2
hpack==3.0.0
html5lib==0.999
httplib2==0.8
hyper==0.7.0
hyperframe==3.2.0
idna==2.5
language-selector==0.1
louis==2.5.3
lxml==3.3.3
Mako==0.9.1
MarkupSafe==0.18
mccabe==0.6.1
monotonic==1.3
oauthlib==2.0.4
onboard==1.0.1
oneconf==0.3.7.14.4.1
piston-mini-client==0.7.5
pkginfo==1.4.1
plainbox==0.5.3
protobuf==3.4.0
py==1.4.34
pyasn1==0.3.6
pyasn1-modules==0.1.4
pycodestyle==2.3.1
pycparser==2.18
pycrypto==2.6.1
pycurl==7.19.3
pyflakes==1.5.0
pygobject==3.12.0
pyparsing==2.0.1
pytest==3.2.0
pytest-cov==2.5.1
pytest-sugar==0.9.0
python-apt===0.9.3.5ubuntu2
python-dateutil==2.6.1
python-debian===0.1.21-nmu2ubuntu2
pyxdg==0.25
requests==2.18.3
requests-mock==1.3.0
requests-oauthlib==0.8.0
requests-toolbelt==0.8.0
rsa==3.4.2
six==1.11.0
software-center-aptd-plugins==0.0.0
sounddevice==0.3.7
tenacity==4.1.0
termcolor==1.1.0
tqdm==4.17.1
twine==1.9.1
typing==3.6.2
ubuntu-drivers-common==0.0.0
ufw===0.34-rc-0ubuntu2
unattended-upgrades==0.1
unity-scope-audacious==0.1
unity-scope-calculator==0.1
unity-scope-chromiumbookmarks==0.1
unity-scope-clementine==0.1
unity-scope-colourlovers==0.1
unity-scope-devhelp==0.1
unity-scope-firefoxbookmarks==0.1
unity-scope-gdrive==0.7
unity-scope-gmusicbrowser==0.1
unity-scope-gourmet==0.1
unity-scope-guayadeque==0.1
unity-scope-manpages==0.1
unity-scope-musique==0.1
unity-scope-openclipart==0.1
unity-scope-texdoc==0.1
unity-scope-tomboy==0.1
unity-scope-virtualbox==0.1
unity-scope-yelp==0.1
unity-scope-zotero==0.1
urllib3==1.21.1
usb-creator==0.2.23
xdiagnose===3.6.3build2
xkit==0.0.0

**Comment by Fleker** [comment]
As stated in the [documentation](https://developers.google.com/assistant/sdk/reference/rpc/google.assistant.embedded.v1alpha2#google.assistant.embedded.v1alpha2.AudioInConfig):

>  Sample rate (in Hertz) of the audio data sent in all audio_in messages. Valid values are from 16000-24000, but 16000 is optimal. For best results, set the sampling rate of the audio source to 16000 Hz. If that's not possible, use the native sample rate of the audio source (instead of re-sampling).

It seems recommended to go with 16K if possible.

**Comment by jiabailie** [comment]
Got it. Thank you.
