### ISSUE TITLE
British Accent

### ISSUE THREAD

**Issue by sheridat** [googlesamples/assistant-sdk-python#128]
Hi, I have a AIY voicekit - the Google Assistant replies in an American Accent.

I have a Nexus 7 and a Moto E4 both have the Google Assistant and they both reply in a distinctly British accent.

Can you do something to allow the AIY voicekit to return results in a British Accent?

**Comment by Fleker** [comment]
Right now there's no ability to change the locale the Assistant responds with.

**Comment by sheridat** [comment]
okay - just wanted to confirm so I can answer a question of the Raspberry.org AIY forum.

**Comment by bwims** [comment]
Is there an update to this?  "Right now" implies that later things may change. It is now 6 months later, and the product had altered beyond imagination during the past year.
