### ISSUE TITLE
Passing an audio file to google assistant 

### ISSUE THREAD

**Issue by saifabuhashish** [googlesamples/assistant-sdk-python#129]
I am using the assistant-sdk-python and I was wondering how I can pass an audio file with a request to the google assitant, is it possible? if so how?

Thanks

**Comment by Fleker** [comment]
With the project, it records audio in raw bytes and transmits that to the server. You could do a similar thing with a pre-recorded audio file where you transmit the raw data of the audio up.

We do it in some our tests, like here https://github.com/googlesamples/assistant-sdk-python/blob/master/google-assistant-sdk/nox.py#L70
