### ISSUE TITLE
Installing sample dependencies

### ISSUE THREAD

**Issue by saifabuhashish** [googlesamples/assistant-sdk-python#131]
I am trying to run Python Samples for the Google Assistant gRPC API, in order to do that, sample dependencies portaudio19-dev, libffi-dev and libssl-dev have to be installed. The README instructs to install the packages using apt-get. My problem is that I am working with linux armv7, kernel v4.4.41. The board I'm working with doesnt have an OS and therefore I cant use apt-get. Is there any alternative way I can install these dependencies?

**Comment by proppy** [comment]
You should be able to build them from source:
http://www.portaudio.com/download.html
https://www.openssl.org/source/
ftp://sourceware.org/pub/libffi/

**Comment by saifabuhashish** [comment]
Thanks @proppy for your help. I was able to download and install all the libraries, however when I go ahead and run googlesamples-assistant-pushtotalk, I still get
OSError: ctypes.util.find_library() did not manage to locate a library called 'portaudio'

which is odd to me since I'm pretty sure the installation process went as expected, and I even got a installation successful message. Any idea on what might be going on?

**Comment by Fleker** [comment]
Are you still seeing this issue? If so, we can re-open this issue.
