### ISSUE TITLE
Can the SDK get answers that contain more than just a spoken answer?

### ISSUE THREAD

**Issue by mpember** [googlesamples/assistant-sdk-python#132]
Since the Google Home devices are capable of playing podcasts, is it correct to assume that the functionality exists for the API to return more than just a spoken answer?

If I ask a Google Assistant to "_play the latest episode of **podcast name**_", the spoken answer suggests that the podcast will play.  However, the response being passed to the software only contains the spoken answer.  If the Home devices are capable of getting a URL (or similar), is there any way of having a similar level of detail available to clients built on the SDK?

**Comment by Fleker** [comment]
Right now the SDK does not support media playback.

**Comment by mpember** [comment]
> Right now the SDK does not support media playback.

Just to be clear, I'm not suggesting that the SDK should become a media player.  I was wondering whether the API is capable of returning more than just a spoken-word audio track and the text of the request.

**Comment by Fleker** [comment]
Not right now.

**Comment by mpember** [comment]
Is that a limitation of the API, or the SDK?

**Comment by Fleker** [comment]
At the moment it's a limitation of both. There's no field in the protobufs for the Assistant service to return any response from the Assistant other than an audio track and the text of the request. But I'll flag this as an enhancement.

**Comment by Fleker** [comment]
`supplemental_display_text` is now a field that is in the service API.

**Comment by mpember** [comment]
@Fleker 
Is that feature exposed via the SDK?

**Comment by Fleker** [comment]
It's in the service API. It is not in the library, but that's related to #216.

**Comment by hundredrabh** [comment]
Do you know if and when this API will be exposed for the library?

**Comment by hundredrabh** [comment]
I see the library documentation says that user spoken text is returned. What api returns Google Assistant response on text, using python library?

**Comment by Fleker** [comment]
It's an event, [`ON_RENDER_RESPONSE`](https://developers.google.com/assistant/sdk/reference/library/python/#google.assistant.library.event.EventType.ON_RENDER_RESPONSE).
