### ISSUE TITLE
adding google-assistant SDK-running device to my google home account

### ISSUE THREAD

**Issue by brianjmurrell** [googlesamples/assistant-sdk-python#133]
How can I add my device running the google-assistant SDK to my Google Home  as a linked device as described in this [document](https://support.google.com/googlehome/answer/7530880?co=GENIE.Platform%3DAndroid&hl=en)?

**Comment by Simonx22** [comment]
Hello, this is currently not possible with SDK. The document you linked only works with a Google Home or a similar device.

**Comment by brianjmurrell** [comment]
Is this an intentional limitation or just a current one that will be resolved at some future point?

**Comment by Fleker** [comment]
There's several limitations between a Google Home and the SDK right now. We are continuing to look at which features make the most sense to add next in a way that is useful for third-party developers.

**Comment by Fleker** [comment]
When you register a device, it will show up in the [Google Assistant settings](https://developers.google.com/assistant/sdk/reference/assistant-app/assistant-settings).
