### ISSUE TITLE
locale support 

### ISSUE THREAD

**Issue by saifabuhashish** [googlesamples/assistant-sdk-python#136]
I am trunning to run the pushtotalk sample in the sdk:
googlesamples-assistant-pushtotalk

When I run the sample, I get the following error:
(env) root@k2g-evm:~/projects/seti/exe# googlesamples-assistant-pushtotalk
Traceback (most recent call last):
  File "/home/root/projects/seti/exe/env/bin/googlesamples-assistant-pushtotalk", line 11, in <module>
    sys.exit(main())
  File "/home/root/projects/seti/exe/env/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/root/projects/seti/exe/env/lib/python3.5/site-packages/click/core.py", line 676, in main
    _verify_python3_env()
  File "/home/root/projects/seti/exe/env/lib/python3.5/site-packages/click/_unicodefun.py", line 118, in _verify_python3_env
    'for mitigation steps.' + extra)
RuntimeError: Click will abort further execution because Python 3 was configured to use ASCII as encoding for the environment.  Consult http://click.pocoo.org/python3/for mitigation steps.

Additional information: on this system no suitable UTF-8
locales were discovered.  This most likely requires resolving
by reconfiguring the locale system.

Click discovered that you exported a UTF-8 locale
but the locale system could not pick up from it because
it does not exist.  The exported locale is "C.UTF-8" but it
is not supported

I tried exporting:
export LC_ALL=C.UTF-8
export LANG=C.UTF-8
But I still get the same error.

When I type locale -a in my system I get:
C
POSIX

Those are the only two locale systems supported on my machine. I am running a linux kernel v4.4.41 with no real OS, so adding locales isn't very straightforward like ubuntu or debian. Is there anyway I can get past this issue with the locales I have? Any suggestions on how to get past this?

**Comment by Fleker** [comment]
Can you download the sample and try running the source?

**Comment by saifabuhashish** [comment]
I solved it by installing a en_US locale and then exporting it. Thank you!
