### ISSUE TITLE
Assistant no longer knows how to play music

### ISSUE THREAD

**Issue by PancakeSparkle** [googlesamples/assistant-sdk-python#137]
First of all,i know it didn't play music ever,but as of a few days ago,it doesn't even say music isn't supported,it just says it doesn't know how to help me with that "yet",and so do the chromecast commands,which used to work just fine

**Comment by Fleker** [comment]
Which Chromecast commands stopped working?

Not knowing how to play music may be a change in the TTS response to reflect its current capability.

**Comment by PancakeSparkle** [comment]
For example YouTube casting,Which used to work,still works on my phone

**Comment by PancakeSparkle** [comment]
I used to tell assistant to cast videos from YouTube to the TV,it used to do it,I don't know why it doesn't work anymore

**Comment by Fleker** [comment]
Were you using the library or gRPC version when executing these commands?

**Comment by PancakeSparkle** [comment]
library,installed using pip

**Comment by Fleker** [comment]
I believe this has since been fixed.
