### ISSUE TITLE
Navigation is no longer working

### ISSUE THREAD

**Issue by shavanni** [googlesamples/assistant-sdk-python#139]
Using the GPIO Trigger, whenever i ask how long will it take to get to a destination, I receive the following
"Sorry, I can't do navigation yet"

It used to give the correct response, e.g. " _destination_ is 30 minutes away in light traffic"

**Comment by Fleker** [comment]
It's a bit unusual that there was a regression. How did it know where you were in the first place?

**Comment by shavanni** [comment]
Not sure how it knows where I am. Maybe through my location history.
It tells me the weather for my location

**Comment by Simonx22** [comment]
It's using your IP to get your location iirc.

**Comment by Fleker** [comment]
We'll look into it.

**Comment by Fleker** [comment]
Can you try with the updated version of the library?

google-assistant-library 0.1.0

**Comment by Fleker** [comment]
Can you try with the updated version of the library?

google-assistant-library 0.1.0

**Comment by shavanni** [comment]
I haven't updated as I'm not sure how but it seems to be working regardless

**Comment by Fleker** [comment]
I'm glad to hear.
