### ISSUE TITLE
Assistant Selectively using a British Voice

### ISSUE THREAD

**Issue by sheridat** [googlesamples/assistant-sdk-python#140]
Hi, I use the Google AIY platform. 
In the past if I asked it for weather information - the responses were given in an American accent. 
For the first time in perhaps a month I asked the assistant "will it rain today" - I fell out of my high chair when the response was given in a British rather than American accent. 
If I ask what is the time - the response is an American voice
If I ask will it rain today - the response is a British voice
If I ask do I need an Umbrella today - the response is a British voice
If I ask what is the temperature - the response is a British voice
If I ask what is 2 plus 2 - the response is an American voice
If I ask who was Robert Oppenheimer the answer is an American voice
All of the British accent responses are followed by this error - [1557:1569:ERROR:assistant_output_handler.cc(543)] Ignoring kUnimplemented action error!` This doesn't cause a hard error.

I haven't done anything to update the assistant software so presumable this is a server side change.

It would be better if the Assistant didn't present different accent responses depending upon the question.

**Comment by Fleker** [comment]
This is a really interesting bug. Thanks for letting us know about it.

You're using a Raspberry Pi and the Python sample?

**Comment by sheridat** [comment]
I am using a Raspberry PI with a AIY voicehat and a google supplied image available from this url **https://aiyprojects.withgoogle.com/voice#assembly-guide-1-get-the-voice-kit-sd-image**
That image contains a variety of python programs that use the Assistant. 
The relevant url for the Google Voice Kit is https://github.com/google/aiyprojects-raspbian

The software runs in a virtual environment with the following software
argparse-1.4.0
enum34-1.1.6 
**google-assistant-library-0.0.3** 
google-auth-1.0.1 
requests-2.14.2
six-1.11.0

**Comment by LondonSi72** [comment]
I get the same result. Also with the original AIY image. 

:2313:ERROR:assistant_output_handler.cc(517)] Ignoring kUnimplemented action error!

**Comment by Fleker** [comment]
Can you try with the updated version of the library?

google-assistant-library 0.1.0

**Comment by sheridat** [comment]
I updated the version as above.

It breaks the AIY software
(env) pi@raspberrypi:~/AIY-voice-kit-python $ src/assistant_library_with_local_commands_demo.py
Traceback (most recent call last):
  File "src/assistant_library_with_local_commands_demo.py", line 99, in <module>
    main()
  File "src/assistant_library_with_local_commands_demo.py", line 93, in main
    with Assistant(credentials) as assistant:
TypeError: __init__() missing 1 required positional argument: 'device_model_id'

**Comment by Fleker** [comment]
You'll need to register a `device_model_id` https://developers.google.com/assistant/sdk/guides/library/python/embed/register-device

**Comment by sheridat** [comment]
Thank You - please see this update I've made on the AIY repo.  
https://github.com/google/aiyprojects-raspbian/issues/199

**Comment by Fleker** [comment]
Is the British accent issue still reproducible for you? We've been unable to replicate it.
