### ISSUE TITLE
Stuck at ON_MUTED_CHANGED:   {'is_muted': False} ON_START_FINISHED on Pi 3 b

### ISSUE THREAD

**Issue by VPNMAHAWAR** [googlesamples/assistant-sdk-python#141]
![pi3](https://user-images.githubusercontent.com/15152159/34015412-579c33f6-e144-11e7-8375-d83b11f5ea4f.JPG)

I've installed assistant on Raspberry Pi 3.  All gone well but after the installation done it stuck at ON_MUTED_CHANGED:   {'is_muted': False} ON_START_FINISHED and nothing happens after it.

**Comment by Fleker** [comment]
Have you tried speaking to it, saying "OK Google, <query>"? It seems like it is waiting for you to say something.

**Comment by VPNMAHAWAR** [comment]
Tried. Nothing happens....

**Comment by Fleker** [comment]
Are you sure that your microphone works? Have you tried the pushtotalk sample successfully?

**Comment by VPNMAHAWAR** [comment]
While running googlesamples-assistant-hotward it says no module named google.assistant.library.
It may help................
![pi3](https://user-images.githubusercontent.com/15152159/34057800-804ad446-e1fe-11e7-801a-
777516cd85e9.JPG)

**Comment by Fleker** [comment]
Have you made sure to pip install the library?

**Comment by shivasiddharth** [comment]
@VPNMAHAWAR , what mic are you using ? What is your audio setup , meaning, what is your mic device and audio out device ?

**Comment by VPNMAHAWAR** [comment]
@shivasiddharth I'm using webcam mic for audio input and standard 3.5 mm speakers for audio out. Both of them are working well (tested using arecord and aplay).
@Fleker Sorry for the late reply as my college exams are going on. I've installed all the libraries written over the Google developers page to setup SDK.

**Comment by shivasiddharth** [comment]
@VPNMAHAWAR , Try changing your asound.conf and asoundrc to this https://github.com/shivasiddharth/GassistPi/blob/master/audio-drivers/USB-MIC-JACK/scripts/asound.conf

**Comment by VPNMAHAWAR** [comment]
Thanks @shivasiddharth ,It worked after changing the .asoundrc and asound.conf files.
