### ISSUE TITLE
problem for new sdk assistant rpi3

### ISSUE THREAD

**Issue by Enzoinventor** [googlesamples/assistant-sdk-python#142]
hi, trying to run pushtotalk.py I get these errors:
(env) pi@raspberrypi:~ $ python3 /home/pi/assistant-sdk-python-master/google-assistant-sdk/googlesamples/assistant/grpc/pushtotalk.py
INFO:root:Connecting to embeddedassistant.googleapis.com
WARNING:root:Device config not found: [Errno 2] No such file or directory: '/home/pi/.config/googlesamples-assistant/device_config.json'
INFO:root:Registering device
ERROR:root:Option --device-model-id required when registering a device instance.

Register a new device model and new device instance (after replacing the 'placeholder values' between quotes):

it is not clear to me how to declare [this:](https://github.com/googlesamples/assistant-sdk-python/tree/master/google-assistant-sdk)

googlesamples-assistant-devicetool register --model 'my-model-identifier' \
                                            --type LIGHT --trait action.devices.traits.OnOff \
                                            --manufacturer 'Assistant SDK developer' \
                                            --product-name 'Assistant SDK light' \
                                            --description 'Assistant SDK light device' \
                                            --device 'my-device-identifier' \
                                            --nickname 'My Assistant Light'
I wait for your directions thank you very much

**Comment by shivasiddharth** [comment]
Try something like this.
```
googlesamples-assistant-devicetool register-model --manufacturer "Pi Foundation" \
          --product-name "GassistPi" --nickname RPi --model 'Your unique modelid"
```
The model id should be unique.  For my project users, i have created this script, which will take in the project id, name of the credentials file and a nickname. I am generating the modelid using the project-id and the date and time of installation, in that way, the modelid is always unique. Feel free to modify the script and use. 
https://github.com/shivasiddharth/GassistPi/blob/newsdk/scripts/gassist-installer-pi3.sh

**Comment by Fleker** [comment]
You first need to register your device model, then you will receive a device id from the sample. You can follow the instructions in [the docs](https://developers.google.com/assistant/sdk/guides/service/python/embed/register-device). Let me know if you have more questions.

`python3 pushtotalk.py --device-model-id your-model-id`

**Comment by Enzoinventor** [comment]
thanks for the answers, I managed to register the device and get the id and I ran the hotword example correctly by repeating the instructions here: https: //developers.google.com/assistant/sdk/guides/library/python /

The only thing that is not clear to me is because after the updates made, in the home / pi folder I still have the folder assistant-sdk-python with the old files inside? in theory I did not have to update? or were they moved elsewhere? I'm looking for the new pushtotalk.py file which allows me to change the language but I have not yet found where the updated file resides.
thank you very much for your patience.

**Comment by Fleker** [comment]
Are you modifying the sample code directly or using the `google-assistant-pushtotalk` command?

You can add the `--lang en-US` flag to change locale.

**Comment by Enzoinventor** [comment]
I would like to modify the sample code but I do not find it in home / pi / assistant-sdk-python / google-assistant-sdk / googlesamples / assistant / grpc
or rather I find it but not the updated version. why?

**Comment by Enzoinventor** [comment]
@shivasiddharth 
I tried your example and it does not work

**Comment by shivasiddharth** [comment]
@Enzoinventor , my mistake. There should not have been nickname there. 
```
googlesamples-assistant-devicetool register-model --manufacturer "Pi Foundation" \
          --product-name GassistPi --type Light --model 'Your unique model-id'
```
This one works for sure. Just make sure to set your own model-id

**Comment by Fleker** [comment]
Did you pull the latest changes in the sample?

**Comment by Enzoinventor** [comment]
@Fleker no, I have not done it yet if I run python3 pushtotalk.py --device-model-id your-model-id
I did not get the file in the directory

**Comment by Enzoinventor** [comment]
@shivasiddharth 
by running this code:
googlesamples-assistant-devicetool register-model --manufacturer "Pi Foundation" \
          --product-name GassistPi --type Light --model 'Your unique model-id'
and inserting my id from the google console, I get this error:
Error: Invalid value for "--type": invalid choice: Light. (choose from LIGHT, SWITCH, OUTLET)

**Comment by shivasiddharth** [comment]
@Enzoinventor .. Aaah auto correct..  LIGHT should be in caps.
```
googlesamples-assistant-devicetool register-model --manufacturer "Pi Foundation" \
          --product-name GassistPi --type LIGHT --model 'Your unique model-id'
```

**Comment by Enzoinventor** [comment]
@shivasiddharth 
ok, so it works

**Comment by Enzoinventor** [comment]
maybe it is appropriate to release a new AIY image file?

**Comment by Enzoinventor** [comment]
I succeeded thanks guys for the tips
googlesamples-assistant-pushtotalk --device-id 'id personal' --lang it-IT

**Comment by sunghwan523** [comment]
@Enzoinventor 
hi nice to meet you...
I have a same problem...
=>python -m googlesamples.assistant.grpc.pushtotalk 
and then 
I have a problem...
=> ERROR:root:Option --device-model-id required when registering a device instance.

how sloved the promblem??

**Comment by pvklink** [comment]
Hi,
When i try
googlesamples-assistant-pushtotalk --device-id <id> --lang it-IT it works, it speaks Italian!

But 
googlesamples-assistant-pushtotalk --device-id <id> --lang nl-NL it DOES NOT work!
Strange because my google assistant app on my tablet does speak Dutch!
Somebody an idea ?
