### ISSUE TITLE
from __future__ import print_function in hotword.py

### ISSUE THREAD

**Issue by shivasiddharth** [googlesamples/assistant-sdk-python#143]
Do we need the print function import? I suppose it would throw some import errors.

**Comment by Fleker** [comment]
It is being used as a compatibility layer between Python 2.7 and Python 3 for printing. [This StackOverflow question](https://stackoverflow.com/questions/32032697/how-to-use-from-future-import-print-function) has more information about it.

**Comment by shivasiddharth** [comment]
Ok..Thanks !
