### ISSUE TITLE
Hotword example Language

### ISSUE THREAD

**Issue by Jojow99** [googlesamples/assistant-sdk-python#146]
Hello,
is there a way to change the language in the hotword example?

**Comment by Simonx22** [comment]
Did you try --lang [language] behind the command? So for example: --lang ja-JP for Japanese and --lang de-DE for German.

**Comment by Enzoinventor** [comment]
@Simonx22 the hotword code is not structured to define the language. did you open the hotword.py file?

**Comment by Simonx22** [comment]
@Enzoinventor oh you're right. I thought it has that too like [textinput.py does](https://github.com/googlesamples/assistant-sdk-python/blob/7c422718749f3992dae7f0e6a3be8f2fb42d0fe9/google-assistant-sdk/googlesamples/assistant/grpc/textinput.py#L131).  I heard that it's possible to change settings in the Google Home app, but I'm not sure how.

**Comment by JulianMined** [comment]
@Simonx22
You can change the language/devicename in the App, but without any effect :/

**Comment by proppy** [comment]
There was an [issue](https://github.com/googlesamples/assistant-sdk-python/commit/f00df5ff40672942bdc6d1b27c10c49076f994f2) where the hotword sample didn't set the `client_type` correctly during device registration.

We published a new release:
https://pypi.python.org/pypi/google-assistant-sdk/0.4.1

Can you give it another try?

**Comment by pratesbh** [comment]
@proppy yes, it worked for me.
ps: grpc takes about one hour for building on my single board PC (Orange Pi Zero)

**Comment by proppy** [comment]
@pratesbh there should be arm7 wheels for the `1.7.0` version:
https://pypi.python.org/pypi/grpcio/1.7.0

**Comment by Nick-256** [comment]
The hotword example now works with other languages, but I still have to pronounce "Ok Google" in english to trigger it

**Comment by sergio-daniels** [comment]
I don't have access to the google assistant app since i only have an ios device and the google assistant app is not available in the Swiss ios app store. Is it possible to change the language of the hotword example without the app?

**Comment by Enzoinventor** [comment]
@sergio-daniels no and in my opinion here they were not very correct. they cut out several users. (please solve)

**Comment by Fleker** [comment]
For the Assistant SDK Library, you will need to change language using the app. If you are interested in programmatically changing the language in the library, please refer to #150.

For the Assistant Service, you can programmatically change the language in the API.

I'll close this issue as the primary question has been answered.

**Comment by sergio-daniels** [comment]
since i don't have an android device, I installed the android development studio and launched an android virtual device with android oreo. I was able to login to google app an change the language to de-DE, but still the hotword example is talking in english

**Comment by zhengpenghu** [comment]
@sergio-daniels  Yes. Change language in App only change how ASR understand your query, not the offline built-in hotword language. I will file this as a feature request to engineers.

Thanks,

**Comment by aandroide** [comment]
hello everyone I followed step by step your guide but I can not see the device on the app assistant, I ran:
(env) pi@raspberrypi:~ $ googlesamples-assistant-devicetool list --device
Device Instance Id: *****************
    Nickname: Assistant SDK light
    Model: Home
(env) pi@raspberrypi:~ $ googlesamples-assistant-devicetool list --model
Device Model Id: Home
        Project Id: composite-****-*****
        Device Type: action.devices.types.LIGHT
        Trait action.devices.traits.OnOff

I have in my phone android 6.0.1 and on assistant language settings I only see the phone between the devices.
How can I solve?
Thanks to everyone in advance

**Comment by Fleker** [comment]
Have you made sure the device and your phone are on the same Google account? Can you check again?

**Comment by aandroide** [comment]
yes, I certainly used the same account.
a user on a forum wrote that:
This is because Google has limited the developer package that is available for installing on the Raspberry pi. 
it's true?

**Comment by tei-chino** [comment]
@proppy ,  
I tried the new release:
https://pypi.python.org/pypi/google-assistant-sdk/0.4.3

I registered my device and  changed the language to Japanese in the Google Assistant app.
But the hotword is still talking in english, nothing changed!
I tried the AIY assistant_library_demo.py too, the results were same, Japanese didn't work!
However, the pushtotalk can talk in Japanese with the parameter --lang ja-Jp.

**Comment by proppy** [comment]
@tei-chino the 「OK Google」 hotword model is only available in `en-US` for now. But you should be able to set the **conversation** language in Japanese by updating the language in the settings of Google Assistant App for the device your registered.

**Comment by tei-chino** [comment]
@proppy , I have set the device's language to Japanese using the Google Assistant App, but  the Assistant  still talks english.
It seems that the App language settings had no any affects.

**Comment by proppy** [comment]
@tei-chino can you double check that you switched the language for the right device.

I was able to successfully switch the assistant from english to japanese while it was running:
```
tmp 🍡  env/bin/googlesamples-assistant-hotword --device_model_id my-model --project_id my-project-id
device_model_id: my-model
device_id: my-device-id

https://embeddedassistant.googleapis.com/v1alpha2/projects/my-project-id/devices/my-device-id 200
ON_MUTED_CHANGED:
  {'is_muted': False}
ON_START_FINISHED

ON_CONVERSATION_TURN_STARTED
ON_END_OF_UTTERANCE
ON_RECOGNIZING_SPEECH_FINISHED:
  {'text': 'what time is it'}
ON_RESPONDING_STARTED:
  {'is_error_response': False}
ON_RESPONDING_FINISHED
ON_CONVERSATION_TURN_FINISHED:
  {'with_follow_on_turn': False}

// - Go to the Assistant Settings
// - Switch the language to Japanese for the device with "device-model-id"

ON_CONVERSATION_TURN_STARTED
ON_END_OF_UTTERANCE
ON_RECOGNIZING_SPEECH_FINISHED:
  {'text': '今何時ですか'}
ON_RESPONDING_STARTED:
  {'is_error_response': False}
ON_RESPONDING_FINISHED
ON_CONVERSATION_TURN_FINISHED:
  {'with_follow_on_turn': False}
```

Hope that helps.

**Comment by tei-chino** [comment]
@proppy , thanks for your advise.
I followed your instruction to switch the language from English to Japanese while running, but it still didn't work.
Maybe there are some things wrong with me, but I have no any ideas.

**Comment by aandroide** [comment]
I apologize if I ask for your help again but I can not solve the problem of making the device appear on the app assistant.
I formatted the sd installed again noobs desktop and made all the updates, I followed the official guide https://developers.google.com/assistant/sdk/guides/library/python/
by wire and by sign and I created a new json key to be sure not to create conflicts, I then enabled the bee copied the code on the raspberry and I registered my device, I ran the hotword file without problems and I got the id that I entered in googlesamples-assistant-devicetool register-device --client-type LIBRARY \
          --model my-model --device my-device-id
the model and the device appear correctly if I interrupt the server but on the assistant app no ​​device seen besides the phone.
Any suggestions?
thank you all in advance

**Comment by aandroide** [comment]
@Fleker leker
gentlemen, I discovered the problem
for those who live in Italy, you have to change the language in English and set it in English, just by opening the app assistant and going to settings you can view the registered devices.
However, the problem remains that the Italian language is not yet available.
I will open a new report. @

**Comment by aandroide** [comment]
@tei-chino 
Hi, I can give you a suggestion:
make sure you have updated the library to the version: https: //pypi.python.org/pypi/google-assistant-sdk/0.4.3
run in the terminal:
source env / bin / activate
googlesamples-assistant-devicetool list --model
check that you do not have too many templates at most one by one with:
googlesamples-assistant-devicetool delete --model MODEL_ID
also run:
googlesamples-assistant-devicetool list --device
check that you do not have too many devices at most one by one with:
googlesamples-assistant-devicetool delete --device DEVICE_ID
and also from the app assistant it eliminates all the devices you see recorded.
Then register a new model and then execute:
googlesamples-assistant-devicetool register-device --client-type LIBRARY
--model my-model --device my-device-id
the device id you get it by running the file hotword.py as it showed proppy in the picture.
Let me know.

**Comment by tei-chino** [comment]
@aandroide, Thanks for your valuable advice. I followed your suggestion, tried the assistant again.
Please let me tell you the results.
a. Deleted all models and devices in my project.
b. Registered a new model  as SDK readme:
googlesamples-assistant-devicetool register-model --manufacturer "Assistant SDK developer" - product-name "Assistant SDK light" --type LIGHT --model test-model-1111
c. Registered a new device as your suggestion: (I notice that you set the  client_type = LIBRARY)
googlesamples-assistant-devicetool register-device --client-type LIBRARY --model test-model-1111 --device test-device-1111.
d. The new device showed on my Assistant App. I set the language to Japanese.
e. I run hotword using the new device:
googlesamples-assistant-hotword --device-model-id test-model-1111 -project_id my-project-4116-196212
f. I found another new device was shown on my Assistant App. I check it using "googlesamples-assistant-devicetool list --device". the model of the 2nd device is same with the 1st one, and it has been set to Japanese although I never do any things.
g. During first seconds,  the hotword didn't reacted my dialogue, then it began to recognize my Japanese as  proppy did, though recongnizing is not well done everytime:
ON_CONVERSATION_TURN_STARTED
ON_END_OF_UTTERANCE
ON_RECOGNIZING_SPEECH_FINISHED:
  {'text': 'こんにちは'}
ON_CONVERSATION_TURN_TIMEOUT
 However, no any replies ! The Assistant understood what I said, but didn't answer me. 
Ahthough, I could not fix the problem at all . Anyway, I did  some progress. 
==============================================================
By the way, I notice that the client type is set to  LIBRARY in  your suggestion, , however I found that the AIY project sample code and SDK readme set to SDK_SERVICE. Maybe, this caused the problem of Japanese.

**Comment by aandroide** [comment]
@tei-chino
@proppy 
I ask the experts, but sdk-service is only for pushbutton.py that uses api grpc
we await their confirmation

**Comment by tei-chino** [comment]
@aandroide 
The following is from AIY-projects-python device-helps.py
`    device_id = "%s-%s" % (model_id, uuid.uuid4())

    # We can hardcode client_type as SDK_SERVICE, because the Assistant Library
    # creates its own device_id.

    payload = {
            "id": device_id,
            "model_id": model_id,
            "client_type": "SDK_SERVICE",
    }`
By the way, I have tried the AIY-projects-python, I can set the language to Japanese, but no any effects.

**Comment by tei-chino** [comment]
@aandroide
@proppy 
I checked "My Actions" in my Assitant App, I found the logs of conversation with the Assistant.
It is very curious that my voice such as "今何時ですか？ (What time is it now?)" has been recognized on the RPi terminal, but  all of them recorded in my actions were "unknown voice commands". 
These can explain why the Assistant didn't reply my voice in Japanese. The Assistant can recognize the voice Japanese words only, but could not understant the meanings. Why?

By the way, I got only one reply from the Assistant in Japanese. When I saiy "Ok Google, こんにちは (hello)", the Assistant talked a piece of news to me in Japanese. But when I tried again, it didn't work any more.

**Comment by cheroby** [comment]
Hi everybody,
I am running hotword.py on my raspberry pi 3.

I got the same issue in changing the local settings to ITA.

I am unable to understand what do you mean when you say change the language in the APP. Do you mean in an Android phone?

Can you please tell me in which path of the phone is possible to setting the locale?

Which is the relationship among the Android APP and the code running on Raspberry?

Thanks & Regards

**Comment by Fleker** [comment]
The Google Assistant app on a phone has settings for the Google Assistant on all registered devices. The Raspberry Pi, which is authenticated as you, should appear in your device list and have settings for changing the language.

**Comment by aandroide** [comment]
In Android don't work
