### ISSUE TITLE
Assistant Apps no longer supported

### ISSUE THREAD

**Issue by pratesbh** [googlesamples/assistant-sdk-python#147]
With December's release I can't no longer use Google Assistant Apps with the hotword demo. When I try to invoke an existing App, like "talk to SongPop", it answers "Sorry, SongPop is not supported on this device".

**Comment by Fleker** [comment]
Thanks for the report. We're looking into why this may be happening. Can you try registering again with the 0.4.1 release of the SDK, then checking whether it is working correctly?

**Comment by pratesbh** [comment]
Unfortunately I can't make such change at this moment. Maybe in a few weeks, when a new single board pc will arrive.

**Comment by amerinoo** [comment]
Same problem here. Today I have made a clean installation of the Google Assistant SDK updating all. The demos are working well, but when I say "talk to Albert test" the answer is "Sorry, talk to Albert test is not supported on this device".

**Comment by sergio-daniels** [comment]
same problem here, would be greate to get it fixed. I realy like the sdk.

**Comment by varunchitre15** [comment]
Any update on this?

**Comment by Fleker** [comment]
Which version of the SDK are you using?

**Comment by pratesbh** [comment]
I've tested again on SDK version 0.1.1 and assistant apps are working as expected. Issue closed.
