### ISSUE TITLE
Accuracy of recognition is very low in hotword detection in japanese

### ISSUE THREAD

**Issue by garicchi** [googlesamples/assistant-sdk-python#152]
In the google assistant library v0.1.0, the sdk corresponded some language (ex. ja-JP).
So I tried to update sdk, register device, set language following step https://developers.google.com/assistant/sdk/guides/assistant-settings
and run program "googlesamples-assistant-hotword" and speech "OK,Google(In Japanese)".

However, the program could not recognize hotword which is  "OK,Google"(In Japanese).
Next, I tried to "OK,Google(In English)" then the program cloud recognize it. but accuracy is very low.
Finally I tried to say "what time is it now(In Japanese)" then the assistant program returned response In Japanese.

Why the assistant cloud not recognize Japanese hotword in spite of returning response in japanese?
Cloud I recognize hotword as well as Google HOME which sales at a market?

**Comment by Fleker** [comment]
We've [added support](https://developers.google.com/assistant/sdk/release-notes) for more hotword models to be downloaded to the device.
