### ISSUE TITLE
ERROR:assistant_ssdp_client.cc(83) and (210)

### ISSUE THREAD

**Issue by landaisbenj** [googlesamples/assistant-sdk-python#153]
Sorry for my english.

I've follow this step for install google assistant sdk without any problem.

When i start to running assistant i've many line like this two:

[4155:4172:ERROR:assistant_ssdp_client.cc(83)] LOCATION url's host is not a valid IP address [4155:4172:ERROR:assistant_ssdp_client.cc(210)] Failed to parse header: LOCATION: http://[@ipv6]:49152/InternetGatewayDevice.xml

I don't really understand what does it mean... The @ipv6 is my local wifi gateway... I don't know what's InternetGatewayDevice.xml and i don't know if my assistant want to acces this file or if it's return...

Can you help me ?

**Comment by essgrocott** [comment]
I had the same problem, fixed it by updating the google assistant library:
pip3 install google-assistant-library==0.1.0

Good luck!

**Comment by MrPestle** [comment]
Similar problem running google-assistant-library==0.1.1 
Failed to pass header: Location: http:// [IPV6 address]:8096/dnla/[setofnumbers]/description.xml
Switched of IPV6 on Raspberry Pi but still the same problem?
Should I downgrade to google-assistant-library==0.1.0???

**Comment by moham96** [comment]
see if installing upnp packags help

> sudo apt-get install minissdpd libminiupnpc10 libupnp6

reboot raspberry pi after installing

**Comment by MrPestle** [comment]
Thanks for the suggestion but after installing I still have the same
errors. The errors are referring to IPV6 addresses however I have disabled
IPV6
In /etc/sysctl.conf - added
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.lo.disable_ipv6 = 1

and ifconfig does not show any IPV6 addresses

**Comment by vikaskarunakaran** [comment]
**If I install google-assistant-library==0.1.0, I get the following error:**

Testing the installed google assistant. Make a note of the generated Device-Id
Traceback (most recent call last):
  File "/home/pi/env/bin/googlesamples-assistant-hotword", line 11, in <module>
    sys.exit(main())
  File "/home/pi/env/lib/python3.5/site-packages/googlesamples/assistant/library/hotword.py", line 128, in main
    Assistant.__version_str__())
AttributeError: type object 'Assistant' has no attribute '__version_str__'

**Comment by Fleker** [comment]
@vikaskarunakaran we have updated to [`google-assistant-library` 0.1.1](https://github.com/googlesamples/assistant-sdk-python/releases). You may want to update your dependencies to use the latest version.

**Comment by MrPestle** [comment]
I haven't revisited this for a while but don't think it did, although I can
get Alexa & Google Assistant to both work if I enter the code by hand but
they won't auto start on boot.(errors)

**Comment by Fleker** [comment]
Is this issue still happening?

**Comment by MrPestle** [comment]
I only revisit the project every three months or so and still haven't managed to get Alexa & Google Assistant to work together and auto start. Hoping an update will appear that sorts it all!
