### ISSUE TITLE
google-assistant-library-Empty

### ISSUE THREAD

**Issue by sopissed** [googlesamples/assistant-sdk-python#154]
I m so pissed i m trying to install this google assistant on my pc but getting errors from the first command i solved all of them but i m not able to solve this one 
  File "C:\Users\HRIDHYANSH\AppData\Local\Programs\Python\Python36-32\Scripts\go
oglesamples-assistant-hotword.exe\__main__.py", line 5, in <module>
  File "c:\users\hridhyansh\appdata\local\programs\python\python36-32\lib\site-p
ackages\googlesamples\assistant\library\hotword.py", line 27, in <module>
    from google.assistant.library import Assistant
ModuleNotFoundError: No module named 'google.assistant.library'

if you can help me with this one god bless you

**Comment by VPNMAHAWAR** [comment]
just install the library by executing the command in command prompt:
pip install google-assistant-library

**Comment by proppy** [comment]
Note that the google-assistant-library is only support on Linux (see https://developers.google.com/assistant/sdk/overview#features).

You should be able to follow the getting started guide for the Google Assistant Service:
https://developers.google.com/assistant/sdk/guides/service/python/
