### ISSUE TITLE
unknown device error on pushtotalk

### ISSUE THREAD

**Issue by miz884** [googlesamples/assistant-sdk-python#157]
The pushtotalk.py shows the following error on a device with a trait action.devices.traits.OnOff:

```
Press Enter to send a new request...
INFO:root:Recording audio request.
...
INFO:root:Transcript of user request: "turn on".
INFO:root:Playing assistant response.
WARNING:root:Ignoring command for unknown device: xxxx-xxxx-xxxx-xxxx-xxxxx
INFO:root:Finished playing assistant response.

```

The error indicates that a [DeviceRequestHandler](https://github.com/googlesamples/assistant-sdk-python/blob/master/google-assistant-sdk/googlesamples/assistant/grpc/device_helpers.py#L76) was not initialised with a proper device_id.

In [pushtotalk.py](https://github.com/googlesamples/assistant-sdk-python/blob/master/google-assistant-sdk/googlesamples/assistant/grpc/pushtotalk.py#L358), the DeviceRequestHandler is initialised before loading device_config, but it should be done after loading the device_config so that it can read proper device_id from the device_config.

**Comment by Fleker** [comment]
Are you passing the device id as a flag when you start the script?
