### ISSUE TITLE
Device config not found: [Errno 2] - ERROR:root:Failed to register device

### ISSUE THREAD

**Issue by zaper4life** [googlesamples/assistant-sdk-python#164]
Couldn't find anyway to make it work, couldn't find support online, I'm a newb who want to play with experts, if you can help me to get it to work I'll love it.

After running:

python -m pushtotalk --device-id 'my-device-identifier'

I've encountered following error:

_(env) ISRTLVMAC13:grpc oassraf$ python -m pushtotalk --device-model-id 'Omer_Link.932' --project-id 'OmerAssistant'
INFO:root:Connecting to embeddedassistant.googleapis.com
WARNING:root:Device config not found: [Errno 2] No such file or directory: '/Users/oassraf/Library/Application Support/googlesamples-assistant/device_config.json'
INFO:root:Registering device
ERROR:root:Failed to register device: {
  "error": {
    "code": 403,
    "message": "Could not create the device instance. You don't have permission to perform that operation on that resource.",
    "status": "PERMISSION_DENIED"
  }
}_

**Comment by zhengpenghu** [comment]
Make sure you do have the google developer project 'OmerAssistant', and the gmail account logged in is owner or editor of that project.

"Also, note that you must be an Owner or Editor of a given Google Developer Project to register models for it. (Add these roles for other users in the Cloud Console—see the IAM documentation)."

https://developers.google.com/assistant/sdk/guides/service/python/embed/register-device.

**Comment by zaper4life** [comment]
1. I appear to be the owner
2. I believe I use the correct credentials
3. I put a lot of pictures that may say more than I can
4. It's unbelievable the help and support I get from you guys, I'm a total newb who try to play with stuff and learning on the way and your support is something that I'm new to, thanks a bunch!

**Error:**
_(env) ISRTLVMAC13:grpc oassraf$ python -m pushtotalk --device-model-id 'Omer_Link.932' --project-id 'OmerAssistant'
INFO:root:Connecting to embeddedassistant.googleapis.com
WARNING:root:Device config not found: [Errno 2] No such file or directory: '/Users/oassraf/Library/Application Support/googlesamples-assistant/device_config.json'
INFO:root:Registering device
ERROR:root:Failed to register device: {
  "error": {
    "code": 403,
    "message": "Could not create the device instance. You don't have permission to perform that operation on that resource.",
    "status": "PERMISSION_DENIED"
  }
}_

**Folder Content:**
_(env) ISRTLVMAC13:grpc oassraf$ ls
README.rst
__init__.py
__pycache__
assistant_helpers.py
audio_helpers.py
client_secret_921988378596-qp68bjkfps94u5u********9mi.apps.googleusercontent.com.json
device_helpers.py
devicetool.py
pushtotalk.py
requirements.txt
textinput.py_





![image](https://user-images.githubusercontent.com/31882936/34921507-2339d7de-f98c-11e7-9861-bd3931838438.png)
![image](https://user-images.githubusercontent.com/31882936/34921522-4111ac78-f98c-11e7-9075-592fa4614066.png)
![image](https://user-images.githubusercontent.com/31882936/34921566-0e277418-f98d-11e7-8280-697ca7f8884e.png)
![image](https://user-images.githubusercontent.com/31882936/34921570-16e8b198-f98d-11e7-9185-242aaf7280bb.png)
![image](https://user-images.githubusercontent.com/31882936/34921574-1c408594-f98d-11e7-856d-3cd6f528aed0.png)

**Comment by zhengpenghu** [comment]
Did you figure it out now?

Could you try get your device model using command here?
https://developers.google.com/assistant/sdk/guides/service/python/embed/register-device

A device need to be tied to a existing device model owned by your project.

**Comment by zaper4life** [comment]
Still haven't figure it out yet, I seem to be able to register the device but nothing else:

_(env) ISRTLVMAC13:grpc oassraf$ python -m devicetool register --model 'Omer_Link'                               --type LIGHT --trait action.devices.traits.OnOff                               --manufacturer 'Assistant SDK developer'                               --product-name 'Assistant SDK light'                               --description 'Assistant SDK light device'                               --device 'Omer_Link.932'                               --nickname 'My Assistant Light' --client-type SERVICE
**Updating existing device model: Omer_Link
Model Omer_Link successfully registered
Creating new device
Device instance Omer_Link.932 successfully registered_**

And than there's this issue:
_(env) ISRTLVMAC13:grpc oassraf$ googlesamples-assistant-devicetool get --model 'Omer_Link'
-bash: googlesamples-assistant-devicetool: command not found_

**Comment by MightyPiggie** [comment]
I have the same problem.
C:\Users\Daan\Desktop\googleassistant>googlesamples-assistant-pushtotalk --project-id 487137548294 --device-model-id 487137548294Daan
INFO:root:Connecting to embeddedassistant.googleapis.com
WARNING:root:Device config not found: [Errno 2] No such file or directory: 'C:\\Users\\Daan\\AppData\\Roaming\\googlesamples-assistant\\device_config.json'
INFO:root:Registering device
ERROR:root:Failed to register device: {
  "error": {
    "code": 403,
    "message": "Could not create the device instance. You don't have permission to get device model 487137548294Daan. Make sure you registered this device model under your project 487137548294.",
    "status": "PERMISSION_DENIED"
  }
}

**Comment by zhengpenghu** [comment]
@MightyPiggie I doubt your project id is something else, 487137548294 looks like a project number. You can also read my comment above to verify your account's role in the project.

**Comment by MightyPiggie** [comment]
@zhengpenghu Thanks you where right I was using my project number instead of the id. Its working now .

**Comment by Fleker** [comment]
Are there any other issues? It seems like everything has been resolved.

**Comment by zaper4life** [comment]
True that

**Comment by Fleker** [comment]
@surajit7577 have you already registered this device model id? You'll need to do that before running the sample.

**Comment by kwokkawai** [comment]
googlesamples-assistant-pushtotalk --project-id  'gooass' --device-model-id 'gooass-eb6fe-gooass-1k237c'
INFO:root:Connecting to embeddedassistant.googleapis.com
WARNING:root:Device config not found: [Errno 2] No such file or directory: '/home/pi/.config/googlesamples-assistant/device_config.json'
INFO:root:Registering device
ERROR:root:Failed to register device: {
  "error": {
    "code": 400,
    "message": "Request contains an invalid argument.",
    "status": "INVALID_ARGUMENT"
  }
}
