### ISSUE TITLE
no such option: --client-secrets

### ISSUE THREAD

**Issue by MightyPiggie** [googlesamples/assistant-sdk-python#165]
When I run this command ''pip install --upgrade google-auth-oauthlib[tool]
google-oauthlib-tool --client-secrets client_secret_XXXXX.json --scope https://www.googleapis.com/auth/assistant-sdk-prototype --save --headless'' 
I get this error message
''Usage:
  pip install [options] <requirement specifier> [package-index-options] ...
  pip install [options] -r <requirements file> [package-index-options] ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...

no such option: --client-secrets''
How can I fix this?

**Comment by Fleker** [comment]
This should be two separate commands

`pip install --upgrade google-auth-oauthlib[tool]`

and then

`google-oauthlib-tool --client-secrets client_secret_XXXXX.json --scope https://www.googleapis.com/auth/assistant-sdk-prototype --save --headless`

**Comment by neuberfran** [comment]
@Fleker Hi,
I stay trying this: https://github.com/actions-on-google/smart-home-nodejs
with issue invalid cliend_id (oauth) in very time.
About the photo below What is Cliend ID in number 8? (pls)

![fotinha21](https://user-images.githubusercontent.com/38701397/44869173-468a2b00-ac63-11e8-9190-be114b739e24.png)

**Comment by Fleker** [comment]
@neuberfran your question is very unrelated to the Assistant SDK, as the smart home client ID and secret are related to OAuth between the Google Assistant and your server, whereas this issue is with regards to a client secret authenticating a client application to use Google Assistant as a user.

For your case, please view [config-provider.js](https://github.com/actions-on-google/smart-home-nodejs/blob/master/smart-home-provider/cloud/config-provider.js) for those values.

**Comment by neuberfran** [comment]
@Fleker Please help me just one more time.

I'm trying this project (http://nilhcem.com/android-things/google-assistant-smart-home)(https://github.com/Nilhcem/smarthome-androidthings)  two weeks ago and the invalid client_id error in the google home app. Although following this link (https://stackoverflow.com/questions/44288981/how-to-authenticate-user-with-just-a-google-account-on-actions-on-google) I can not set oauth correctly. In the photo below (which is part of the project cited) the author says that google itself should provide the oauth code but I can not authenticate and always fall on this screen in this issue:(https://github.com/actions-on-google/codelabs-nodejs/issues/8)

![fotinha24](https://user-images.githubusercontent.com/38701397/44872432-e64bb700-ac6b-11e8-8701-831b231f4617.png)

**Comment by Fleker** [comment]
You should probably look deeper into all the components of OAuth. You, as the developer, are responsible for the client id and client secret. As part of the OAuth exchange, you should provide Google with an OAuth access token based on the OAuth refresh token that you sent Google earlier.

**Comment by neuberfran** [comment]
@Fleker https://stackoverflow.com/questions/52130557/gcloud-beta-functions-deploy-ha-command-not-update-ha-home-automation-function

Pls help me more

**Comment by neuberfran** [comment]
@Fleker 

Hi,

Pls help me

when I install my actions app called wHome things and I execute the commands : Hey google, turn lightone on / Hey google, turn lighttwo on everything works ok. But after about an hour without use, I happen to have the problems of one of the screens below and it's not a quota issue
![fotinha24](https://user-images.githubusercontent.com/38701397/45131439-5625da00-b163-11e8-9955-80b02ea5f617.png)


![fotinha23 0](https://user-images.githubusercontent.com/38701397/45131449-5c1bbb00-b163-11e8-8f1d-cdd8575c253b.png)

**Comment by Fleker** [comment]
I think your issue is your OAuth integration has some bugs where you aren't requesting a new access token.

**Comment by neuberfran** [comment]
hey @Fleker you said: I think your issue is your OAuth integration has some bugs where you aren't requesting a new access token.

How to solve? (pls)?

**Comment by Fleker** [comment]
I'd look over the [OAuth 2.0 specification](https://developers.google.com/actions/identity/oauth2?oauth=code) and also use the [OAuth playground](https://developers.google.com/oauthplayground/). I think there is an issue in refreshing the tokens if it stops working after an hour.

**Comment by neuberfran** [comment]
@Fleker You said in last post here: https://stackoverflow.com/questions/49431264/why-does-couldnt-update-the-setting-check-your-connection-error-appear-afte

and above, that  is OAuth playground  the solution

I can connect using my access token via browser. 
https://www.youtube.com/watch?v=lJjQPaPAfWM

I select Auto-refresh the token before it expires button in OAuth playground, I put  https://developers.google.com/oauthplayground in Authorized redirect URIs in my gcp console credentials, but I can't delete https://oauth-redirect.googleusercontent.com/r/projectFirebaseId

**### _otherwise I get: “error” : “redirect_uri_mismatch”_**

unfortunately my token  time expiration problem continues:
![wyitr](https://user-images.githubusercontent.com/38701397/45919495-4c42ed00-be6c-11e8-83df-2ff8c7ccb418.png)

**Comment by Fleker** [comment]
@neuberfran I don't know what the internals of your OAuth implementation are, so I'm unable to debug further. It seems like your OAuth implementation does not refresh the access token, and until you resolve that problem it's not going to work. The playground serves as a useful debugging tool, and you should use that to help determine why your system is failing.

If you continue to run into problems, please make a new issue.
