### ISSUE TITLE
Give me permission to help you

### ISSUE THREAD

**Issue by zaper4life** [googlesamples/assistant-sdk-python#166]
Couldn't find anyway to make it work, couldn't find support online, I'm a newb who want to play with experts, if you can help me to get it to work I'll love it.

After running:
python -m pushtotalk --device-id 'my-device-identifier'
I pressed enter and recorded my voice, 
All the assistant is saying back is "give me permission to help you'

I'm a bit confused,
Using Mac OSX High Sierra

**Comment by zhengpenghu** [comment]
It's asked and resolved on stackoverflow already.
https://stackoverflow.com/questions/46482807/google-assistant-sdk-returns-give-me-the-permission-to-help-you

**Comment by zaper4life** [comment]
Amazing it worked! I have my assistant working! wow!

Now what can I do with it?
I've been using it for the last minute to tell me jokes,

It can't start Spotify
It can't set Reminders
It can't even start a timer!

I mean it's funny but what else can I do with it?

Is there a way to teach it stuff?

**Comment by Fleker** [comment]
Things like timers and music are not supported in the Assistant Service. But you can use [Actions on Google](https://developers.google.com/actions/) to add third-party integrations.

**Comment by mishuprovince** [comment]
@zhengpenghu 要在网站上设置什么东西么
