### ISSUE TITLE
Get assistant response.

### ISSUE THREAD

**Issue by JakeBMalis** [googlesamples/assistant-sdk-python#168]
Can someone explain how I could get the assistant's response text on an external screen? Thanks.

**Comment by Fleker** [comment]
You can use the `pushtotalk` sample to get the [`supplemental_display_text`](https://developers.google.com/assistant/sdk/reference/rpc/google.assistant.embedded.v1alpha2#dialogstateout) from the `AssistResponse` and then do what you want with that value.

**Comment by JakeBMalis** [comment]
With this code:

logging.info(DialogStateOut.supplemental_display_text)
        self.conversation_stream.stop_playback()
        return continue_conversation

I get this response:
WARNING:root:SoundDeviceStream read overflow (3200, 6400)
INFO:root:Transcript of user request: "what".
INFO:root:Playing assistant response.
INFO:root:Transcript of user request: "what time".
INFO:root:Playing assistant response.
INFO:root:Transcript of user request: "what time is".
INFO:root:Playing assistant response.
INFO:root:Transcript of user request: "what time is it".
INFO:root:Playing assistant response.
INFO:root:Transcript of user request: "what  time is it".
INFO:root:Playing assistant response.
INFO:root:Transcript of user request: "what time  is it".
INFO:root:Playing assistant response.
INFO:root:Transcript of user request: "what time is  it".
INFO:root:Playing assistant response.
INFO:root:Transcript of user request: "what time is it".
INFO:root:Playing assistant response.
INFO:root:End of audio request detected
INFO:root:Transcript of user request: "what time is it".
INFO:root:Playing assistant response.
Traceback (most recent call last):
  File "pushtotalk.py", line 435, in <module>
    main()
  File "/home/pi/env/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/pi/env/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/pi/env/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pi/env/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "pushtotalk.py", line 424, in main
    continue_conversation = assistant.assist()
  File "/home/pi/env/lib/python3.5/site-packages/tenacity/__init__.py", line 214, in wrapped_f
    return self.call(f, *args, **kw)
  File "/home/pi/env/lib/python3.5/site-packages/tenacity/__init__.py", line 295, in call
    start_time=start_time)
  File "/home/pi/env/lib/python3.5/site-packages/tenacity/__init__.py", line 252, in iter
    return fut.result()
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 398, in result
    return self.__get_result()
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
  File "/home/pi/env/lib/python3.5/site-packages/tenacity/__init__.py", line 298, in call
    result = fn(*args, **kwargs)
  File "pushtotalk.py", line 168, in assist
    logging.info(DialogStateOut.supplemental_display_text)
NameError: name 'DialogStateOut' is not defined


P.S. why do I keep getting the "WARNING:root:SoundDeviceStream read overflow (3200, 6400)" error in the beginning even when I change the audio block number?

**Comment by Fleker** [comment]
You need to take a look at the [textinput](https://github.com/googlesamples/assistant-sdk-python/blob/master/google-assistant-sdk/googlesamples/assistant/grpc/textinput.py) sample.

```Python
    def assist(self, text_query):
        """Send a text request to the Assistant and playback the response.
        """
        def iter_assist_requests():
            dialog_state_in = embedded_assistant_pb2.DialogStateIn(
                language_code=self.language_code,
                conversation_state=b''
            )
            if self.conversation_state:
                dialog_state_in.conversation_state = self.conversation_state
            config = embedded_assistant_pb2.AssistConfig(
                audio_out_config=embedded_assistant_pb2.AudioOutConfig(
                    encoding='LINEAR16',
                    sample_rate_hertz=16000,
                    volume_percentage=0,
                ),
                dialog_state_in=dialog_state_in,
                device_config=embedded_assistant_pb2.DeviceConfig(
                    device_id=self.device_id,
                    device_model_id=self.device_model_id,
                ),
                text_query=text_query,
            )
            req = embedded_assistant_pb2.AssistRequest(config=config)
            assistant_helpers.log_assist_request_without_audio(req)
            yield req

        display_text = None
        for resp in self.assistant.Assist(iter_assist_requests(),
                                          self.deadline):
            assistant_helpers.log_assist_response_without_audio(resp)
            if resp.dialog_state_out.conversation_state:
                conversation_state = resp.dialog_state_out.conversation_state
                self.conversation_state = conversation_state
            if resp.dialog_state_out.supplemental_display_text:
                display_text = resp.dialog_state_out.supplemental_display_text
        return display_text
```
