### ISSUE TITLE
How to autostart the assistant?

### ISSUE THREAD

**Issue by olskar** [googlesamples/assistant-sdk-python#169]
I followed the guide to install this, however nowhere is mentioned how to autostart this on boot of the pi? How is this done?

**Comment by Fleker** [comment]
There's nothing special about this compared to any other script you may want to start on the Pi. This [StackOverflow question](https://raspberrypi.stackexchange.com/questions/8734/execute-script-on-start-up) may help.

**Comment by lev11** [comment]
Similar to here: https://aiyprojects.withgoogle.com/voice#makers-guide-3-4--run-your-app-automatically
But change the text in the service to define alternate locations as here:

`Description=Assistant app

[Service]
ExecStart=/bin/bash -c '/home/pi/env/bin/python -u /home/pi/assistant-sdk-python/google-assistant-sdk/googlesamples/assistant/grpc/pushtotalk.py --device-id <your device id>'
WorkingDirectory=/home/pi/env/bin/
Restart=always
User=pi

[Install]
WantedBy=multi-user.target`
