### ISSUE TITLE
pushtotalk.py - device-id from config file for device action

### ISSUE THREAD

**Issue by NobuHayashi916** [googlesamples/assistant-sdk-python#170]
(Please discard-close if you have fixed this already)

Hi all,

I've been trying to enable action.devices.commands.OnOff with pushtotalk.py with Python command line ($ python pushtotalk.py) on Ubuntu-on-MacbookAir.

It appears, if we use device_id from the saved device_config file, device_id is not properly passed to device_helpers.DeviceRequestHandler(device_id), because it is called *before* device_config file is read.

This results in showing 'Ignoring command for unknown device: %s' message and no-op for any device command.

Proposed fix is to move below lines:
---
    device_handler = device_helpers.DeviceRequestHandler(device_id)

    @device_handler.command('action.devices.commands.OnOff')
    def onoff(on):
        if on:
            logging.info('Turning device on')
        else:
            logging.info('Turning device off')
---
(https://github.com/googlesamples/assistant-sdk-python/blob/master/google-assistant-sdk/googlesamples/assistant/grpc/pushtotalk.py#L358) 

to a section after device_config is being processed.
(https://github.com/googlesamples/assistant-sdk-python/blob/master/google-assistant-sdk/googlesamples/assistant/grpc/pushtotalk.py#L405)

It seems to work fine on my Macubuntu - please advise if above makes sense.

Thanks a bunch for your time!
Cheers, Nobu

**Comment by Fleker** [comment]
But the script does work if you pass `--device-id` as a parameter when you call it?

It's not exactly a bug as we do expect this value to be passed when calling the Python code. But I do see what you mean, that the device id can be obtained from config file as well.

**Comment by NobuHayashi916** [comment]
Correct, the code works if --device-id is specified.

The SDK tutorial instructs us to include --device-id (https://developers.google.com/assistant/sdk/guides/service/python/extend/handle-device-commands), thus this issue isn't critical. 
(I should have it called an improvement, not bugfix - sorry for a scary title)

**Comment by NobuHayashi916** [comment]
FWIW, forlked / modified / verified repo is here:
https://github.com/NobuHayashi916/assistant-sdk-python

**Comment by proppy** [comment]
This should be fixed with https://github.com/googlesamples/assistant-sdk-python/commit/1ef2e7b3817ad4f3461c551fdcea372d32cbd188 released in https://github.com/googlesamples/assistant-sdk-python/releases/tag/0.4.4
