### ISSUE TITLE
Hotword detection for the Google Assistant Service 

### ISSUE THREAD

**Issue by sandblasted7** [googlesamples/assistant-sdk-python#171]
Hello,

I was wondering if there is any example code available for hotword detection for the google assistant service. Or can someone please point me to a direction where I can convert the hotword.py provided with the Library  to work with the Service package? I am working on an project where I am utilising the text response provided by the Service. But I definitely need to add a hotword detection as well. Can someone give any tips? Thank you!

**Comment by Fleker** [comment]
We don't have any sample code for hotword detection using the service. However, there are a few Python packages that can do it, but there is no guarantee of their quality.

Some community members have used the third-party [Snowboy](https://pypi.python.org/pypi/snowboy/1.2.0b1).

**Comment by sandblasted7** [comment]
Thank you for the quick response. I did see an example using Snowboy. I will look into it. Regards.
