### ISSUE TITLE
volume in assistant verry low

### ISSUE THREAD

**Issue by bart-heremans** [googlesamples/assistant-sdk-python#174]
I installed a fresh raspbian image. And installed the assistant-sdk-python.
This in combination with the respeaker 2 mic pi hat (http://wiki.seeed.cc/Respeaker_2_Mics_Pi_HAT/)

Speaker test works fine.
Microphone test also ok.

Volume is ok when i do the speaker test, It is set to 100% with alsamixer.
But when starting the assitant demo the volume is verry low. I already set the volume to max with "okay google set volume to max" 
But the voice feedback is verry silent, I have to put my ear on the speaker to hear it. When i ask to set the volume louder it says that volume is already at max.

Python packages up to date with latest versions    
google_assistant_library-0.1.0-py2.7-nspkg.pth    
google_assistant_sdk-0.4.2-py2.7-nspkg.pth     
google_auth-1.0.1-py2.7-nspkg.pth           

Anybody has an idea ?

**Comment by bart-heremans** [comment]
After some strange reason the seed sound card is now card0

**** List of PLAYBACK Hardware Devices ****
card 0: seeed2micvoicec [seeed-2mic-voicecard], device 0: bcm2835-i2s-wm8960-hifi wm8960-hifi-0 []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: ALSA [bcm2835 ALSA], device 0: bcm2835 ALSA [bcm2835 ALSA]


after changing asoundrc to math the correct card number the volume is okay.
I do not now how I changed the order of the sound cards

**Comment by gerardwr** [comment]
Hi,

I have a similar problem with the latest GA SDK.

Installed a Respeaker 2-mic HAT on my Raspberry Pi 3+, and connected a speaker to the JST connector.

Changed .asound.rc to use the Respeaker. The solution from @bart-heremans was not applicable for me, I checked that the coreect card numbers were set.

The Respeaker mic and speaker work fine, with a high volume on the speaker:
- record audio with "arecord" and then re-play with "aplay"
- Alexa using the avs-device-sdk from https://github.com/alexa/avs-device-sdk
- can increase/decrease the volume level with "alsamixer". It's now set to 50%

So far, so good, BUT:
Using Google Assistant from https://github.com/googlesamples/assistant-sdk-python the volume of the voice response is very low, MUCH lower than using "aplay" or Alexa.

I tried the follwing, but 
- I can increase and decrease the volume using alsamixer but when it is set to max the volume is still very low, MUCH lower than with Alexa or aplay.
- ask GA to set the volume to max

It seems that the Google Assistant SDK has an additional volume setting in the code.

How come that the Respeaker volume is too low using Google Assitant, while it is fine using "apaly" and Alexa? Hoa can I change that?

**Comment by gerardwr** [comment]
I solved my issue.

The problem was caused by differences between the files ~/.asound and /etc/asoundrc.

After I delete the file ~/.asoundrc and rebooted the volume of the Google Assistant was on the same high level as with With Alexa en aplay.

FYI I list the contents of both files:
```(env) pi@raspberrypi3:~ $ cat .asoundrc
pcm.!default {
 type asym
 capture.pcm "mic"
 playback.pcm "speaker"
}
pcm.mic {
 type plug
 slave {
 pcm "hw:1,0"
 }
}
pcm.speaker {
 type plug
 slave {
 pcm "hw:1,0"
 }
}

(env) pi@raspberrypi3:~ $ cat /etc/asound.conf 
# The IPC key of dmix or dsnoop plugin must be unique
# If 555555 or 666666 is used by other processes, use another one

pcm.!default {
    type asym
    playback.pcm "playback"
    capture.pcm "capture"
}

pcm.playback {
    type plug
    slave.pcm "dmixed"
}

pcm.capture {
    type plug
    slave.pcm "array"
}

pcm.dmixed {
    type dmix
    slave.pcm "hw:1,0"
    ipc_key 555555 
}

pcm.array {
    type dsnoop
    slave {
        pcm "hw:1,0"
        channels 2
    }
    ipc_key 666666
}

(env) pi@raspberrypi3:~ $ 
```

**Comment by AGID-WL** [comment]
Here is the log from Youtube command:

`stopping vlc
High Performance MPEG 1.0/2.0/2.5 Audio Player for Layers 1, 2 and 3
	version 1.23.8; written and copyright by Michael Hipp and others
	free software (LGPL) without any warranty but with best wishes

Directory: /tmp/

Terminal control enabled, press 'h' for listing of keys and functions.

Playing MPEG stream 1 of 1: female-say.mp3 ...

MPEG 2.0 L III cbr32 24000 mono

[0:01] Decoding of female-say.mp3 finished.

{'regionCode': 'EG', 'etag': '"SJZWTG6xR0eGuCOh2bX6w3s4F94/gh-YXBIV2XeNpaIcIyu5vl6wDc0"', 'pageInfo': {'resultsPerPage': 5, 'totalResults': 1000000}, 'kind': 'youtube#searchListResponse', 'nextPageToken': 'CAUQAA', 'items': [{'id': {'videoId': 'eyzxu26-Wqk', 'kind': 'youtube#video'}, 'snippet': {'liveBroadcastContent': 'none', 'channelTitle': 'Sony Pictures Entertainment', 'channelId': 'UCz97F7dMxBNOfGYu3rx8aCw', 'description': 'The only thing more dangerous than the front lines was the fight to get there. Screenplay by Tom Hanks inspired by actual events, Greyhound comes to theaters ...', 'publishedAt': '2020-03-05T17:00:07.000Z', 'title': 'GREYHOUND - Official Trailer (HD)', 'thumbnails': {'default': {'width': 120, 'url': 'https://i.ytimg.com/vi/eyzxu26-Wqk/default.jpg', 'height': 90}, 'high': {'width': 480, 'url': 'https://i.ytimg.com/vi/eyzxu26-Wqk/hqdefault.jpg', 'height': 360}, 'medium': {'width': 320, 'url': 'https://i.ytimg.com/vi/eyzxu26-Wqk/mqdefault.jpg', 'height': 180}}}, 'etag': '"SJZWTG6xR0eGuCOh2bX6w3s4F94/nTXDCUa-0YmFRwl6ButpYswl_bE"', 'kind': 'youtube#searchResult'}, {'id': {'videoId': 'LF--yzj4W1s', 'kind': 'youtube#video'}, 'snippet': {'liveBroadcastContent': 'none', 'channelTitle': 'The Late Show with Stephen Colbert', 'channelId': 'UCMtFAi84ehTSYSE9XoHefig', 'description': 'America\'s favorite astrophysicist, host of "Cosmos: Possible Worlds" on NatGeo, stirred up all kinds of trouble when he pointed out the Elsa from "Frozen" isn\'t ...', 'publishedAt': '2020-03-07T08:35:00.000Z', 'title': 'Neil deGrasse Tyson Stands By His Tweet About &quot;Frozen&quot;', 'thumbnails': {'default': {'width': 120, 'url': 'https://i.ytimg.com/vi/LF--yzj4W1s/default.jpg', 'height': 90}, 'high': {'width': 480, 'url': 'https://i.ytimg.com/vi/LF--yzj4W1s/hqdefault.jpg', 'height': 360}, 'medium': {'width': 320, 'url': 'https://i.ytimg.com/vi/LF--yzj4W1s/mqdefault.jpg', 'height': 180}}}, 'etag': '"SJZWTG6xR0eGuCOh2bX6w3s4F94/tCToqFnaeacEOb9apZg0J13E_nk"', 'kind': 'youtube#searchResult'}, {'id': {'videoId': 'N3idyCo4hSw', 'kind': 'youtube#video'}, 'snippet': {'liveBroadcastContent': 'none', 'channelTitle': 'FBE', 'channelId': 'UC0v-tlzsn0QZwJnkiaUSJVQ', 'description': 'Have you subscribed to our new Try Not To Channel yet? Click the link to subscribe now and HIT the bell! https://fbereact.com/SubscribeTryNotTo Generations ...', 'publishedAt': '2020-03-06T22:00:02.000Z', 'title': '10 Tricks Advertisers Use To Make Food Look Delicious | Generations React', 'thumbnails': {'default': {'width': 120, 'url': 'https://i.ytimg.com/vi/N3idyCo4hSw/default.jpg', 'height': 90}, 'high': {'width': 480, 'url': 'https://i.ytimg.com/vi/N3idyCo4hSw/hqdefault.jpg', 'height': 360}, 'medium': {'width': 320, 'url': 'https://i.ytimg.com/vi/N3idyCo4hSw/mqdefault.jpg', 'height': 180}}}, 'etag': '"SJZWTG6xR0eGuCOh2bX6w3s4F94/fJ7Lr-8XKio0iAhoOxquyraIR-I"', 'kind': 'youtube#searchResult'}, {'id': {'videoId': 'nc6dz18GPU0', 'kind': 'youtube#video'}, 'snippet': {'liveBroadcastContent': 'none', 'channelTitle': 'Fox News', 'channelId': 'UCXIJgqnII2ZOINSWNOGFThA', 'description': "Sen. Kelly Loeffler, one of the 14 senators co-sponsoring the resolution, calls for Sen. Schumer's apology on 'Fox & Friends.' #FoxNews FOX News operates the ...", 'publishedAt': '2020-03-06T14:25:00.000Z', 'title': 'Senate Republicans draft resolution to censure Schumer&#39;s SCOTUS &#39;threat&#39;', 'thumbnails': {'default': {'width': 120, 'url': 'https://i.ytimg.com/vi/nc6dz18GPU0/default.jpg', 'height': 90}, 'high': {'width': 480, 'url': 'https://i.ytimg.com/vi/nc6dz18GPU0/hqdefault.jpg', 'height': 360}, 'medium': {'width': 320, 'url': 'https://i.ytimg.com/vi/nc6dz18GPU0/mqdefault.jpg', 'height': 180}}}, 'etag': '"SJZWTG6xR0eGuCOh2bX6w3s4F94/yKVswCg0vzJnYTpHZEg7OM8bntQ"', 'kind': 'youtube#searchResult'}, {'id': {'videoId': '5VsHnpU-Xjc', 'kind': 'youtube#video'}, 'snippet': {'liveBroadcastContent': 'none', 'channelTitle': 'MSNBC', 'channelId': 'UCaXkIU1QidjPwiAYu6GcHjg', 'description': 'A federal judge appointed by George W. Bush issues a scathing critique of Attorney General William Barr over his distortions of the findings of special counsel ...', 'publishedAt': '2020-03-06T23:36:08.000Z', 'title': 'Federal Judge Blasts Barr Over Mueller Report | Deadline | MSNBC', 'thumbnails': {'default': {'width': 120, 'url': 'https://i.ytimg.com/vi/5VsHnpU-Xjc/default.jpg', 'height': 90}, 'high': {'width': 480, 'url': 'https://i.ytimg.com/vi/5VsHnpU-Xjc/hqdefault.jpg', 'height': 360}, 'medium': {'width': 320, 'url': 'https://i.ytimg.com/vi/5VsHnpU-Xjc/mqdefault.jpg', 'height': 180}}}, 'etag': '"SJZWTG6xR0eGuCOh2bX6w3s4F94/yJGlfkqIwuu2bwUDkOaH9PbDDsE"', 'kind': 'youtube#searchResult'}]}
Videos
 GREYHOUND - Official Trailer (HD) (eyzxu26-Wqk)
Neil deGrasse Tyson Stands By His Tweet About &quot;Frozen&quot; (LF--yzj4W1s)
10 Tricks Advertisers Use To Make Food Look Delicious | Generations React (N3idyCo4hSw)
Senate Republicans draft resolution to censure Schumer&#39;s SCOTUS &#39;threat&#39; (nc6dz18GPU0)
Federal Judge Blasts Barr Over Mueller Report | Deadline | MSNBC (5VsHnpU-Xjc) 

Channels:
  

Playlists:
  

ERROR: eyzxu26-Wqk: YouTube said: HTTP is not supported.
ERROR: eyzxu26-Wqk: Youtube says: HTTP is not supported.
High Performance MPEG 1.0/2.0/2.5 Audio Player for Layers 1, 2 and 3
	version 1.23.8; written and copyright by Michael Hipp and others
	free software (LGPL) without any warranty but with best wishes

Directory: /tmp/

Terminal control enabled, press 'h' for listing of keys and functions.

Playing MPEG stream 1 of 1: female-say.mp3 ...

MPEG 2.0 L III cbr32 24000 mono

[0:03] Decoding of female-say.mp3 finished.
ON_CONVERSATION_TURN_FINISHED:
  {"with_follow_on_turn": false}
`
Hope it helps
