### ISSUE TITLE
How can I change voice to British (en-GB)?

### ISSUE THREAD

**Issue by bedfelllow** [googlesamples/assistant-sdk-python#175]
How can the voice be changed from the default American (en-US) to British (en-GB)? I tried argument `--lang='en-GB'` but this resulted in `google-assistant-demo: error: unrecognized arguments: --lang=en-GB`

**Comment by janvda** [comment]
The following worked for me

 --lang 'en-UK'

**Comment by bedfelllow** [comment]
`google-assistant-demo: error: unrecognized arguments: --lang en-UK`

**Comment by janvda** [comment]
It worked for me when using:

> googlesamples-assistant-pushtotalk

E.g. the full command I have used looks like:

> googlesamples-assistant-pushtotalk --device-id  'FDA1...4F8'  --device-model-id 'pi.....t'  --lang 'en-UK'

Of course you have to specify your device-id and  device-model-id.

**Comment by bedfelllow** [comment]
I have `google-assistant-demo --device_model_id="o...e"`
When I add `--lang='en-UK'` or `--lang 'en-UK'` I get `google-assistant-demo: error: unrecognized arguments: --lang en-GB`
Maybe it's a syntax error?

**Comment by bedfelllow** [comment]
If I add `--device-id` to the string I then get `google-assistant-demo: error: unrecognized arguments: --device-id`

**Comment by janvda** [comment]
I admit I have not used "google-assistant-demo", so it looks like the option --lang is not supported for this script.
But I can tell you that the option --lang works for googlesamples-assistant-pushtotalk.

**Comment by bedfelllow** [comment]
Unfortunately, googlesamples-assistant-pushtotalk is not supported on the system I'm running.

**Comment by Fleker** [comment]
What system is `google-assistant-pushtotalk` not going to work for? It is designed to be much more flexible.

The `google-assistant-demo` is using [the library](https://github.com/googlesamples/assistant-sdk-python/blob/master/google-assistant-library/README.rst), which does not accept `lang` as a parameter. To change its locale, you will need to register the device and then modify it in the Google Assistant on your phone. (Assistant -> Settings -> Devices)

**Comment by bedfelllow** [comment]
I have google-assistant-demo installed on an Orange Pi Lite, using the instructions from here [https://www.cnx-software.com/2017/07/30/how-to-setup-an-orange-pi-zero-diy-smart-speaker-with-google-assistant-sdk/](url)

I have Google assistant installed on my phone but the Orange Pi does not show in Assistant -> Settings -> Devices

**Comment by Fleker** [comment]
It looks like the blog post is relatively old, so it does not include instructions on how to [register the device](https://developers.google.com/assistant/sdk/guides/library/python/embed/register-device) and have it show up in your Assistant settings.

**Comment by bedfelllow** [comment]
Following @Fleker advice, I have resolved the issue by installing a newer version of the SDK per the instruction [here](https://developers.google.com/assistant/sdk/guides/service/python/), which then allow me to register the device and change the setting on my phone.
