### ISSUE TITLE
How to Add Switch to trigger Google Assistant ?

### ISSUE THREAD

**Issue by Kinjalk** [googlesamples/assistant-sdk-python#18]
Please can you help me with adding switch to trigger google assistant ? Pressing enter every time is very annoying

**Comment by proppy** [comment]
See the Google+ discussion about this [here](https://plus.google.com/101714911555226603504/posts/RwuJARZua3s)

**Comment by proppy** [comment]
The README is actually referring to the go command line tool:
https://github.com/google/oauth2l/tree/master/go/oauth2client#command-line-tool

**Comment by oscartprom** [comment]
We have an example of this in the Mocktails Mixer write-up. Instructions to wire the button are [here](https://github.com/Deeplocal/mocktailsmixer#final-connections) and the code is [here](https://github.com/Deeplocal/mocktailsmixer/blob/master/software/rpi/__main__.py) (lines of interest are mainly 150-181).

**Comment by capitalfuse** [comment]
sysfs method;
1.add the followings definitions
```
def read_button():
    fp1 = open("/sys/class/gpio/gpio6/value","r")
    value = fp1.read()
    return int(value)
    fp1.close()

def write_led(value):
    fp2 =  open("/sys/class/gpio/gpio20/value","w")
    fp2.write(str(value))
    fp2.close()
```
2. Modify the code
```
        while True:
            if wait_for_user_trigger:
                while True:                
                    #print(read_button())
                    button_status = read_button()
                    if button_status == 1:
                        break
            write_led(1)
                #click.pause(info='Press Enter to send a new request...')
            continue_conversation = assistant.converse()
            # wait for user trigger if there is no follow-up turn in
            # the conversation.
            wait_for_user_trigger = not continue_conversation
            write_led(0)
            # If we only want one conversation, break.
            if once and (not continue_conversation):
                break
```
