### ISSUE TITLE
Cloud discovery nupnp request failed: Peer certificate cannot be authenticated with given CA certificates

### ISSUE THREAD

**Issue by BlackLight** [googlesamples/assistant-sdk-python#192]
I've been getting this error since yesterday whenever I start the assistant, on any of the machines where I installed it:

```
[8090:8152:ERROR:assistant_nupnp_client.cc(103)] Cloud discovery nupnp request failed: [-1] Peer certificate cannot be authenticated with given CA certificates
```

It prevents any response from being processed, but it doesn't prevent text recognition itself.

Things I have tried with no success:

* Generate new OAuth credentials

* Update to the latest version

Any help?

**Comment by Fleker** [comment]
Are you using the library (hotword) or service (pushtotalk)? I couldn't reproduce it using gRPC calls.

**Comment by silvacharles** [comment]
I am facing the same problem, I am using (hotword), I did the same update procedures and I even generated new credentials.

but nothing ... the error continues, but the questions and answers are working.

 

> ON_MUTED_CHANGED:
>   {'is_muted': False}
> ON_START_FINISHED
> [6327:6346:ERROR:assistant_nupnp_client.cc(103)] Cloud discovery nupnp request failed: [60] Peer certificate cannot be authenticated with given CA certificates
> [6327:6346:ERROR:assistant_nupnp_client.cc(103)] Cloud discovery nupnp request failed: [60] Peer certificate cannot be authenticated with given CA certificates
> [6327:6346:ERROR:assistant_nupnp_client.cc(103)] Cloud discovery nupnp request failed: [60] Peer certificate cannot be authenticated with given CA certificates
> 
> ON_CONVERSATION_TURN_STARTED
> ON_END_OF_UTTERANCE
> ON_RECOGNIZING_SPEECH_FINISHED:
>   {'text': 'what time is it'}
> ON_RESPONDING_STARTED:
>   {'is_error_response': False}
> ON_RESPONDING_FINISHED
> ON_CONVERSATION_TURN_FINISHED:
>   {'with_follow_on_turn': False}
> 
>

**Comment by BlackLight** [comment]
I'm using the hotword. Yesterday the answers were impacted as well (speech was recognized but no answer). Now answers work, but the error is still there. I can investigate if I can reproduce with push to talk as well.

**Comment by electromaniac24** [comment]
i am having the same error , using aiy projects to interface google assistant with magicmirror and when i run the script i get this error , it responds to voice commands but the voice is different i think the responses are not being processed,
{following this: https://medium.com/@aallan/a-magic-mirror-powered-by-aiy-projects-and-the-raspberry-pi-e6a0fea3b4d6}

**Comment by Fleker** [comment]
I'm curious as to whether this is related to the library. Can anyone reproduce using `pushtotalk.py`?

**Comment by yoelrc88** [comment]
Same here in Rasp Pi 3:
```
^C^[[A(env) pi@google-assist-sdk:~ $ googlesamples-assistant-hotword --project_id goggle-assist-sevice_model_id goggle-assist-sdk-model
device_model_id: goggle-assist-sdk-model
device_id: B43210DBDDC5C66A125492C63C6B4A34

https://embeddedassistant.googleapis.com/v1alpha2/projects/goggle-assist-sdk/devices/B43210DBDDC5C66A125492C63C6B4A34 200
[1818:1835:ERROR:assistant_nupnp_client.cc(103)] Cloud discovery nupnp request failed: [60] Peer certificate cannot be authenticated with given CA certificates
[1818:1835:ERROR:assistant_nupnp_client.cc(103)] Cloud discovery nupnp request failed: [60] Peer certificate cannot be authenticated with given CA certificates
EventType.ON_MUTED_CHANGED
EventType.ON_START_FINISHED
[1818:1835:ERROR:assistant_nupnp_client.cc(103)] Cloud discovery nupnp request failed: [60] Peer certificate cannot be authenticated with given CA certificates
```

**Comment by Fleker** [comment]
Thanks for reporting everyone. After talking with a few other engineers, this error is being logged due to some legacy features that are being deprecated. It should not impact you from actually running the sample and the error will be removed in an upcoming SDK release.
