### ISSUE TITLE
Newest Sdk broadcast the message problem. 

### ISSUE THREAD

**Issue by adas4190** [googlesamples/assistant-sdk-python#196]
I have latest sdk setup on my raspberry pi3 and It won't broadcast the message, it was possible on previous release. I have 2 GH and raspi assistant says she cannot found any..  
Thank You.

**Comment by Fleker** [comment]
You're trying the broadcast system? ie, saying "Broadcast <message>"?

**Comment by adas4190** [comment]
Yes. It used to work like on real gh. I could say broad cast the message
and it was asking me what is the message. It looks like this function is
still there but device on new sdk won't recognize my real gh in the network
so it won't broadcast the message.

**Comment by Fleker** [comment]
Are you using the Service API (pushtotalk) or the Library (hotword)?

**Comment by adas4190** [comment]
Hotword

**Comment by adas4190** [comment]
To be more specific gassistpi project.

**Comment by Fleker** [comment]
The library [should now support](https://developers.google.com/assistant/sdk/release-notes) sending broadcasts.
