### ISSUE TITLE
Cannot unline device from google home

### ISSUE THREAD

**Issue by adas4190** [googlesamples/assistant-sdk-python#197]
I have had few google assistant project setup on my raspberry pi3. I used to unlink devices and they dissapear from google home app. On the latest sdk I can't do that anymore. As I mess google assistant I have 4 additional devices in GH app. 

Thank You.

**Comment by skogsmaskin** [comment]
Same here, got a unamed entry in my list after updating the SDK, which can't be removed.

![2018-03-06 14 44 19](https://user-images.githubusercontent.com/373403/37035519-22366a6c-214d-11e8-804c-4f60a2041c1f.png)

**Comment by Fleker** [comment]
You should be able to use the devicetool to delete a device of a given id.

**Comment by adas4190** [comment]
I could use the tool and it would work but what I did is thst I have hanged
the google assistant project. Same account but different credential and my
old devices doesn't show up when I use the tool. Only the current one comes
up.

**Comment by Fleker** [comment]
Can you try using your previous credentials to delete them?

**Comment by adas4190** [comment]
I would but I have deleted my secret json file in my project page and I
dont know how to restore it.

**Comment by Fleker** [comment]
You can get all of your API keys in the Google Cloud console for your project.

**Comment by adas4190** [comment]
Ok. I'll give it a go. Thank You
