### ISSUE TITLE
About the waiting time of the "pushtotalk" command.

### ISSUE THREAD

**Issue by yuta0719** [googlesamples/assistant-sdk-python#199]
Hi,
Can I change the waiting time of the "pushtotalk" command,
changing Option or Python code ?

---------------------------------
googlesamples-assistant-pushtotalk
INFO:root:Connecting to embeddedassistant.googleapis.com
Press Enter to send a new request...
INFO:root:Recording audio request.
... <---- waiting time 
INFO:root:End of audio request detected.
INFO:root:Finished playing assistant response.

**Comment by yuta0719** [comment]
I'm sorry I didn't explain it clearly enough.
Is it possible to extended time for speech waiting ?
In the current situation, it takes about 8 seconds from display "Recording audio request" to display "End of audio request" when there is no speech.
Can I lengthen that about 8 seconds ?
(I'm sorry. I revised it because there was a mistake in the position of the "waiting time" of the sample.)

**Comment by Fleker** [comment]
So you want to extend the time it waits to end the recording?

Right now the sample keeps waiting for an `END_OF_UTTERANCE` event, when it waits for you to stop speaking and it ends the request. You can do this on your own, by waiting for a given time or checking for an end to speech.

**Comment by yuta0719** [comment]
Hi Fleker,
Thanks for the reply.

I was able to adjust the dialogue by modifying the source near END_OF_UTTERANCE (for resp in self.assistant.Assist ...) of pushtotalk.py.
Thanks for the information.
