### ISSUE TITLE
Text input sample no audio

### ISSUE THREAD

**Issue by BramV122** [googlesamples/assistant-sdk-python#200]
Hi,

I'm trying to integrate the text input sample with aiy voice kit code.
I'm trying to get custom answers with the text input example by trying to use "repeat after me".
I get a text response in the console but no audio output.

How can I solve this?

**Comment by Fleker** [comment]
The text input sample does not include audio output, but the audio is still being sent. You can take a look at how to do it through the [pushtotalk](https://github.com/googlesamples/assistant-sdk-python/blob/master/google-assistant-sdk/googlesamples/assistant/grpc/pushtotalk.py#L142) sample and replicate that.
