### ISSUE TITLE
understanding of the new update sdk 0.4.4

### ISSUE THREAD

**Issue by aandroide** [googlesamples/assistant-sdk-python#202]
I noticed that you added the device template registration in the google actions https://console.actions.google.com/
I noticed that if I imitate the Italian language and unload the json credentials and run hotworld.py, the raspberry always speaks in english.
I miss something or the Italian language has not been enabled yet? is the choice of the Italian language now available from the assitant app?
Thanks to those who will help me understand

**Comment by Fleker** [comment]
For changing the language in the library you will need to, after registering, go to the Google Assistant settings on a phone and update the language for the device.

**Comment by aandroide** [comment]
thanks for the reply, so I confirm that it has nothing to do with the fact that when you create a project in the google actions, even if you set the Italian language and create the json credentials, if the assistant library does not present the language, it will not appear in the assistant app.
For a moment I thought it was finally possible.

**Comment by Fleker** [comment]
Italian support is not available yet. When it is, it will be a server-side change and won't need to be a client-side update.
