### ISSUE TITLE
Does hotword detection work locally?

### ISSUE THREAD

**Issue by subjectxbj** [googlesamples/assistant-sdk-python#204]
Hi,

Because google assistant library provide such a high level API, that I'm not clear how does hotword detection works. Is it working remotely or locally? If it works remotely, then the client need to keep on listening to the microphone and sending audio data to remote server. This is not an efficient way. But if it is processed locally, why google does not add it to google assistant service?

Thanks,
Arthman

**Comment by Fleker** [comment]
It's a hotword model which runs locally that is closed source.

**Comment by subjectxbj** [comment]
Thanks.
