### ISSUE TITLE
How to get output from hotword?

### ISSUE THREAD

**Issue by kenanEkici** [googlesamples/assistant-sdk-python#205]
I would like the output of the audiostream from hotword so I can play it back on another speaker over the network. Any idea how to achieve this?

**Comment by Fleker** [comment]
Using the hotword sample / library, the audio playback is coupled to Alsa. In theory you may be able to do some routing in a soundcard to play to a remote device.

Alternatively, using the Service API / pushtotalk, you do get the raw audio bytes which would make it easier to stream elsewhere.

**Comment by kenanEkici** [comment]
Unfortunately push to talk as the name implies, requires action first which doesnt suit my situation. I wouldve really liked if it was possible to capture the output from hotword some way or another...

**Comment by Fleker** [comment]
Using the service API would give you more flexibility, although it would require some extra work to incorporate a 3P hotword library like Snowboy.
