### ISSUE TITLE
 information credential.json

### ISSUE THREAD

**Issue by aandroide** [googlesamples/assistant-sdk-python#207]
hello, I followed the new guide to register the device model using the actions on google and enabling assistant in the project console.
I then downloaded the credential.json file and copied it to home / pi,
everything seems to spin smoothly I copied the generated url and given the required consent.
but when I run on the terminal:
(env) pi@raspberrypi:~ $ googlesamples-assistant-devicetool list --model
Error: Error loading client secret: [Errno 2] No such file or directory: 'client_secret_916478789940-qtjl6qk2l6ii7etioceodosoauqgerap.apps.googleusercontent.com.json'.
Run the device tool with --client-secrets or --project-id option.
Or copy the client_secret_916478789940-qtjl6qk2l6ii7etioceodosoauqgerap.apps.googleusercontent.com.json file in the current directory.

I get these errors because I would like the credential.json file downloaded from the project console and not from google actions.
why?
how should we behave precisely so as not to make mistakes?

**Comment by Fleker** [comment]
You should make sure to include the credentials file you downloaded in your command.

`googlesamples-assistant-devicetool --client-secrets /path/to/credentials.json list --model`

**Comment by aandroide** [comment]
perfect as it works. therefore it is no longer necessary to download credentials.json from the project console
you confirm?
thank you so much

**Comment by aandroide** [comment]
I found the device on the phone in the app assistant I tried to change the language trying all but always speaks in English.
does it happen to you too?

**Comment by Fleker** [comment]
If you use the console a lot of the devicetool capabilities do not need to be used, but you still need to download it and generate credentials that can be used for a specific device.

Are you trying to set language for the hotword or pushtotalk sample?

**Comment by aandroide** [comment]
for hotword.
pushtotalk works well.
thank you

**Comment by Fleker** [comment]
Can you confirm the device running the hotword sample has the same instance and model ids as the device in your phone's settings?

**Comment by aandroide** [comment]
I run the hotword file with the model id obtained from google actions
googlesamples-assistant-hotword --device_model_id 'my-model-identifier'

among other things, I wonder if it is correct that it is no longer necessary to declare the project_id also when using hotword
googlesamples-assistant-hotword --project_id ******** --device_model_id *********
Honestly I'm a bit 'confused about what is the correct option.
I thank you for helping me

**Comment by aandroide** [comment]
I noticed that if I also declare the project_id in hotword I get the answer:
device_model_id: my-model
device_id: my-device-id

https://embeddedassistant.googleapis.com/v1alpha2/projects/my-project-id/devices/my-device-id 200
while instead if I do:
googlesamples-assistant-hotword --device_model_id 'my-model-identifier'
I do not get the answer:
https://embeddedassistant.googleapis.com/v1alpha2/projects/my-project-id/devices/my-device-id 200
even if the language change seems to work anyway

**Comment by aandroide** [comment]
https://github.com/shivasiddharth/GassistPi/issues/179
a user had my same problem we solved by entering the project id this is a bug?

**Comment by aandroide** [comment]
I open another discussion to avoid confusion
