### ISSUE TITLE
Problem with python -m pip install --upgrade google-assistant-sdk[samples]  (Command "python setup.py egg_info" failed with error code )

### ISSUE THREAD

**Issue by ManPython** [googlesamples/assistant-sdk-python#214]
python-3.6.4-amd64

python -m pip install --upgrade google-assistant-sdk[samples]   

 ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\x\AppData\Local\Temp\pip-build-9iz9x062\googleapis-common-protos\

**Comment by Fleker** [comment]
Are you running in a [Python virtual environment](https://docs.python.org/3/library/venv.html)?

**Comment by ManPython** [comment]
Similar like in link, use venv helped me
https://github.com/googlesamples/assistant-sdk-python/issues/215
