### ISSUE TITLE
Google Assistant Library - retrieve text of response?

### ISSUE THREAD

**Issue by MKB787** [googlesamples/assistant-sdk-python#216]
I have embedded the Google Assistant SDK Library in a Ubuntu virtual machine.
Is it possible to retrieve the text of the Assistant's response to queries in the terminal when using the Library?
I see that this is possible via the supplemental_display_text field with the Google Assistant Service, but I couldn't find the equivalent option for the Library.

**Comment by Fleker** [comment]
I don't believe this field is currently exposed in the library.

**Comment by Fleker** [comment]
This is now part of the library.

**Comment by checkomkar** [comment]
How to use ON_RENDER_RESPONSE to display text in a webpage?
