### ISSUE TITLE
google-assistant-demo -  python: can't open file 'google-assistant-demo': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by ManPython** [googlesamples/assistant-sdk-python#217]
google-assistant-demo  
gives -  python: can't open file 'google-assistant-demo': [Errno 2] No such file or directory

Looks like https://github.com/googlesamples/assistant-sdk-python/blob/master/README.md 
..is very not actual and all SDK is doing chaos after changes of version and related instructions

Should exist idea as 

goodle-assistant-sdk.1.0-python
goodle-assistant-sdk.1.1-python
goodle-assistant-sdk.1.2-python
goodle-assistant-sdk.2.0-python

**Comment by Fleker** [comment]
You may need to run it within the context of Python: `python -m google-assistant-demo`.

Renaming it for each version may not make much sense, as there's the expectation to only have one version of this module on your computer. It's not meant to be a versioned SDK but rather a quick sample to get started.

**Comment by ManPython** [comment]
But instaling SDK by PIP there is no file google-assistant-demo, thats made all SDK instructions unuseful
