### ISSUE TITLE
Problem with registering custom device actions

### ISSUE THREAD

**Issue by KaeYan** [googlesamples/assistant-sdk-python#220]
Hi Please Help! 

I want to create my own custom command to control my robot with the device actions, however, when I followed the steps in this link https://developers.google.com/assistant/sdk/guides/library/python/extend/custom-actions

The actions does not work, the assistant does not know how to help with the command, for this example, it is "Ok Google, blink the light 5 times" 

Would really appreciate any helps!

**Comment by KaeYan** [comment]
Hi Fleker, 

Ya, I registered my device model and deployed the action package, as shown in the google assistant sdk documentation. Is it related to the google assistant sdk version? I saw that the device actions is only supported from 0.4.4 onwards, is it true?

Best Regards,
Goh Kae Yan

**Comment by Fleker** [comment]
Custom device actions shouldn't be too tightly coupled to the SDK version you use, although it should be 0.4.x.

**Comment by KaeYan** [comment]
Hi Fleker, 

Appreciate your reply!

I re-registered and deploy the action package for the blinking light tutorials, it works well. However, now I am trying to create my own device package. I went through gactions update and gactions test, however I think due to the schema error, I cannot trigger my custom command. 

Can you/anyone help me to check if there is any error in the schema? Basically, I want to trigger a simple actions, the command is "I want to go to (goal) now", and I want to capture the (goal) as the parameter
[actions.zip](https://github.com/googlesamples/assistant-sdk-python/files/1870752/actions.zip)
. 

Thanks!

**Comment by Fleker** [comment]
The problem with your action is that `$SchemaOrg_Text` is not supported as a usable schema type (see #221). In the short-term you will need to pick a different schema or create a custom schema type.

**Comment by KaeYan** [comment]
Thanks for the reply!

So if I just want to capture the part as a String? Because if I create a custom schema type, I need to specify all the available goals. What are the other schema that I can create to capture as a String? Thanks!

**Comment by 5AMsan** [comment]
@KaeYan,
I'm struggling with a similar issue, trying to link mpd actions on my device (rpi2).
Did you setup a new project and then published the action on or did you published the action on the project where the device is registered ?
I also used schema.org_text as type, is this an issue ?

**Comment by Fleker** [comment]
The text schema type has since been added.
