### ISSUE TITLE
Query patterns with $SchemaOrg_Text are not working

### ISSUE THREAD

**Issue by hzeroo** [googlesamples/assistant-sdk-python#221]
Changing a working action from using SchemaOrg_Number to SchemaOrg_Text results in the action not being recognized.

```
"trigger": {
                  "queryPatterns": [
                      "play $SchemaOrg_Text:query"
                  ]
```

```
$ play 5
Works
# Replaced SchemaOrg_Number with SchemaOrg_Text
$ play something
Sorry, I don't understand you
```

Using google asssistant service with nodejs, but i don't think it matters?

**Comment by Fleker** [comment]
Yes this is a bug in the action packages right now.

**Comment by Fleker** [comment]
This should now be fixed
