### ISSUE TITLE
"There was a glitch" response in hotword.py 

### ISSUE THREAD

**Issue by gerardwr** [googlesamples/assistant-sdk-python#223]
Hi,

I'm running the hotword.py example on an Orange Pi with Armbian

It works fine. The "OK Google" is recognised, and voice requests gets the correct voice response.

But lately the respons to voice requests is faulty on a reguar basis, on a daily basis. After speaking "OK Google" i get a voice response like:
"Hmmm, something went wrong, try again ...."
"There was a glitch, try again ....

When this happens the network connection of the OrangePI is active and working:
- I can ping google.com
- I can SSH to the OrangePI from another computer

Google Assistance is running as a service, that starts a boot time:

```
(env) pi@orangepione:~/Google-Assistant-SDK$ cat /etc/systemd/system/google-assistant-demo.service
[Unit]
Description=google assistant service
After=network.target ntpdate.service

[Service]
Type = idle
Environment=VIRTUAL_ENV=/home/pi/Google-Assistant-SDK/
Environment=PATH=/home/pi/Google-Assistant-SDK/env/bin:/usr/local/sbin:/usr/local
ExecStart=/bin/bash /home/pi/Google-Assistant-SDK/hotword.sh
WorkingDirectory=/home/pi/
StandardOutput=syslog
StandardError=syslog
Restart=always
User=pi

[Install]
WantedBy=multi-user.target
Alias=google-assistant.service
```

I assume that:
- The recognition of "OK Google" is done locally
- The voice response like "There was a glitch..." is done locally
- The connection between the OrangePi and the Google Assistant cloud service was somehow interrupted.

What can I do to investigate the source of the problem, and correct it?

**Comment by gerardwr** [comment]
@Fleker 
Thanks for your response, triggered by it I have been diving into possible logs now, but need some more studying.

The systemd log contains some entries when starting or stopping the service like:
```
pi@orangepione:~/Google-Assistant-SDK$ sudo journalctl -u google-assistant-demo.service
-- Logs begin at Sat 2018-04-07 00:17:08 CEST, end at Sun 2018-04-08 00:19:57 CEST. --
Apr 08 00:06:37 orangepione systemd[1]: Stopped google assistant service.
Apr 08 00:08:43 orangepione systemd[1]: Started google assistant service.
Apr 08 00:08:49 orangepione pulseaudio[20610]: [pulseaudio] sink.c: Default and alternate sample rates are the same.
Apr 08 00:08:49 orangepione pulseaudio[20610]: [pulseaudio] server-lookup.c: Unable to contact D-Bus: org.freedesktop.DBus.Erro
Apr 08 00:08:49 orangepione pulseaudio[20610]: [pulseaudio] main.c: Unable to contact D-Bus: org.freedesktop.DBus.Error.NotSupp
```

And at every "OK Google" voice request the systemd log contains:
```
Apr 08 00:11:16 orangepione bash[20602]: sh: 1: sudo: not found
Apr 08 00:12:16 orangepione bash[20602]: sh: 1: sudo: not found
```

Not sure where the "sudo: not found" but that does not seem right.

Considering the fact that hotword.py runs fine inititally, and only get the "light" after some time, it possibly has nothing to do with my original issue, but I'll investigate further.

**Comment by moham96** [comment]
Do you use sudo inside  `/home/pi/Google-Assistant-SDK/hotword.sh` ?
Maybe you exported a `PATH` env variable that doesn't contain the path of sudo which is usually `/usr/bin/sudo`.
Try this path :
`Environment=PATH=/home/pi/Google-Assistant-SDK/env/bin:/usr/bin:/usr/local/sbin:/usr/local`

I can see you are using pulseaudio. try uninstalling it and using alsa only with a proper asoundrc config

**Comment by gerardwr** [comment]
@moham96 
Thx for your suggestions.

Please note that my Google Assistant setup generally works fine, but after not using it for a few hours repruducing the voice respone "there was a glitch .....". After Stopping and starting the systemd service, it works fine again.

> Do you use sudo inside /home/pi/Google-Assistant-SDK/hotword.sh ?

No, I created a script that runs OK on the command line. I use the same script in the systemd service:
```
pi@orangepione:~/Google-Assistant-SDK$ cat hotword.sh 
source env/bin/activate
googlesamples-assistant-hotword --device_model_id gwr-light
```

> Maybe you exported a PATH env variable that doesn't contain the path of sudo which is usually /usr/bin/sudo.
> Try this path :
> Environment=PATH=/home/pi/Google-Assistant-SDK/env/bin:/usr/bin:/usr/local/sbin:/usr/local

Yes! Tried the path, and the error  "sudo: not found" is gone.
```
pi@orangepione:~/Google-Assistant-SDK$ sudo journalctl -u google-assistant-demo.service
-- Logs begin at Sun 2018-04-08 06:53:01 CEST, end at Sun 2018-04-08 11:51:03 CEST. --
Apr 08 11:50:46 orangepione systemd[1]: Stopped google assistant service.
Apr 08 11:50:49 orangepione systemd[1]: Started google assistant service.
Apr 08 11:50:54 orangepione bash[20283]: /home/pi/Google-Assistant-SDK/hotword.sh: line 1: env/bin/activate: No such file or di
Apr 08 11:51:03 orangepione pulseaudio[20314]: [pulseaudio] sink.c: Default and alternate sample rates are the same.
```

>I can see you are using pulseaudio. try uninstalling it and using alsa only with a proper asoundrc config

I installed pulseaudio just recently, and I had the "glitch" way before the install. But I'll try it anyway.

Thanks so far, will post my experience here.

**Comment by moham96** [comment]
@gerardwr You have another error
```
Apr 08 11:50:54 orangepione bash[20283]: /home/pi/Google-Assistant-SDK/hotword.sh: line 1: env/bin/activate: No such file or di
```
obviously the bash script can't find the the bath of the activate file, Also you don't need a bash script for such a simple commad, Try the following service file:
```

[Unit]
Description=google assistant service
After=network.target ntpdate.service

[Service]
Type = idle
Environment=VIRTUAL_ENV=/home/pi/Google-Assistant-SDK/
Environment=PATH=/home/pi/Google-Assistant-SDK/env/bin:/usr/bin:/usr/local/sbin:/usr/local
ExecStart=/home/pi/Google-Assistant-SDK/env/bin/python -u googlesamples-assistant-hotword --device_model_id gwr-light
WorkingDirectory=/home/pi/
StandardOutput=syslog
StandardError=syslog
Restart=always
User=pi

[Install]
WantedBy=multi-user.target
Alias=google-assistant.service
```
Or if you need to use the bash script you can correct the env path as follows:
```
source ./Google-Assistant-SDK/env/bin/activate
googlesamples-assistant-hotword --device_model_id gwr-light
```
I am assuming that `/home/pi/Google-Assistant-SDK/env/bin/python` is the correct path of your venv

**Comment by moham96** [comment]
@gerardwr  I'm sorry but the previous service file that i posted is incorrect  and won't run, I've updated the comment use the updated one.
for debugging maybe changing :
```
StandardOutput=syslog
StandardError=syslog
```
to :
```
StandardOutput=journal
StandardError=journal
```
Might help.
Also you can use the logging module of python

**Comment by gerardwr** [comment]
@moham96 

The more I'm looking at logs and changes I make change errors keep popping up :(

Note that Google Assistant is working OK. "OK Google" is recongnised, and "What is the time" results in a valid voice response.

I tried the update service file (had trouble with the previous one).

Below the service log while issuing the command "OK Google what is the time". At every command:
- the time is spoken
- error "sudo: no tty present and no askpass program specified"
- error "pam_unix(sudo:auth): auth could not identify password for [pi]"

Seems like a right issue, but it's above my head what all happening.

```
pi@orangepione:~/Google-Assistant-SDK$ sudo journalctl -f -u google-assistant-demo.service
-- Logs begin at Mon 2018-04-09 11:43:48 CEST. --
Apr 09 14:36:10 orangepione systemd[1]: Stopped google assistant service.
Apr 09 14:36:13 orangepione systemd[1]: Started google assistant service.
Apr 09 14:36:32 orangepione python[19756]: sudo: no tty present and no askpass program specified
Apr 09 14:36:42 orangepione python[19756]: sudo: no tty present and no askpass program specified
Apr 09 14:36:42 orangepione sudo[19840]: pam_unix(sudo:auth): auth could not identify password for [pi]
Apr 09 14:36:55 orangepione python[19756]: sudo: no tty present and no askpass program specified
Apr 09 14:36:55 orangepione sudo[19850]: pam_unix(sudo:auth): auth could not identify password for [pi]
```

**Comment by moham96** [comment]
You main issue which is "There was a glitch" Is gone? or is it still there?

**Comment by gerardwr** [comment]
@moham96 

I've been working on the changes you suggested, so the service has not been running for a longer period. So I cannot say if the "glitch" is gone.

I'll leave the config alone for a few days, and then report back.

Thx so far :-)

**Comment by gerardwr** [comment]
@moham96 
I've had no more "glitch" warnings since my last report, so it's safe to say that this issue can be closed now.

Thx for your help!
