### ISSUE TITLE
assistant-sdk-c++ ?

### ISSUE THREAD

**Issue by Pillar1989** [googlesamples/assistant-sdk-python#23]
Hi
    Does google have any plans to develop c++ sdk ? A lot of devices dont have python engine.

**Comment by proppy** [comment]
Can you repost this question on the [Google+ community](g.co/assistantsdkdev)?

**Comment by Pillar1989** [comment]
@proppy Page not found.

**Comment by proppy** [comment]
@Pillar1989 try again !

**Comment by alfongj** [comment]
@Pillar1989 You can generate your own bindings for the API on C++. See the instructions [here](https://developers.google.com/assistant/sdk/prototype/getting-started-other-platforms/)
