### ISSUE TITLE
Google Assistant Service won't accept Google Cloud text-to-speech mp3 file as input

### ISSUE THREAD

**Issue by MKB787** [googlesamples/assistant-sdk-python#231]
I am attempting to synthesise audio versions of commands to Google Assistant and to provide them as input to the Google Assistant Service via the terminal as in the following example:

(env) mkb3@ubuntu:~$ googlesamples-assistant-pushtotalk -i light.mp3

The Assistant does listen to the audio file, but does not recognise or respond to the command (by contrast, it does respond to an audio file containing a recording of a human voice saying a Google command).

Is it possible to use synthesised speech as input to the Assistant?

**Comment by moham96** [comment]
Maybe google assistant uses some sort of [VAD](https://en.wikipedia.org/wiki/Voice_activity_detection) technology to detect whether the audio input contains a human voice or not.

PS:This is just guessing,I'm not a Google employee

**Comment by gerardwr** [comment]
Just guessing too.

The voice input file has to be in a non-compressed "raw" format, so an mp3 will not work.

So check the format of your working file, and look at the arecord format here:
https://developers.google.com/assistant/sdk/guides/library/python/embed/audio

**Comment by MKB787** [comment]
Thanks for the responses. I have tried converting my mp3 file to raw format, but this does not trigger a response from the Assistant either. The Assistant does not respond to synthesised speech at all, perhaps.

**Comment by Fleker** [comment]
You definitely should be able to use synthesized speech. In this repo there is a `whattimeisit.riff` while which is used in [tests](https://github.com/googlesamples/assistant-sdk-python/blob/master/google-assistant-sdk/tests/test_endtoend.py#L63).

**Comment by gerardwr** [comment]
I have succesfully used some Alexa soundfiles in Google Assistant from here:
https://github.com/alexa/avs-device-sdk/tree/master/Integration/inputs

I have only tested these, they are recognized by GA perfectly:
```
recognize_weather_test
recognize_whats_up_test
recognize_joke_test
```

**Comment by MKB787** [comment]
ok, thanks. Can any audio file format be used?

**Comment by gerardwr** [comment]
@MKB787 
I believe only raw format is supported.

From https://developers.google.com/assistant/sdk/guides/library/python/embed/audio
 ```
arecord --format=S16_LE --duration=5 --rate=16000 --file-type=raw out.raw
```

**Comment by MKB787** [comment]
Thanks
I have resolved this now by specifying the "sampleRateHertz" as 16000 when synthesizing an audio file using Google Cloud Text-to-Speech. I believe the rate was previously 24000, when this was adjusted the synthesized speech triggered a response from the Assistant.
