### ISSUE TITLE
Google assistant gives random error.

### ISSUE THREAD

**Issue by aasshhiisshh** [googlesamples/assistant-sdk-python#232]
I installed google-assistant in Ubuntu. It was working fine until this error pops up. 

> Press Enter to send a new request...
> INFO:root:Recording audio request.
> INFO:root:End of audio request detected
> INFO:root:Finished playing assistant response.
> Traceback (most recent call last):
>   File "/home/luser/env/bin/googlesamples-assistant-pushtotalk", line 11, in <module>
>     sys.exit(main())
>   File "/home/luser/env/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
>     return self.main(*args, **kwargs)
>   File "/home/luser/env/local/lib/python2.7/site-packages/click/core.py", line 697, in main
>     rv = self.invoke(ctx)
>   File "/home/luser/env/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/home/luser/env/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
>     return callback(*args, **kwargs)
>   File "/home/luser/env/local/lib/python2.7/site-packages/googlesamples/assistant/grpc/pushtotalk.py", line 428, in main
>     continue_conversation = assistant.assist()
>   File "/home/luser/env/local/lib/python2.7/site-packages/tenacity/__init__.py", line 229, in wrapped_f
>     return self.call(f, *args, **kw)
>   File "/home/luser/env/local/lib/python2.7/site-packages/tenacity/__init__.py", line 313, in call
>     start_time=start_time)
>   File "/home/luser/env/local/lib/python2.7/site-packages/tenacity/__init__.py", line 267, in iter
>     return fut.result()
>   File "/home/luser/env/local/lib/python2.7/site-packages/concurrent/futures/_base.py", line 455, in result
>     return self.__get_result()
>   File "/home/luser/env/local/lib/python2.7/site-packages/tenacity/__init__.py", line 316, in call
>     result = fn(*args, **kwargs)
>   File "/home/luser/env/local/lib/python2.7/site-packages/googlesamples/assistant/grpc/pushtotalk.py", line 170, in assist
>     self.conversation_stream.stop_playback()
>   File "/home/luser/env/local/lib/python2.7/site-packages/googlesamples/assistant/grpc/audio_helpers.py", line 288, in stop_playback
>     self._source.stop()
>   File "/home/luser/env/local/lib/python2.7/site-packages/googlesamples/assistant/grpc/audio_helpers.py", line 221, in stop
>     self.flush()
>   File "/home/luser/env/local/lib/python2.7/site-packages/googlesamples/assistant/grpc/audio_helpers.py", line 211, in flush
>     self._audio_stream.write(b'\x00' * self._flush_size)
>   File "/home/luser/env/local/lib/python2.7/site-packages/sounddevice.py", line 1202, in write
>     _check(err)
>   File "/home/luser/env/local/lib/python2.7/site-packages/sounddevice.py", line 2563, in _check
>     raise PortAudioError(errormsg, err)
> sounddevice.PortAudioError: Can't write to an input only stream [PaErrorCode -9974]

**Comment by aasshhiisshh** [comment]
I got my answer. I installed pyaudio newer version.

**Comment by moham96** [comment]
install the assistant from the repo (not from pip ),

**Comment by Fleker** [comment]
Can you try the latest version of the sample? It should make some fixes to the audio I/O.
