### ISSUE TITLE
AttributeError on "hotword.py" while installing Google Assistant

### ISSUE THREAD

**Issue by vikaskarunakaran** [googlesamples/assistant-sdk-python#233]
[googleassistant.log](https://github.com/googlesamples/assistant-sdk-python/files/1915410/googleassistant.log)

Facing attribute error while installing google assistant in Raspberry Pi 3

Attached the full installation log.

**Comment by Fleker** [comment]
It seems like you are using gassist pi. The error itself seems to be happening [on this line of hotword.py](https://github.com/googlesamples/assistant-sdk-python/blob/master/google-assistant-sdk/googlesamples/assistant/library/hotword.py#L124) and [this line of gassist](https://github.com/shivasiddharth/GassistPi/blob/master/scripts/gassist-installer-pi3.sh#L67), although I'm not sure why. Can you also file an issue [on that repository](https://github.com/shivasiddharth/GassistPi/issues) and link to this issue?

```
Traceback (most recent call last):
  File "/home/pi/env/bin/googlesamples-assistant-hotword", line 11, in <module>
    sys.exit(main())
  File "/home/pi/env/lib/python3.5/site-packages/googlesamples/assistant/library/hotword.py", line 128, in main
    Assistant.__version_str__())
```
