### ISSUE TITLE
[Errno 13] Permission denied How i solve this problem

### ISSUE THREAD

**Issue by boomza19193** [googlesamples/assistant-sdk-python#236]
I try to install google assistant on raspberry PI 3 by this code 
`python -m pip install google-assistant-sdk[samples]
` 

and then it is show 
> Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/usr/lib/python2.7/dist-packages/pyasn1/error.py'
Consider using the `--user` option or check the permissions.

thank you.

**Comment by talha020** [comment]
@moham96 thnku also worked in my case.

**Comment by schoolkid** [comment]
@moham96 Thanks a lot!

**Comment by Abhi0496** [comment]
I am using Ubuntu
I am trying to install pandas in anaconda and i was getting same error permission denied

The code i tried is:
  python3 -m venv env
  source ./env/bin/activate 
  python -m pip install pandas


I am getting this error:
 File "<ipython-input-7-9322242e7d32>", line 1
    python3 -m venv env
                  ^
SyntaxError: invalid syntax

**Comment by Fleker** [comment]
Which version of Python are you using?

**Comment by Abhi0496** [comment]
Python 3.6.3

I don't know why it was showing the error then, but I tried once again now and used only-
python3 -m pip install pandas

And it worked, 
Thank you

**Comment by animanoir** [comment]
commenting to save the probable solution

**Comment by horaanchal** [comment]
While installing tensorflow with native pip in ubuntu 16.04 it shows me an error:

Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/usr/local/lib/python3.5/dist-packages/gast'
Consider using the `--user` option or check the permissions.

Anyone can help me solve this problem!
Thanks

**Comment by wichayut** [comment]
try this:

pip install --user tensorflow

**Comment by zramya** [comment]
I am using python 2.7 version

I tried using python2 -m install pandas. But I am getting error telling "command is not recognized as internal or external command"

please help me on this

**Comment by MikeBirdsall** [comment]
use
python2 -m pip install pandas
you left out pip

**Comment by aalfaroiii** [comment]
Thank you moham96 It also helped to solve my problem.

**Comment by adampei** [comment]
perfect you save my day

**Comment by xneal** [comment]
Obrigado Mohamed, só você resolveu meu problema!

Mas agora o meu terminal está assim:

(env) klann@klann-PC:~/Documents$

como retirar esse "env" ?

**Comment by omarjnb** [comment]
Im trying to execute the DirichletForest topic modeling code in bash/Linux which has been published on GitHub http://pages.cs.wisc.edu/~andrzeje/research/df_lda.html

While I'm executing the code in py2.7 Linux, I get this error : 


omar@DESKTOP-0CAAKGI:/mnt/c/Users/omar3/Desktop/sentiment-analysis/coding/arXivLDA/code/LDAlike/DF-LDA-0.1.1$ python setup.py install
running install
running build
running build_py
running build_ext
running install_lib
copying build/lib.linux-x86_64-2.7/ConstraintCompiler.py -> /usr/local/lib/python2.7/dist-packages
**error: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/ConstraintCompiler.py'**
omar@DESKTOP-0CAAKGI:/mnt/c/Users/omar3/Desktop/sentiment-analysis/coding/arXivLDA/code/LDAlike/DF-LDA-0.1.1$



Any help!!
Thanks

**Comment by WV-no7** [comment]
That error is usually because of user permission stuff. Try using "**sudo**" before the command. @omarjnb

**Comment by Rama-Adim** [comment]
On Windows server. Open the command prompt by "Run as Administrator" and try again.

**Comment by sts77** [comment]
I am trying to install face_recognition in jupyter terminal in Anaconda Navigator, using python 2.7
I used the command: 
`pip install face_recognition`
Then it is showing that : 

> Requirement already satisfied: face_recognition in ./anaconda2/lib/python2.7/site-packages

But when I run : 
`import face_recognition`
it is showing that : 

> ImportError: No module named face_recognition

Then I checked the Face Recognition Installation [Documentation:](https://face-recognition.readthedocs.io/en/latest/readme.html#installation)

From there I got the command `pip2 install face_recognition`
when i tried that I got the error: 

sooraj:~$ pip2 install face_recognition
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/__init__.py:83: RequestsDependencyWarning: Old version of cryptography ([1, 2, 3]) may cause slowdown.
  warnings.warn(warning, RequestsDependencyWarning)
Collecting face_recognition
  Using cached https://files.pythonhosted.org/packages/3f/ed/ad9a28042f373d4633fc8b49109b623597d6f193d3bbbef7780a5ee8eef2/face_recognition-1.2.3-py2.py3-none-any.whl
Requirement already satisfied: Pillow in /usr/lib/python2.7/dist-packages (from face_recognition) (3.1.2)
Collecting dlib>=19.7 (from face_recognition)
Requirement already satisfied: numpy in /usr/local/lib/python2.7/dist-packages (from face_recognition) (1.14.5)
Collecting face-recognition-models>=0.3.0 (from face_recognition)Collecting Click>=6.0 (from face_recognition)
  Using cached https://files.pythonhosted.org/packages/34/c1/8806f99713ddb993c5366c362b2f908f18269f8d792aff1abfd700775a77/click-6.7-py2.py3-none-any.whl
Installing collected packages: dlib, face-recognition-models, Click, face-recognition
Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/dlib.so'
Consider using the `--user` option or check the permissions.

How to overcome this error?

**Comment by ampaire** [comment]
Thanks it works

**Comment by PatelTixa15** [comment]
Could not install packages due to an EnvironmentError: [Errno 28] No space left on device: '/home/priyanka/.local/lib'

answer this error?

**Comment by Fleker** [comment]
@PatelTixa15 you need to look at your storage size. There seems to be too many files, and there's no room left for what you're trying to install.

**Comment by PatelTixa15** [comment]
okay 
but how to transfer all data from one disk to another in ubuntu. like from home directory to any other directory .bcaz all data save by default in home directory.

**Comment by Fleker** [comment]
There's probably some files on your system that you can move over, like in your home directory. You can use a terminal or a file explorer app. If you have further questions, please make a new issue.

**Comment by Ishaan28malik** [comment]
Thanks alot it worked for me as well @boomza19193

**Comment by AbuAhmedsd** [comment]
@moham96 thanks very match for you. also worked in my case by using the third option.

**Comment by DunkeeFunk** [comment]
I had a virtual environment set up with virtualenv on my Raspberry Pi, i tired to install the packages I needed and got the same permission denied error, im using venv now and it works ... thanks

**Comment by deepu2010** [comment]
I solved this issue by typing the following command,

    pip install --user <package_name>

Example,

    pip install --user tensorflow

NOTE: You should not enter your own username for this command. Please enter with '--user'.

**Comment by NoneYEL** [comment]
> 
> 
> You are trying to install the package to a system folder which you don't have permissions to write to.
> You have three options(use only one of them):
> 1-setup a virtual env to install the package **(recommended)**:
> 
> ```
> python3 -m venv env
> source ./env/bin/activate 
> python -m pip install google-assistant-sdk[samples]
> ```
> 
> 2-Install the package to the user folder:
> ` python -m pip install --user google-assistant-sdk[samples]`
> 
> 3-use sudo to install to the system folder **(not recommended)**
> `sudo python -m pip install google-assistant-sdk[samples]`

>4-try this:
  su root
  pip install SomePackage

**Comment by jd-vandenbor** [comment]
Honestly before trying any of these solutions try closing the terminal, reopening it and entering in the same command. Especially if you just left a virtual environment. Sometimes this fixes things for me.

**Comment by lydia-gu** [comment]
@moham96 Solution works in CentOS
Thank you!

**Comment by jiseongg** [comment]
One of my friends got this same problem in my virtual environment.
His virtualenv directory is in C:\pyvenv, and python interpreter is in C;\Python\Python36.
I don't know how to fix it.

**Comment by EvanLavizadeh** [comment]
> You are trying to install the package to a system folder which you don't have permissions to write to.
> You have three options(use only one of them):
> 1-setup a virtual env to install the package **(recommended)**:
> 
> ```
> python3 -m venv env
> source ./env/bin/activate 
> python -m pip install google-assistant-sdk[samples]
> ```
> 2-Install the package to the user folder:
> ` python -m pip install --user google-assistant-sdk[samples]`
> 
> 3-use sudo to install to the system folder **(not recommended)**
> `sudo python -m pip install google-assistant-sdk[samples]`

Why is using sudo not recommended?

**Comment by Castern** [comment]
Thank You so much.
I tried to do a 
`pip install pysolr`  on the edge node of the Hadoop cluster which resulted in
`Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/usr/lib/python2.7/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/usr/lib/python2.7/site-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/lib/python2.7/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/usr/lib/python2.7/site-packages/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/usr/lib/python2.7/site-packages/pip/wheel.py", line 323, in clobber
    shutil.copyfile(srcfile, destfile)
  File "/usr/lib64/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 13] Permission denied: '/usr/lib/python2.7/site-packages/pysolr.py'`

Tried the above. Works well!

**Comment by moham96** [comment]
> > You are trying to install the package to a system folder which you don't have permissions to write to.
> > You have three options(use only one of them):
> > 1-setup a virtual env to install the package **(recommended)**:
> > ```
> > python3 -m venv env
> > source ./env/bin/activate 
> > python -m pip install google-assistant-sdk[samples]
> > ```
> > 2-Install the package to the user folder:
> > ` python -m pip install --user google-assistant-sdk[samples]`
> > 3-use sudo to install to the system folder **(not recommended)**
> > `sudo python -m pip install google-assistant-sdk[samples]`
> 
> Why is using sudo not recommended?

It's actually just my opinion, on Gnu/linux environment I like to install python packages in an organized fashion like so 
1- System directories like `/usr/lib/python2.7/site-packages` will be managed by my system's package manager (i.e when installing a python package from your system's package manager like `sudo apt-get install python-flask`).

2- use `pip` only to install to user directories or a virtual environment so in case you mess up something beyond repair you can just delete the in the home directory or delete the virtual environment.

This is just my personal preference, there is no reason you can't install to system directories.

Regards

**Comment by EvanLavizadeh** [comment]
@moham96 
I read more about it and I think the reason is that it is unsafe to give the developer root permissions. After all, setup.py is just a python file and it can contain anything. Any developer can deploy malicious software very easily this way.

**Comment by TheRoger** [comment]
great.

**Comment by jisnava** [comment]
Thank You soo much....this worked in my case also

**Comment by lucidsushi** [comment]
How do you check upfront if your `pip` has permission to install to systems directory? Because sometimes it does work :scream:

**Comment by LuisManuelLuis** [comment]
Hi .. How are you? I have some issues when install the tensorflow on the ubuntu..
```
ERROR: Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/usr/local/lib/python3.6/dist-packages/numpy-1.16.4.dist-info'
Consider using the `--user` option or check the permissions.
```
So I tried with `sudo pip install --ignore-installed --upgrade tensorflow==1.9`

But there are some warning.
And then I test tensorflow follow this:
`python`
`import tensorflow as tf`
This doesn't work and show the issues follow this:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named tensorflow
```

How can I fix this? thanks for your help.

**Comment by WV-no7** [comment]
Use "***pip install --user tensorflow*** ". Not just Tensorflow while installing any package use --user. 

Thank you :)

**Comment by PraiseSunAsh** [comment]
@moham96 Thank u !!!!!!

**Comment by carolynenewman** [comment]
@moham96  Thank you so much, this worked perfectly. Once I get the package installed, do I need to access this "env" I just created every time I need to use what I just installed?

**Comment by lucidsushi** [comment]
@carolynenewman you can have multiple virtual environments, so you have to figure out which one is active, or you want to activate, the virtual env is deactivated when the terminal it starts in is terminated

**Comment by anudeepar06** [comment]
fgzfg

**Comment by marcofdz** [comment]
Thank you so much, this worked perfectly

**Comment by Huy-Ngo** [comment]
> You are trying to install the package to a system folder which you don't have permissions to write to.
> You have three options(use only one of them):
> 1-setup a virtual env to install the package **(recommended)**:
> 
> ```
> python3 -m venv env
> source ./env/bin/activate 
> python -m pip install google-assistant-sdk[samples]
> ```
> 
> 2-Install the package to the user folder:
> ` python -m pip install --user google-assistant-sdk[samples]`
> 
> 3-use sudo to install to the system folder **(not recommended)**
> `sudo python -m pip install google-assistant-sdk[samples]`

I'm trying to set up Django. I tried both three ways:

1:  Somehow I can't set up the environment at all with that command
2: I did that, but it just respond with "check permission" instead
3: I'm on Windows, so I can't use sudo

I also run the command prompt as admin, so I thought it was supposed to be working, but it did not.
Anyone else have the same problem?

**Comment by mrparadox404** [comment]
it works thanks

**Comment by mohit-a-different-approach** [comment]
your command will run but before that you need to create and activate the virtual environment
thats it

**Comment by Samobey** [comment]
just put --user after "install" 
so:  
 pip install --user whatEverYouWant

**Comment by Knrd2** [comment]
For me its still not working. Im getting the following error message when running my bot: message: session not created: Chrome version must be between 71 and 75
(Driver info: chromedriver=2.46.628411 (3324f4c8be9ff2f70a05a30ebc72ffb013e1a71e),platform=Mac OS X 10.14.5 x86_64)
Then i wanted to update: 
python -m pip install instapy -U
Getting the error: 
ERROR: Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/fake_useragent'
Consider using the `--user` option or check the permissions.
This is still not helping: pip install --user tensorflow

Google Chrome is up to date
Version 76.0.3809.100

**Comment by geniusunil** [comment]
still not working for me

**Comment by AlexWayfer** [comment]
```
> source ./env/bin/activate                                                                                                                           29 Aug 16:16:04 
./env/bin/activate (line 74): Missing end to balance this if statement
if [ -n "${BASH:-}" -o -n "${ZSH_VERSION:-}" ] ; then
^
from sourcing file ./env/bin/activate
	called on standard input

source: Error while reading file “./env/bin/activate”
```

Doesn't work for [fish shell](https://fishshell.com/).

**Comment by happar73** [comment]
@moham96 It works, you save our time, thanks so much!

**Comment by yts61** [comment]
thank you you made my day

**Comment by 123-emir** [comment]
Thank You So Much

**Comment by aleej123** [comment]
Hello everyone need  some help I have installed python 3.5 and want to install h5py package and I am getting an error :(

Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/usr/local/lib/python3.5/dist-packages/h5py'
Consider using the `--user` option or check the permissions.

**Comment by MUsman27665** [comment]
3rd option worked for me thanks your not recommended one...

**Comment by thinksanky** [comment]
Thanks! it worked

**Comment by emlanis** [comment]
> just put --user after "install"
> so:
> pip install --user whatEverYouWant

it works.. successfully.. thanks

**Comment by smanohar76** [comment]
I am running python3.7 on a CENTOS VM.  In order to install request library the below command worked for me
python3.7 -m pip install --user requests

**Comment by smanohar76** [comment]
> > just put --user after "install"
> > so:
> > pip install --user whatEverYouWant
> 
> it works.. successfully.. thanks

That worked

**Comment by sameerapriya** [comment]
> ```
> > source ./env/bin/activate
> ./env/bin/activate (line 74): Missing end to balance this if statement
> if [ -n "${BASH:-}" -o -n "${ZSH_VERSION:-}" ] ; then
> ^
> from sourcing file ./env/bin/activate
> 	called on standard input
> 
> source: Error while reading file “./env/bin/activate”
> ```
> 
> Doesn't work for [fish shell](https://fishshell.com/).

try using activate.fish at the end

**Comment by anubhvshrma18** [comment]
i am also getting the same error with python 3.8
usr/bin/env  - Permission denied 
any solution?

**Comment by sameerapriya** [comment]
> i am also getting the same error with python 3.8
> usr/bin/env - Permission denied
> any solution?


Could be a path error as well 
check your path and the packages installed

**Comment by areebsyed** [comment]
> You are trying to install the package to a system folder which you don't have permissions to write to.
> You have three options(use only one of them):
> 1-setup a virtual env to install the package **(recommended)**:
> 
> ```
> python3 -m venv env
> source ./env/bin/activate 
> python -m pip install google-assistant-sdk[samples]
> ```
> 
> 2-Install the package to the user folder:
> ` python -m pip install --user google-assistant-sdk[samples]`
> 
> 3-use sudo to install to the system folder **(not recommended)**
> `sudo python -m pip install google-assistant-sdk[samples]`

Why is sudo option not recommended?

**Comment by talk2ajay** [comment]
moham96 - thank you savior

**Comment by tklander95** [comment]
Hi i need some help here. Doing machine learning but I am facing OSError.

OSError: Unable to create file (unable to open file: name = 'cnnh5', errno = 13, error message = 'Permission denied', flags = 13, o_flags = 302)

**Comment by NageshRu** [comment]
Go to the super user/root then install packages.
sudo su
pip3 install .....

**Comment by Tejas2909** [comment]
i have a doubt that when i convert my .py to .exe file in virtual environment then where should we place our pytho file inside the virtual environment

**Comment by BuddyBob** [comment]
Who's a legend... you are!

**Comment by MareksNo** [comment]
> You are trying to install the package to a system folder which you don't have permissions to write to.
> You have three options(use only one of them):
> 1-setup a virtual env to install the package **(recommended)**:
> 
> ```
> python3 -m venv env
> source ./env/bin/activate 
> python -m pip install google-assistant-sdk[samples]
> ```
> 
> 2-Install the package to the user folder:
> ` python -m pip install --user google-assistant-sdk[samples]`
> 
> 3-use sudo to install to the system folder **(not recommended)**
> `sudo python -m pip install google-assistant-sdk[samples]`

I know it has been 2 years, but is it possible for me to use the first option if I already have the venv activated?

**Comment by ShahbazU** [comment]
Hi i need some help here.Installing librosa package and getting this error.
ERROR: Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: 'C:\\Python38\\Lib\\site-packages\\__pycache__\\soundfile.cpython-38.pyc'

**Comment by bitman333** [comment]
> You are trying to install the package to a system folder which you don't have permissions to write to.
> You have three options(use only one of them):
> 1-setup a virtual env to install the package **(recommended)**:
> 
> ```
> python3 -m venv env
> source ./env/bin/activate 
> python -m pip install google-assistant-sdk[samples]
> ```
> 
> 2-Install the package to the user folder:
> ` python -m pip install --user google-assistant-sdk[samples]`
> 
> 3-use sudo to install to the system folder **(not recommended)**
> `sudo python -m pip install google-assistant-sdk[samples]`

Number 1 worked for me. Thanks.

**Comment by sobabear** [comment]
thank you it works a lot

**Comment by sunith-kumar** [comment]
ERROR: Can not perform a '--user' install. User site-packages are not visible in this virtualenv.

**Comment by Soorya-111** [comment]
> I am running python3.7 on a CENTOS VM. In order to install request library the below command worked for me python3.7 -m pip install --user requests

it worked for me

**Comment by zeeshan52123** [comment]
Error: [Errno 13] Permission denied: 'C:\\UMS-API\\myenv\\Scripts\\python.exe' generate this error how to resolve
