### ISSUE TITLE
SDK service only returns the last message as supplemental display text on a multi message response

### ISSUE THREAD

**Issue by dataoracle** [googlesamples/assistant-sdk-python#239]
The case appears when asking questions that involve multiple messages. For example `tell me a joke` usually returns two messages, the last one is normally the punchline along some nice emoji.

The audio in `DialogStateOut ` comes proper with the full joke. However the `supplemental_display_text` only contains the punchline.

Similar case is `tell me a riddle`, that does not populate the `supplemental_display_text` at all.

**Comment by Fleker** [comment]
Yes, thanks for reporting this issue. It is a duplicate, so I'll close this one specifically.
