### ISSUE TITLE
Directly pass audio file as user input command?

### ISSUE THREAD

**Issue by lohriialo** [googlesamples/assistant-sdk-python#243]
My user input is always constant, meaning same user command all the time, so instead of asking the user to everytime record a voice command via a device microphone, I want to have the user press a button and execute the command by passing a pre-recorded audio file as input. Is that possible with the Google assistant SDK? And can I parse the result as json or string?

**Comment by Fleker** [comment]
It is possible, and it's something that is shown in the [`pushtotalk`](https://github.com/googlesamples/assistant-sdk-python/blob/master/google-assistant-sdk/googlesamples/assistant/grpc/pushtotalk.py#L245) sample.

**Comment by lohriialo** [comment]
Thanks much for the pointers, I'm trying out the pushtotalk sample now but it's not talking my `.mp3` or `.wav` file 

**Command:**
`googlesamples-assistant-pushtotalk --device-model-id 'my-device-model' --device-id 'my-device-identifier' -i whats-this-song.mp3`

**Error is:** 
`INFO:root:Connecting to embeddedassistant.googleapis.com`
`WARNING:root:error opening WAV file: file does not start with RIFF id, falling back to RAW format`
`INFO:root:Recording audio request.`
`INFO:root:End of audio request detected`
`INFO:root:Finished playing assistant response.`

Where can I find what audio format it wants?

**Comment by Fleker** [comment]
Can you try some of the [test audio files](https://github.com/googlesamples/assistant-sdk-python/tree/master/google-assistant-sdk/tests/data) in the repo and see if it's an audio encoding issue?

**Comment by lohriialo** [comment]
Thanks for your help!
