### ISSUE TITLE
Error message with the command: python hotword.py --device_model_id my model

### ISSUE THREAD

**Issue by thymosi** [googlesamples/assistant-sdk-python#245]
When I enter with the command:

(env) pi@raspberrypi:~/assistant-sdk-python/google-assistant-sdk/googlesamples/assistant/library $ python hotword.py --device_model_id my model

I get:

Traceback (most recent call last):
  File "hotword.py", line 156, in <module
    main()
  File "hotword.py", line 134, in main
    Assistant._version_str_())
AttributeError: type object 'Assistant' has no attribute '_version_str_'

I'm using Python 3.5.3 Shell. 
Can someone help me?

**Comment by Fleker** [comment]
Can you run `pip freeze` and state which version of the SDK and which version of the library are installed?

**Comment by Fleker** [comment]
We have since released [a few new versions](https://github.com/googlesamples/assistant-sdk-python/releases) of each. It may be useful to upgrade your pip dependencies.

**Comment by thymosi** [comment]
Wow!!! You were right!

I made some updates as you suggested and everything is working.
Thanks a lot for the help.
