### ISSUE TITLE
How to create devices programmatically?

### ISSUE THREAD

**Issue by dmarvp** [googlesamples/assistant-sdk-python#247]
I understand that the assistant service includes ways to do this: https://developers.google.com/assistant/sdk/reference/rpc/google.assistant.devices.v1alpha2

However, I don't think the bindings for that are part of this package? Are there plans to include that? And if not, could you please point me in the right direction to do it?

**Comment by Fleker** [comment]
We do include the `googlesamples-assistant-devicetool` tool which wraps around some of the API calls, but we do not include anything beyond that.

**Comment by dmarvp** [comment]
Hey @Fleker, thanks. I think we contacted also on the google assistant developers SDK google+ group. I would appreciate it if the protobufs could be shared so that I can create my own python client for it. Or if you could tell me if there is any other simple way to reach that service by code. Thanks a lot!

**Comment by proppy** [comment]
@dmarvp did you take a look at the device registration tool?

It could also serve as an example on how to build a simple REST client for device registration:
https://github.com/googlesamples/assistant-sdk-python/blob/master/google-assistant-sdk/googlesamples/assistant/grpc/devicetool.py

**Comment by dmarvp** [comment]
thanks @proppy, I'm closing the issue as that example has everything I needed.
