### ISSUE TITLE
Register model bug

### ISSUE THREAD

**Issue by Silvermax00** [googlesamples/assistant-sdk-python#248]
Hi ! So, I try to install google assistant and then when i must register a model with this command : 
googlesamples-assistant-devicetool register-model -manufacturer "Assistant SDK developer" -product-name "Assistant SDK light" -type LIGHT -model
It said : "Error: Missing option "--project-id"." Somebody can help me ?
Thanks

**Comment by Fleker** [comment]
`googlesamples-assistant-devicetool --project-id your-google-cloud-project-id register-model ...` is the correct syntax.
