### ISSUE TITLE
ALSA lib ../../../alsa-lib-1.1.0/src/pcm/pcm_dmix.c:1029:(snd_pcm_dmix_open) unable to open slave

### ISSUE THREAD

**Issue by captainpanther** [googlesamples/assistant-sdk-python#249]
OS: NXP in yocto(arm embedded)

ON_RECOGNIZING_SPEECH_FINISHED:
  {u'text': u'who are you'}
ALSA lib ../../../alsa-lib-1.1.0/src/pcm/pcm_dmix.c:1029:(snd_pcm_dmix_open) unable to open slave
[ERROR:audio_output_stream.cc(61)] Device could not be opened: default
ON_RESPONDING_STARTED:
  {u'is_error_response': False}
[3950:3981:ERROR:audio_output_stream.cc(121)] An error occurred when playing audio output
ON_RESPONDING_FINISHED
ON_RESPONDING_STARTED:
  {u'is_error_response': True}
ALSA lib ../../../alsa-lib-1.1.0/src/pcm/pcm_dmix.c:1029:(snd_pcm_dmix_open) unable to open slave
[ERROR:audio_output_stream.cc(61)] Device could not be opened: default
[3950:3981:ERROR:audio_output_stream.cc(121)] An error occurred when playing audio output
ON_RESPONDING_FINISHED
ON_CONVERSATION_TURN_FINISHED:
  {u'with_follow_on_turn': False}

who can solve it?

**Comment by Fleker** [comment]
Are you still seeing this issue?

**Comment by captainpanther** [comment]
I have been solved it,thank
Nick <notifications@github.com> 於 2018年9月16日 週日 上午6:33 寫道：
