### ISSUE TITLE
send_text_query() is missing from assistant library

### ISSUE THREAD

**Issue by JamesTowner** [googlesamples/assistant-sdk-python#252]
Hi,

On AIY assistant SDK page, Google mentioned an API send_test_query(). 

**send_text_query(query)**
Sends |query| to the Assistant as if it were spoken by the user.
This will behave the same as a user speaking the hotword and making a query OR speaking the answer to a follow-on query.

But i cannot find it on my rPi3 AIY voice installation. I installed SW by following the booklet came in the package. All demo programs worked fine. But i cannot find that API when i try to use it. Some output from my installation are as the following.

**pi@raspberrypi:~$ pip list |grep google**
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
google-api-core (0.1.4)
google-assistant-grpc (0.1.0)
google-assistant-library (0.1.0)
google-assistant-sdk (0.4.2)
google-auth (1.4.1)
google-auth-oauthlib (0.2.0)
google-cloud-core (0.28.1)
google-cloud-speech (0.30.0)
google-gax (0.15.16)
googleapis-common-protos (1.5.3)
You are using pip version 9.0.2, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**pi@raspberrypi:~$ pip show google-assistant-library**
Name: google-assistant-library
Version: 0.1.0
Summary: Google Assistant Library Python wrapper
Home-page: https://developers.google.com/ assistant/sdk
Author: Google Assistant SDK Team
Author-email: jordanjtw+assistant-library@ google.com
License: Other/Proprietary License
Location: /usr/local/lib/python3.5/dist- packages
Requires: enum34, argparse, google-auth, requests
You are using pip version 9.0.2, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**pi@raspberrypi:~$ grep "    def " /usr/local/lib/python3.5/dist- packages/google/assistant/** library/assistant.py
    def __init__(self, credentials, device_model_id):
    def __enter__(self):
    def __exit__(self, exception_type, exception_value, traceback):
    def __call__(self, event_type, event_data):
    def start(self):
    def set_mic_mute(self, is_muted):
    def start_conversation(self):
    def stop_conversation(self):
    def device_id(self):
    def version(self):
    def _set_credentials(self, credentials):
    def _load_lib(self):

**pi@raspberrypi:~$ ls -l /usr/local/lib/python3.5/dist- packages/google/assistant/ library/**
total 11444
-rw-r--r-- 1 root staff    10742 Apr 13 21:18 assistant.py
-rw-r--r-- 1 root staff     2659 Apr 13 21:18 auth_helpers.py
-rw-r--r-- 1 root staff     6857 Apr 13 21:18 event.py
-rw-r--r-- 1 root staff      952 Apr 13 21:18 file_helpers.py
-rw-r--r-- 1 root staff      762 Apr 13 21:18 __init__.py
-rw-r--r-- 1 root staff 11500644 Apr 13 21:18 libassistant_embedder.so
-rw-r--r-- 1 root staff   157282 Apr 13 21:18 LICENSE.third_party
-rw-r--r-- 1 root staff     5300 Apr 13 21:18 __main__.py
drwxr-sr-x 2 root staff     4096 Apr 13 21:18 __pycache__

**pi@raspberrypi:~$ grep send_text_query /usr/local/lib/python3.5/dist- packages/google/assistant/ library/***
grep: /usr/local/lib/python3.5/dist- packages/google/assistant/ library/__pycache__: Is a directory

Any idea on what is missing on my installation? 

Thanks in advance,
James

**Comment by Fleker** [comment]
Your version of the SDK is pretty old. You can check out the [releases page](https://github.com/googlesamples/assistant-sdk-python/releases) for all of the latest versions of the SDK and library.

Can you point to the documentation that AIY has for sending text queries?

**Comment by JamesTowner** [comment]
Here is the link for the doc.
[google.assistant.library package.](https://developers.google.com/assistant/sdk/reference/library/python/)

I will try the latest SDK.

Thanks.
