### ISSUE TITLE
Remote casting not working

### ISSUE THREAD

**Issue by BillyTheGit** [googlesamples/assistant-sdk-python#254]
I have an Google AIY Voice kit running with the latest Assistant sdk, but remote casting to Chromecasts is not working. I get an answer that this is not possible or it doesn't know how to help with that yet. For example I tried casting with Google Play Music and Youtube.

I am able to turn on and off the television (through the Chromecast) or pause or stop playing a song or video, also playing next song/video works.
Once it said I had to repeat myself but with the song I wanted to hear, but that also didn't work.

I also noticed broadcasting (from my phone to Google AIY Voice kit) is not working, but I've read somewhere that this is a known problem, so maybe this is related?

Im running the assistant_library_demo.py from src/examples/voice/

**Comment by Fleker** [comment]
If you run `pip freeze`, which version of the google-assistant-library do you have?

**Comment by BillyTheGit** [comment]
My bad, not the latest version I guess, but I can't update because of this problem mentioned here:
https://github.com/google/aiyprojects-raspbian/issues/378

Will close this issue since Im not up to date.
