### ISSUE TITLE
Unable to Re-Register RPi Model --> "Error: Missing option "--project-id"

### ISSUE THREAD

**Issue by JackJack99** [googlesamples/assistant-sdk-python#255]
Hi, 
I'm currently working on a Google Assistant project and have updated the supported traits of my device model (I added OnOff to try to use voice commands to turn an LED on and off). However, my Assistant says that "power controls is not yet supported". 

From a bit of looking around I figure that this is because I am still using the older device instance ID from before I turned OnOff on in Actions. I have tried to re-register the device with the following:
`googlesamples-assistant-devicetool register-device --project-id "MY PROJECT ID" --model "MY MODEL ID" --client-type "SERVICE"`
but the following message is printed:
`Error: Missing option "--project-id".`

I don't understand why I would be getting this error when I specifically use the project ID option.

Does anyone have an idea why this might be happening? Please keep in mind that I am very new at this so simple answers would be _greatly_ appreciated.

Thanks,

Jack

**Comment by proppy** [comment]
`--project-id PROJECT_ID` needs to be before `register-device`

**Comment by JackJack99** [comment]
@proppy Thanks! I knew it'd be something obvious...

**Comment by proppy** [comment]
No worries! Glad it was easy to figure out.
