### ISSUE TITLE
How to change 'Turn LED on' word to Something 

### ISSUE THREAD

**Issue by salmanfarisvp** [googlesamples/assistant-sdk-python#258]
Hi, i would like to control (Turn on/off) GPIO , and the example from here :- https://developers.google.com/assistant/sdk/guides/library/python/extend/handle-device-commands worked perfectly , i would like to on/off the GPIO using a custome Word .
Thanks

**Comment by Fleker** [comment]
Then you will want to set up [custom device actions](https://developers.google.com/assistant/sdk/guides/library/python/extend/custom-actions)

**Comment by salmanfarisvp** [comment]
Thanks @Fleker  i'll check that .
