### ISSUE TITLE
the Italian language has disappeared from the hotword

### ISSUE THREAD

**Issue by aandroide** [googlesamples/assistant-sdk-python#259]
Hello, since the beginning of the month, I and other users, we found that the app assistant, you can no longer set the Italian language for hotword.
Can we kindly know the reason? since the google home and google home mini have also arrived in our country !!
Thanks to those who will give us a plausible explanation

**Comment by aandroide** [comment]
![cattura](https://user-images.githubusercontent.com/14141574/41620693-cfb36da6-740a-11e8-8ebe-57a60d5a11d6.PNG)

please give an explanation of why using sdk library we do not have the Italian language?
Until the end of May it worked now no longer appears in the app assistant

**Comment by S1m0n3** [comment]
Encountered the same problem but seems that using pushtotalk example code italian language appears...

**Comment by aandroide** [comment]
@S1m0n3 

we do not confuse the 2 bookstores !!! pushtotalk, uses Google Assistant Service and Italian is also present.
While hotword uses the Google Assistant Library that from 8 March to 30/05/2018 also worked in Italian and now no longer and we do not know yet the reason after almost a month from the report.

**Comment by S1m0n3** [comment]
@aandroide Yes, I know! But how you saying both support the Italian language from documentation of Google, so just want to know the reason because the Italian language disappears only when we using  Google Assistant Library! ;)

**Comment by Enzoinventor** [comment]
@proppy @S1m0n3 @aandroide @Fleker 
sorry but is not that by chance google has made an agreement with amazon alexa? because look at the case in early June alexa also speaks in Italian and google assistant sdk instead no.

**Comment by JordanJTW** [comment]
I am really sorry to hear you've been having trouble with the Google Assistant Library and just wanted to follow up and let you know that this has been brought to my attention and we are actively investigating the regression. I hope we can get this resolved quickly, thank you for your patience!

**Comment by aandroide** [comment]
@JordanJTW 
Ok today I noticed the new update from the google app playstore, but the Italian language does not appear yet. moreover, even the voice match to set the word ok google on the phone no longer works

**Comment by aandroide** [comment]
@JordanJTW  it would seem that the problem manifests itself in Android devices. on iOS, other users have confirmed to me that they display the Italian language.
so at this point, if so, who should we ask? I will have sent a thousand feedback from the app assistant but I have never received an answer

**Comment by aandroide** [comment]
I confirm that on ios it works, I tried today. so I guess it's not your problem but the google app developer on the android playstore

**Comment by aandroide** [comment]
@JordanJTW 
hello today the problem has not yet been solved on android devices.
how much longer do we have to wait?

**Comment by aandroide** [comment]
solved
