### ISSUE TITLE
How works "plays news" functionality.

### ISSUE THREAD

**Issue by Smanar** [googlesamples/assistant-sdk-python#260]
Hi, according to https://developers.google.com/assistant/sdk/release-notes, the library have now support for playing news and podcasts.
But every time I try, I have as answer  "unfortunately I still can not read the news on this device", and setting seem good on google assistant app.

I m trying in other language than english.

BTW, I have too problem with reminders (or event), I can set them (and see them in google calendar) but they are never trigger by assistant.

**Comment by Smanar** [comment]
I have tried with english (US)
"Tell me the news" >  "unfortunately I still can not read the news on this device"
"plays BBC Minute" > "news not supported on this device yet"
"How's my day" > "blablablabla" and "Sorry I can't find updated news"
with

> ON_RENDER_RESPONSE:
> {
>   "text": "How to play rising interest rates based on your age\n---\n( CNBC.com - https://www.cnbc.com/amp/2018/06/18/how-to-play-rising-interest-rates-based-on-your-age.html )\n---\nTrump’s Play to Base May Backfire in Midterms\n---\n( Bloomberg - https://www.bloomberg.com/amp/news/articles/2018-06-18/trump-s-play-to-base-may-backfire-in-midterms )\n---\nReviewing Fairview, a Play That Almost Demands That I Not Do So\n---\n( Vulture - http://amp.vulture.com/2018/06/reviewing-fairview-a-play-that-almost-d.....................st.com/story/us-open-2018-brooks-koepka-shows-hes-more-than-a-bash-bro-can-play-us-open-style-golf/amp )\n---\nMexico play for the love of winning to seal one of their greatest victories\n---\n( The Guardian - https://amp.theguardian.com/football/2018/jun/17/mexico-germany-world-cup-2018-juan-carlos-osorio )",
>   "type": 0
> }
> 

But nothing (on news, the rest is ok) in french at "how is my day"

It don't work on all localisations ?

**Comment by Fleker** [comment]
It should work on all locales, and it is pretty unusual that it doesn't work on English. What version of the library are you using?

**Comment by Smanar** [comment]
> google-assistant-library==1.0.0

And IDK if the render_response (missing in french) is correct, it's a mix url/comment, how the assistant can read that as it ?

And just to be sure, I have checked, I m sure have use "--client-type LIBRARY" for registration.

**Comment by Smanar** [comment]
I m the only one with this bug ^^ ?
Someone know here is the code for news ?
It's client based or server based ?

**Comment by JordanJTW** [comment]
Can you please make sure you have libmpg123.so on your device?

$ sudo apt install libmpg123-dev

**Comment by Smanar** [comment]
Yeah ^^, thx, my bad, it s written on the documentation, idk why I have missed this lib.
News test to do now.

**Comment by mpember** [comment]
When I execute
`google-assistant-demo --device-model-id 'MY-DEVICE-ID' --credentials ~/.config/google-oauthlib-tool/credentials.json`

I get the following:
```
ON_MUTED_CHANGED:
  {"is_muted": false}
ON_MEDIA_STATE_IDLE
ON_START_FINISHED

ON_CONVERSATION_TURN_STARTED
ON_END_OF_UTTERANCE
ON_RECOGNIZING_SPEECH_FINISHED:
  {"text": "play the news"}
Aborted
```

If I uninstall libmpg123-dev, I get the _"Sorry news playback isn't supported on this device yet"_ audio response.  Is there any way of finding out what is causing the demo to abort?

**Comment by DewGew** [comment]
I have the same issue..
