### ISSUE TITLE
Dialogflow fulfilment

### ISSUE THREAD

**Issue by NicolasLifetouch** [googlesamples/assistant-sdk-python#262]
Someone knows how it's possible to start a conversation in dialogflow from a custom google assistant action write in json? There is the parameter "conversation" in the google documentation of the json structure but without any example i don't know how to insert it in the json and how to do the dialogflow part.

**Comment by Fleker** [comment]
You would need to create a custom device action that, when activated, uses something like the [Dialogflow Python client](https://github.com/dialogflow/dialogflow-python-client-v2) to send a request to an agent.

**Comment by NicolasLifetouch** [comment]
Thank you for the answer, do you have any example or something like that? It would help a lot.

**Comment by Fleker** [comment]
The sample I link to is for implementing a Dialogflow client.

**Comment by NicolasLifetouch** [comment]
Ok i did the client configuration and i can send the request to the agent, there is a way to get the response of the agent as a audio autput of the google assistant? Now i get only text output. Thanks!

**Comment by matthewayne** [comment]
Currently text is the only supported response.  You can use Google's Cloud text to speech API beta or similar API to take the text/SSML returned by Dialogflow and turn it into audio: https://cloud.google.com/text-to-speech/docs/

**Comment by NicolasLifetouch** [comment]
Thank you, I'll do it!
