### ISSUE TITLE
Where do I find the modelid for my raspberry pi? I cannot find the register devices tab in the Actions Console, any help?

### ISSUE THREAD

**Issue by TheEndernaut** [googlesamples/assistant-sdk-python#265]

**Comment by Fleker** [comment]
On [this page of the documentation](https://developers.google.com/assistant/sdk/guides/service/python/embed/config-dev-project-and-account), you must find the Device Registration card on the bottom of the categories page.

![Device Registration](https://developers.google.com/assistant/sdk/images/console/device-registration-card.png)
