### ISSUE TITLE
Can the google home speak first on a button press?

### ISSUE THREAD

**Issue by sharkwheels** [googlesamples/assistant-sdk-python#266]
Really more of a question than an issue. Is there a way to have the google home respond first with a button press or a tirgger on a raspberry pi? 

For example, instead of pressing a button then asking "what's the weather", you button and it starts the conversation with something like "Hey, what can I help you with?"

I'm currently looking through the documentation, but if anyone has some links or thoughts, that would be great. 

Thanks!

**Comment by Fleker** [comment]
A feature of the SDK is that your embedded Google Assistant can wake up on any trigger that you want. However, it is not able to wake up a Google Home, and the Google Home does not have any button to wake it up.

**Comment by sharkwheels** [comment]
Sorry. I think maybe I wasn't clear? I have an embedded google assistant ON a raspberry pi, and I know you can rig a button to wake it up, what I want to know is if you can wake it up and have the google assistant respond first rather than waking it up and then having to prompt it with a question to get a response.

**Comment by sharkwheels** [comment]
Hm. that might work. I need a way to trigger the start of a custom flow / program without a user voice prompt. I guess I could run an audio clip to prompt the user to start the program but I really wish this functionality just existed in the SDK, autonomously starting its a behaviour I get asked about implementing a lot. Anyways, thanks!
