### ISSUE TITLE
error: `Illegal instruction`

### ISSUE THREAD

**Issue by tiancaipipi110** [googlesamples/assistant-sdk-python#267]
After running 
`googlesamples-assistant-hotword --project_id my-dev-project --device_model_id my-model`
I got an error: `Illegal instruction`
I followed the guide at https://developers.google.com/assistant/sdk/overview
And the previous steps were all good.

**Comment by Fleker** [comment]
As stated in the guide:

> The library is written in Python and is supported on devices with linux-armv7l and linux-x86_64 architectures

If the device you're running it on does not support either architecture, like the Pi Zero ([which uses armv6](https://raspberrypi.stackexchange.com/questions/83374/raspberry-pi-zero-w-is-armv6-or-armv7)) it will not work.

**Comment by tiancaipipi110** [comment]
I'm confused.   https://developers.google.com/assistant/sdk/guides/service/python/embed/setup
The guide is written for both pi zero and pi, and if it does not support pi zero, why include it in the guide?
So basically I cannot setup Google Assistant Service on Raspberry Pi zero right?

**Comment by tiancaipipi110** [comment]
I finally got the assistant to work on Pi 0 with pushtotalk sample by installing `python -m pip install --upgrade --no-binary :all: grpcio` before the SDK installation. However, the assistant will either take forever to give me NO response or not able to finish the response, in either situation, I'll have to close the terminal to end the session. 
Help please?

**Comment by Fleker** [comment]
The Google Assistant Library includes hotword detection, whereas the Google Assistant Service does not.

We are trying to figure out gRPC installation on the Pi Zero (see #235)

**Comment by Fleker** [comment]
It's probably related to an incompatibility error in the gRPC package which is not actually able to send the request and obtain a response, causing it to hang indefinitely.

**Comment by Fleker** [comment]
See #235 as needed
