### ISSUE TITLE
`sounddevice.PortAudioError: Error opening RawStream: Invalid sample rate [PaErrorCode -9997]`

### ISSUE THREAD

**Issue by tiancaipipi110** [googlesamples/assistant-sdk-python#268]
I was using an external soundcard with both speaker and mic on Raspberry pi 3b, setup was successful since I was able to record/playback/etc. However when I ran the sample code  `googlesamples-assistant-pushtotalk --project-id my-dev-project --device-model-id my-model` 
it showed error:
`sounddevice.PortAudioError: Error opening RawStream: Invalid sample rate [PaErrorCode -9997]`
I think it has something to do with the sampling rate setting since on the google doc audio testing code specified 16000 which in reality most soundcards have 44100...
`arecord --format=S16_LE --duration=5 --rate=16000 --file-type=raw out.raw`

But if I use my sd card with unsuccessful google assistant setup on Raspberry Pi zero on Pi 3, the request is successful. 

Any help will be appreciated.

**Comment by Fleker** [comment]
So you're having issues using the 16000 sample rate on your Raspberry Pi Zero, but using it correctly on your Raspberry Pi 3?

The lower sample rate is sufficient for recording speech, and should be a supported rate for most sound cards.

**Comment by tiancaipipi110** [comment]
I think it has something to do with the file type .raw, not sure how to solve this. But I switch to USB Mic and 3.5mm audio jack as speaker on Raspberry Pi 3B, the issue is gone. 

However another issue poped up, I'm not sure where did I configure it wrong, but the assistant could recognize my speech and decode it, but having trouble output it, which means my speaker is setup incorrectly :

```
ON_CONVERSATION_TURN_STARTED
ON_END_OF_UTTERANCE
ON_RECOGNIZING_SPEECH_FINISHED:
  {"text": "what time is it"}
ON_RENDER_RESPONSE:
  {"text": "The time is 8:58 PM.", "type": 0}
ON_RESPONDING_STARTED:
  {"is_error_response": false}
ALSA lib pcm_dmix.c:1052:(snd_pcm_dmix_open) unable to open slave
[ERROR:audio_output_stream.cc(49)] Device could not be opened: default
```

But when I go test mic and speaker:
```
arecord --device=hw:1,0 --format S16_LE --rate 44100 -c1 test.wav
aplay --device=plughw:0,0 test.wav
```
Both commands worked. 
`speaker-test -t wav` didn't work. it showed error:
```
speaker-test 1.1.3

Playback device is default
Stream parameters are 48000Hz, S16_LE, 1 channels
WAV file(s)
ALSA lib conf.c:4886:(parse_args) Parameter DEV must be an integer
ALSA lib conf.c:4991:(snd_config_expand) Parse arguments error: Invalid argument
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM hw:<0>,<0>
Playback open error: -22,Invalid argument
```

**Comment by tiancaipipi110** [comment]
Ahhh this is so lame, I modified the .asoundrc file as `hw:<0>,<0>`, and the correct one should be `hw:0,0`.

**Comment by Tarek206** [comment]
HI 
I have the same problem 
can anyone help me??

**Comment by Tarek206** [comment]
@tiancaipipi110
