### ISSUE TITLE
SoundDeviceStream - read overflow  AND  write underflow  errors

### ISSUE THREAD

**Issue by kutchbhi** [googlesamples/assistant-sdk-python#269]
pi zero + raspbian jessie + aiy v1 + google assistant python sdk.

Audio output is stuttering, as google assistant outputs these messages:

WARNING:root:SoundDeviceStream read overflow (3200, 6400)
WARNING:root:SoundDeviceStream write underflow (size: 4000)
WARNING:root:SoundDeviceStream write underflow (size: 4000)
WARNING:root:SoundDeviceStream write underflow (size: 4000)
WARNING:root:SoundDeviceStream write underflow (size: 4000)
WARNING:root:SoundDeviceStream write underflow (size: 4000)
WARNING:root:SoundDeviceStream write underflow (size: 4000)
WARNING:root:SoundDeviceStream write underflow (size: 4000)
WARNING:root:SoundDeviceStream write underflow (size: 4000)
WARNING:root:SoundDeviceStream write underflow (size: 4000)
WARNING:root:SoundDeviceStream write underflow (size: 4000)

What do these messages mean exactly ? I am guessing they have to do something with the following settings in the file audio_helpers.py ?

DEFAULT_AUDIO_SAMPLE_RATE = 16000
DEFAULT_AUDIO_SAMPLE_WIDTH = 2
DEFAULT_AUDIO_ITER_SIZE = 6400
DEFAULT_AUDIO_DEVICE_BLOCK_SIZE = 6400
DEFAULT_AUDIO_DEVICE_FLUSH_SIZE = 25600

To stop audio from stuttering I tried playing with various values here.
The changes do seem to have an effect, but I no patterns.

Help?

The ~/.adoundrc file. If it matters.

    $ cat .asoundrc
    options snd_rpi_googlemihat_soundcard index=0
    pcm.softvol {
    type softvol
    slave.pcm dmix
    control {
    name Master
    card 0
    }
    }

    pcm.micboost {
    type route
    slave.pcm dsnoop
    ttable {
    0.0 30.0
    1.1 30.0
    }
    }

    pcm.!default {
    type asym
    playback.pcm "plug:softvol"
    capture.pcm "plug:micboost"
    }

    ctl.!default {
    type hw
    card 0
    }

**Comment by maroonsp1rit** [comment]
Were you ever able to resolve this?

**Comment by maroonsp1rit** [comment]
I have solved the issue and documented here: https://github.com/googlesamples/assistant-sdk-python/issues/272
