### ISSUE TITLE
Voice activated Google assistant .

### ISSUE THREAD

**Issue by Kinjalk** [googlesamples/assistant-sdk-python#27]
How can I add wakeword engine like snowboy ?  Pushing button each time is not very friendly .

**Comment by alfongj** [comment]
@Kinjalk please subscribe to #1 if you are interested in the SDK supporting hotword natively.

There's already some people in the community who have implemented wakeword with snowboy + the Assistant API. Please take a look at the [G+ community](g.co/assistantsdkdev)
