### ISSUE TITLE
Overflows/underflow with streaming on the PiZero (choppy audio)

### ISSUE THREAD

**Issue by maroonsp1rit** [googlesamples/assistant-sdk-python#272]
So I have installed the pushtotalk.py sample, yet everytime I try to run it I am met with many underflows for buffer writes and overflows for reads. here is a log of a sample conversation:

INFO:root:Connecting to embeddedassistant.googleapis.com
INFO:root:Using device model #### and device id ####
Press Enter to send a new request...
INFO:root:Recording audio request.
WARNING:root:SoundDeviceStream read overflow (3200, 6400)
INFO:root:Transcript of user request: "hello".
INFO:root:Transcript of user request: "hello".
INFO:root:End of audio request detected.
INFO:root:Stopping recording.
INFO:root:Transcript of user request: "hello".
INFO:root:Expecting follow-on query from user.
INFO:root:Playing assistant response.
WARNING:root:SoundDeviceStream write underflow (size: 1600)
WARNING:root:SoundDeviceStream write underflow (size: 1600)
WARNING:root:SoundDeviceStream write underflow (size: 1600)
INFO:root:Finished playing assistant response.
INFO:root:Recording audio request.
INFO:root:Transcript of user request: "what".
INFO:root:Transcript of user request: "what's".
INFO:root:Transcript of user request: "what's the".
INFO:root:Transcript of user request: "what's the weather".
INFO:root:Transcript of user request: "what's the weather like".
INFO:root:Transcript of user request: "what's  the weather like".
INFO:root:Transcript of user request: "what's the  weather like".
INFO:root:Transcript of user request: "what's the  weather like out".
INFO:root:Transcript of user request: "what's the weather  like outside".
INFO:root:Transcript of user request: "what's the weather like  outside".
INFO:root:Transcript of user request: "what's the weather like outside".
INFO:root:End of audio request detected.
INFO:root:Stopping recording.
INFO:root:Transcript of user request: "what's the weather like outside".
INFO:root:Playing assistant response.
WARNING:root:SoundDeviceStream write underflow (size: 4000)
WARNING:root:SoundDeviceStream write underflow (size: 4000)
WARNING:root:SoundDeviceStream write underflow (size: 4000)
WARNING:root:SoundDeviceStream write underflow (size: 4000)
WARNING:root:SoundDeviceStream write underflow (size: 4000)
WARNING:root:SoundDeviceStream write underflow (size: 4000)
WARNING:root:SoundDeviceStream write underflow (size: 4000)
WARNING:root:SoundDeviceStream write underflow (size: 4000)
WARNING:root:SoundDeviceStream write underflow (size: 4000)
WARNING:root:SoundDeviceStream write underflow (size: 2994)
WARNING:root:SoundDeviceStream write underflow (size: 4000)
WARNING:root:SoundDeviceStream write underflow (size: 4000)
WARNING:root:SoundDeviceStream write underflow (size: 4000)
WARNING:root:SoundDeviceStream write underflow (size: 4000)
WARNING:root:SoundDeviceStream write underflow (size: 4000)
WARNING:root:SoundDeviceStream write underflow (size: 4000)
INFO:root:Finished playing assistant response.

Every time one of these warnings appears, it produces a stutter in the output audio (playback is audible, just very choppy and not smooth). Unsure if the read ones create stutter in my voice being recorded. I have trying messing with block size, flush size, iter size etc. and it does have effects but I cannot seem to find a sweet spot. There isn't much documentation regarding these options on the docs pages anyhow (if there is, it's very minimal). Any advice on how to solve?

**Comment by maroonsp1rit** [comment]
Fixed it by setting the audio block size to 80000

**Comment by maroonsp1rit** [comment]
Here is a more complete train of thought:

I'd try keeping the others at defaults and then doing like 0, 1024, 2048, 4096 on the block size to see if it's a speed issue
I'll see about getting it set up myself to do some verbose debugging, but it looks like the error is from relatively close to the metal given the whole root: thing
My guess from the top of my head is a performance issue, the program isn't able to feed samples to play at the speed that it needs so some samples end up getting skipped which causes the stuttering

In which case you might want a larger block size so you need fewer block writes going to the audio device to play the samples?
Anyways, according to the sounddevice library that is actually returning the underflow indicator, the underflow bool is set to true when a gap is inserted into output data, possibly because the stream callback is using too much CPU time
https://github.com/spatialaudio/python-sounddevice/blob/master/sounddevice.py#L1783-L1793

That file holds too many layers of abstraction for audio I/O for it's own good, but that's okay. In the snippet I linked, they say that the underflow might happen during "play()". Turns out, play() calls upon an OutputStream object which again is an abstraction of the RawOutputStream object which is ultimately what is interfacing with the audiosetting the underflow flag. The Google Assistant example is skipping a bunch of the abstractions and writes the buffer straight to RawOutputStream.write() where the underflow error is being tripped due to what seems to be skipped samples due to performance issues. I'm not sure how much deeper I can dig, the next layer of abstraction is a CFFI and that's a whole other can of beans, but it points to a bunch of different audio backends depending on the platform it's running on
That was a bit of a mess but basically the Google sample skips some abstraction in the sounddevice library and writes a buffer straight to a RawOutputStream, which works via a C Foreign Function Interface down to your Pi's audio framework which is ALSA with what I think is a JACK server on top. At this point we're at the Linux kernel so I don't think changing things here is the way to go to say the least.
I would try to change the settings in the Google example to be more performance oriented, like lowering the sample rate/width. I'm not sure if the block size should be bigger or smaller, but play around with each of the settings individually until you find something you think is an acceptable compromise between sound quality and performance

According to the troubleshooting part in the readme.md of the google assistant sdk repo, stuttering audio may be fixed by setting the block size to a value larger than the size of the "ConverseResponse" audio payload. I'm not clear on how to find the payload size, so I guess either make sure there isn't too much else running on your Pi to avoid running out of CPU time or try arbitrarily raising the block size without touching the other settings until things work?

**Comment by Colin1964** [comment]
@maroonsp1rit Realise this is a closed issue but I'm having exactly this issue. Can you confirm which file you changed when you said: 

> Fixed it by setting the audio block size to 80000

and also in which directory that file is located. Many Thanks.

**Comment by Colin1964** [comment]
OK so having looked at #269 I realised I was looking for the audio_helpers.py file located at `/home/pi/env/lib/python3.5/site-packages/googlesamples/assistant/grpc`
Amended the file and changed the audio block size to 80000

*DEFAULT_AUDIO_SAMPLE_RATE = 16000
* DEFAULT_AUDIO_SAMPLE_WIDTH = 2
* DEFAULT_AUDIO_ITER_SIZE = 3200
* DEFAULT_AUDIO_DEVICE_BLOCK_SIZE = 80000
* DEFAULT_AUDIO_DEVICE_FLUSH_SIZE = 25600`

No improvement. symptoms as before. Did I do something wrong?
