### ISSUE TITLE
Getting HTML content in terminal

### ISSUE THREAD

**Issue by shivasiddharth** [googlesamples/assistant-sdk-python#274]
When running the hotword script, html content appears on the terminal. The same is the case with pushtotalk as well. 
By using the '--display' flag, we can open the html content on the browser when using the pushtotalk. It appears to be some kind of a prompt to authorize or give permission to google. Once the authorization is done, the pushtotalk resumes normal activity.
On the other hand, as there no display flag for the hotword.py there is no way to open the html content in the browser. I tried copying the entire html text, pasting on to a text file and then opening them in a browser, but that just gives a static page.

**Comment by nunorbatista** [comment]
I'm having the same issue, how are you doing the authorisation?

**Comment by shivasiddharth** [comment]
@nunorbatista There is really nothing that can be done with the hotword.py right now. For time being untill this is fixed, you may have to use the pushtotalk

**Comment by mrGrab** [comment]
I have the same issue, and have no idea how to accept that terms from googlesamples-assistant-hotword via terminal.

**Comment by nunorbatista** [comment]
@shivasiddharth even for pushtotalk I'm having issues, how are you accepting the conditions with the --display param? I add it and then the window opens but when I click "Allow" I get "Something went wrong. Try again."

![image](https://user-images.githubusercontent.com/5253144/43368127-811e31fe-9358-11e8-8540-e85f2970524c.png)

**Comment by fragolinux** [comment]
@nunorbatista same here...

**Comment by NeoMod** [comment]
@Fleker Pardon me but **I believe that this should be considered an “_issue_”** rather than an “_enhancement_”. 

We are not discussing about “_increasing the value or quality_” of the SDK, as it would be in my opinion if we were proposing an added functionality to better control authentication process.

**We are reporting an issue that effectively prevents using the SDK**, either in “_voice activated_” mode or in _“push-to-talk_” mode, thus preventing any (new) user to deploy this project.

Surely one can argue that it is indeed the “_authentication method that needs to be enhanced_” and I would blindly agree, if only the authentication method “somehow worked” with a different setting. 

**Thank you for your kind consideration**, and again beg my pardon if the suggestion to switch label may be perceived as wrongfully placed.

**Comment by VyacheslavTeplyakov** [comment]
Same to me. Fresh install. Hot world gives html text in console and not working. Pushtotalk - no response from assistant + no sound. So Im totally stuck. This is an **issue**.

**Comment by Fleker** [comment]
I agree that this is a bug. On my initial reading, it seemed like the person was requesting a new flag to the sample.

For the Google account that you're using this with, have you already set up the Assistant through another device like a phone, or is this the first time?

**Comment by NeoMod** [comment]
Thank you very much for your attention.

Yes, I am using Google Assistant on my phone with the same account I was trying using for this project, so - I guess - I can answer positively.

**Comment by sr14978** [comment]
Just thought I'd link this stack over flow question as it is referencing the same problem.

https://stackoverflow.com/questions/51575816/trouble-setting-up-google-assistant-sdk-on-raspberry-pi

**Comment by shivasiddharth** [comment]
![image](https://user-images.githubusercontent.com/18142081/43417582-472142bc-9433-11e8-927e-ff64155804d6.png)
May be this has got something to do with the bug.
@Fleker , I can confirm that its the same account that i used for all the assistant devices.

**Comment by mizutori** [comment]
I got the same issue.
Supper strange was when I changed my device model id (in the command below) to a wrong value, it worked. Precisely saying I just deleted the last character of my device model id just to test the case with the wrong value, then the assistant on my Raspberry Pi started talking. So weird..

googlesamples-assistant-hotword --project_id　<My Project Id> --device_model_id <My Device Model Id>

**Comment by keepworking** [comment]
@mizutori  yes it was worked when we put the wrong deviceModelId. but that will be not working for the action of custom command

**Comment by 5amuraix** [comment]
I'm experiencing the same issue.   For some reason after using "googlesamples-assistant-pushtotalk --project-id myProject --device-model-id myModel --display" (--display flag opens the terms and conditions webpage in browser after sending a voice command) ,  I was able to accept the terms on the webpage which allowed the assistant to work as intended afterwards.   Was not able to do the same on another PC...accepting the terms would not be saved.

**Comment by enricomariacaporossi** [comment]
It works imho
![schermata-1](https://user-images.githubusercontent.com/5570782/43671054-bb08087e-9793-11e8-959b-af5323d9a3af.png)
![schermata](https://user-images.githubusercontent.com/5570782/43671056-c223baea-9793-11e8-8f98-eb907776306c.png)

**Comment by enricomariacaporossi** [comment]
it a permission issue... i've played a lot with .json files and now it works well

**Comment by shivasiddharth** [comment]
@enricomariacaporossi , If you can mention as to what you actually did with the json files, it will only then benefit the community.

**Comment by enricomariacaporossi** [comment]
rm /home/pi/assistant.json
rm /home/pi/.cache/voice-recognizer/assistant_credentials.json
rm client_secret_client-id.json
removed my device and model and recreate and re-registrate it

if you have a developement machine try it, not for production.

let me know.

**Comment by shivasiddharth** [comment]
Seems like the issue has been fixed.
