### ISSUE TITLE
cannot get authorization code (error 500)

### ISSUE THREAD

**Issue by gismoranas** [googlesamples/assistant-sdk-python#277]
I followed all the [instructions](https://developers.google.com/assistant/sdk/guides/library/python/embed/setup) to setup the google assistant, but I get stuck when I  need to receive the credentials. I'm using a ubuntu 16. 

`google-oauthlib-tool --client-secrets client_secret_496208924159-5lrts1i88n15p1juu1l7a2em1t798hdq.apps.googleusercontent.com.json --scope  https://www.googleapis.com/auth/gcm --scope https://www.googleapis.com/auth/assistant-sdk-prototype --save --headless`

But I get an "Error 500" when I go to the web page. Also removing --headless and letting the terminal open the browser doesn't change anything. 

Any clue? Thanks!

**Comment by Fleker** [comment]
Can you generate a new client secret file? That one may be invalid for some reason. Where did you download it?

**Comment by thatguytim** [comment]
Can confirm that this is happening to me as well on Raspberry Pi 3 / Raspbian Stretch.

Was running through the instructions at https://developers.google.com/assistant/sdk/guides/library/python/, and getting the oauth credentials worked perfectly on 8/1/2018 (maybe 8/2/2018). I had to do a re-install of the OS and decided to re-run the tutorial from the beginning with a new project on 8/3/2018 and have been getting Error 500 ever since.

What I've tried:
* Deleting the developer project and starting from scratch two times. Got error 500 both times.
* Reinstalled the whole OS (to try and remove any possible bad cache issues), deleted the project and started again. Got error 500 again.
* Double-checked the permissions to make sure the Assisstant API was enabled.
* Tried everything from a browser on the device (to make sure the JSON wasn't getting corrupted on copy from the windows side where I had originally downloaded the client secret.json.)
* Spot-checked the client secret json to check for bogus characters
* Tried removing the "https://www.googleapis.com/auth/gcm" scope from the request

None of the above worked. The only time I got something other than an error 500 was when I accidentally tried running google-oauthlib-tool when I had deleted a project before attempting another clean run-through. In that case it was an error 401 (IIRC) "Project Has Been Deleted", which made sense. 

I'm kind of new to this, so I'm out of ideas ATM. 

Oh, and the client scret json came from the device model registration page.

**Comment by BabisK** [comment]
Same for me on Armbian

**Comment by gismoranas** [comment]
Thanks for your fast reply. I followed the steps of the official docs here https://developers.google.com/assistant/sdk/guides/service/python/embed/register-device . I didn’t change the file name and I restarted from scratch two times to no avail (also deleted the project to be sure). I can send the generated link tomorrow if that can help.

**Comment by amaletzky** [comment]
Same her in Netherlands, thought i was doing something wrong, changed/re-did everything in different accounts and even reinstalled the pi from scratch.

**Comment by gismoranas** [comment]
This is the url I get with the command: 

`google-oauthlib-tool --scope https://www.googleapis.com/auth/assistant-sdk-prototype \
>       --save --headless --client-secrets client_secret_496208924159-5lrts1i88n15p1juu1l7a2em1t798hdq.apps.googleusercontent.com.json`

https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=496208924159-5lrts1i88n15p1juu1l7a2em1t798hdq.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fassistant-sdk-prototype&state=EhCvlhhBeo4sbbtjfhPI0sIOFNbJVy&prompt=consent&access_type=offline

@Fleker please let me know if you need the client file, I can pm it to you.

**Comment by DoruLaz** [comment]
Same here. Raspbian Stretch Lite on pi zero.

**Comment by bmesnard** [comment]
Same here. Raspbian Stretch on pi 3b+.

**Comment by Fleker** [comment]
@gismoranas and @thatguytim when I try to open your links in a browser, I see your project but cannot sign in. I get the error

```
com.google.security.lso.protocol.oauth2.common.OAuth2ErrorException: disabled_client: This app is not yet configured to make OAuth requests. To do that, set up the app’s OAuth consent screen in the Google Cloud Console.
	at com.google.identity.boq.federated.userauthorization.service.continueauth.ContinueAuthProducer.produceAggregateScopes(ContinueAuthProducer.java:119)
	Suppressed: CriticalInputFailure: com.google.identity.boq.federated.userauthorization.service.continueauth.ContinueAuthProducer.produceUpdatedApprovalState failed while trying to inject @com.google.apps.framework.producers.PrivateVisibility(module=com.google.identity.boq.federated.userauthorization.service.continueauth.ContinueAuthProducer.class) com.google.security.lso.auth.meta.scope.ImmutableScopeSet
	Suppressed: CriticalInputFailure: com.google.identity.boq.federated.userauthorization.service.continueauth.ContinueAuthProducer.produceHasIdentityConsent failed while trying to inject @com.google.apps.framework.producers.PrivateVisibility(annotation="@com.google.identity.boq.federated.userauthorization.service.continueauth.Annotations$UpdatedApprovalState", module=com.google.identity.boq.federated.userauthorization.service.continueauth.ContinueAuthProducer.class) com.google.identity.boq.federated.approvalstate.ApprovalState
	Suppressed: CriticalInputFailure: com.google.identity.boq.federated.userauthorization.service.continueauth.ContinueAuthProducer.produceAuthResponse failed while trying to inject @com.google.apps.framework.producers.PrivateVisibility(annotation="@com.google.identity.boq.federated.userauthorization.service.continueauth.ContinueAuthProducer$HasIdentityConsent", module=com.google.identity.boq.federated.userauthorization.service.continueauth.ContinueAuthProducer.class) java.lang.Boolean
	Suppressed: CriticalInputFailure: com.google.identity.boq.federated.userauthorization.service.continueauth.ContinueAuthProducer.produceAutoApproveResponse failed while trying to inject @com.google.apps.framework.producers.PrivateVisibility(annotation="@com.google.identity.boq.federated.userauthorization.service.continueauth.Annotations$UpdatedApprovalState", module=com.google.identity.boq.federated.userauthorization.service.continueauth.ContinueAuthProducer.class) com.google.identity.boq.federated.approvalstate.ApprovalState
	Suppressed: com.google.common.labs.concurrent.LabsFutures$10: GraphFuture{key=@com.google.identity.boq.federated.userauthorization.service.continueauth.Annotations$Response com.google.identity.federated.userauthorization.ContinueAuthResponse} failed: com.google.security.lso.protocol.oauth2.common.OAuth2ErrorException: disabled_client: This app is not yet configured to make OAuth requests. To do that, set up the app’s OAuth consent screen in the Google Cloud Console.
```

Have you setup the OAuth consent screen? It should be in the *Credentials* section

**Comment by bmesnard** [comment]
Configuring the OAuth consent screen did it for me. Now, where is that in the instructions? Thanks!

**Comment by thatguytim** [comment]
@Fleker, that also got me running. I don't remember seeing "OAuth Consent Setup" in the tutorial either, so maybe the "fix" is either a small documentation update or I get myself some reading glasses. 😃 

Either way, thanks for the help getting us back up and running.

**Comment by amaletzky** [comment]
thank YOU @bmesnard

**Comment by mizutori** [comment]
@Fleker After setting up the OAuth consent screen, it worked. Thank you so much!

**Comment by masterpro0415** [comment]
I have same error here. Anybody can help me to fix this?? I am going to setup a Google Assistant on my Pi

**Comment by masterpro0415** [comment]
Hello, I have fixed this error. I have created an OAuth 2.0 client IDs, and recheck again. it worked for me. 
Image:
https://uphinhnhanh.com/image/3mWGAv

**Comment by kal8492** [comment]
@masterpro0415 
Thanks for sharing.
I have created the new .json file as per given link and download and use in the authorization process. it generates the key.
> [https://uphinhnhanh.com/image/3mWGAv]

**Comment by Fleker** [comment]
We have added additional documentation about setting up an OAuth consent screen, which should resolve folks' issues.

https://developers.google.com/assistant/sdk/guides/service/python/embed/config-dev-project-and-account

![image](https://user-images.githubusercontent.com/3291635/44052393-5779366a-9ef1-11e8-8023-48981103d4e0.png)
