### ISSUE TITLE
"googlesamples-assistant-hotword" returns an html code

### ISSUE THREAD

**Issue by antrrax** [googlesamples/assistant-sdk-python#278]
when I enter with following code in Raspberry Pi:

googlesamples-assistant-hotword --project_id MY-ID --device_model_id MY-MODEL

and I say "Ok Google"
Then I ask a question in the microphone.
What I said is written on the screen.
and then an extended html code appears and nothing is answered

as in this image:

![erro](https://user-images.githubusercontent.com/24946480/43681105-d7281eda-9820-11e8-8eca-7794bca93c9b.jpg)

---
What's going on wrong?

**Comment by Fleker** [comment]
See #274
