### ISSUE TITLE
Crackling sound from google assistant instead of spoken response

### ISSUE THREAD

**Issue by theraspberryguy** [googlesamples/assistant-sdk-python#279]
Basically, google assistant audio stopped responding and instead there is a crackling sound according to length of response which is received. Everything works apart from the fact google assistant does not speak. On the console, here is the error I get I cannot understand why: 
Method - google.internal.speech.S3OnePlatform.Assistant
Response Code - 499

I have spent a long time to try and single out every possibility but not sure why this is happening. thanks in advance for any help or suggestions.

**Comment by Fleker** [comment]
HTTP 499 indicates **Client Closed**

But I think if you're getting static then the error is probably related to audio I/O. How are you connecting your speaker/microphone?

**Comment by Fleker** [comment]
It looks like you're using the library / hotword sample. The audio management there is embedded closely, so there may be a discrepancy if you're trying to do audio out through two TTS services at the same time.

**Comment by Fleker** [comment]
Are you still seeing this issue?

**Comment by tdo1** [comment]
I have the same issue with hotword but not with pushtotalk , and the audiotest is working great
