### ISSUE TITLE
option --lang not available in hotword mode !!

### ISSUE THREAD

**Issue by fhenryco** [googlesamples/assistant-sdk-python#281]
--lang fr-FR option is available for 
googlesamples-assistant-pushtotalk ... and i could test it in french
but apparantly not for
googlesamples-assistant-hotword

 in principle if french is supported for pushtotalk there is no additional work to make it work in hotword mode so i'm surprised ! or did i miss something ?

**Comment by Fleker** [comment]
To change the language used in the hotword sample, the setting will instead appear in [the settings of the Google Assistant app](https://developers.google.com/assistant/sdk/reference/assistant-app/assistant-settings) for your device.

**Comment by fhenryco** [comment]
Thank you, i managed to make it work...but the answers i get through pushtotalk  on the PC seem less performant compared to those from the google home assistant on my android smartphone. May be it's just because the one on the smartphone can interact with a web browser to answer through the opening of various webpages ... 

is there a documented way to achieve the same using "kind of extensions" to the assistant-sdk-python ?

**Comment by Fleker** [comment]
You can overload commands using [custom device actions](https://developers.google.com/assistant/sdk/guides/service/python/extend/custom-actions) if you want additional functionality.

**Comment by fhenryco** [comment]
Mmmm yes but apparantly this is designed to allow actions on hardware devices such as switches and so on ... or may be also to launch tasks (scripts, etc...) on the PC but
not really to allow the opening of web pages with info (additional to the one given orally by the answering assistant ) related to the question asked ... as does and is actually the main job of an assistant on any smartphone ...

**Comment by Fleker** [comment]
That's currently what the library provides.

I'm going to close this issue as we've resolved the language switching.
