### ISSUE TITLE
How to make single running google assistant instance accept dual input types (text/voice) label:question

### ISSUE THREAD

**Issue by stephenxp04** [googlesamples/assistant-sdk-python#282]
I am trying to develop an attendance record system with facial recognition system integrated with Google Assistant to converse with user recording action and tracking time. However after meddling with the google assistant python SDK for whole day, I can't seem to wrap my head around how to make a single Google Assistant application both text and audio inputs, the configuration functions for both are different.

So my flow is simple,

(Face Track - python output "NAME" as text) ---> Google Assistant asks "NAME" for action ---> "NAME" reports action through voice ---> Google Assistant detect intent and return response ---> python backend catch JSON response and record.

I am stuck at first entry point, have no idea how to use text as input, then switch to audio for second input. Does anyone have any ideas on doing this? thanks alot!

**Comment by Fleker** [comment]
If you look at [the backend gRPC calls](https://developers.google.com/assistant/sdk/reference/rpc/google.assistant.embedded.v1alpha2), you can see that each `[AssistRequest](https://developers.google.com/assistant/sdk/reference/rpc/google.assistant.embedded.v1alpha2#google.assistant.embedded.v1alpha2.AssistRequest)` will contain an `[AssistConfig](https://developers.google.com/assistant/sdk/reference/rpc/google.assistant.embedded.v1alpha2#google.assistant.embedded.v1alpha2.AssistConfig)` optionally with `audio_in` packets. In the `AssistConfig`, you can see it accepts a union of either `AudioInConfig` or a text query.

It may be helpful to take a look at the source code for `[pushtotalk.py](https://github.com/googlesamples/assistant-sdk-python/blob/master/google-assistant-sdk/googlesamples/assistant/grpc/pushtotalk.py)` and `[textinput.py](https://github.com/googlesamples/assistant-sdk-python/blob/master/google-assistant-sdk/googlesamples/assistant/grpc/textinput.py)` to see how each makes API calls, then try to merge functionality from both.

**Comment by stephenxp04** [comment]
Hi thanks for reply. I took some time to understand the assist request construct function. So if i understand correctly , whenever I am switching from text or audio input i will have to reload the AssistConfig which is configured for each type of input right?

**Comment by stephenxp04** [comment]
Got it to work. Just set a boolean for mode switching after each assist request is made, since my assist requests are alternating between text and audio each cycle.
