### ISSUE TITLE
Change hotword

### ISSUE THREAD

**Issue by mra1984** [googlesamples/assistant-sdk-python#283]
Is it possible to change the google hotword in the assistant demo or another way?

**Comment by Fleker** [comment]
You can look at third-party hotword libraries, but that's not something directly supported in the demo or sample.

**Comment by mra1984** [comment]
Thanks. Any links? I tried snowboy but this doesn't  work with local  commands version. Shame google made an aiy kit where you can't  change the main hotword....

**Comment by Fleker** [comment]
I don't see why Snowboy wouldn't work. You just need a way to open the microphone and stream audio.

**Comment by mra1984** [comment]
Snowboy works but only with the button version
Full explanation here:
https://steemit.com/utopian-io/@neavvy/google-assistant-on-raspberry-or-part-3-custom-wake-word

This then means you lose the ability to use voice commands. If I am wrong could you tell me how to change assistant demo with local commands to use a snowboy hotword? I should be so grateful. But looking online I can see no one who has implemented this. Thanks



Sent from my Samsung Galaxy smartphone.

-------- Original message --------

**Comment by Fleker** [comment]
In [hotword.py](https://github.com/googlesamples/assistant-sdk-python/blob/master/google-assistant-sdk/googlesamples/assistant/library/hotword.py) you see

```python
with Assistant(credentials, device_model_id) as assistant:
    events = assistant.start()
    // ...
    for event in events
        process_event(event)
```

If you rewrite it to listen for Snowboy, and a hotword is activated, then you can do [start_conversation](https://developers.google.com/assistant/sdk/reference/library/python/#google.assistant.library.Assistant.start_conversation) like:

```python
with Assistant(credentials, device_model_id) as assistant:
    // Snowboy listen
    for snowboyEvent in snowboyListening:
        assistant.start_conversation()
        for event in events:
            process_event(event)
    // ...
```

**Comment by shivasiddharth** [comment]
@mra1984 , Check out my GassistPi project, i have incorporated snowboy for custom wakeword options.

**Comment by mra1984** [comment]
this looks great! I am working my way through your instructions now, just what I wanted :)
