### ISSUE TITLE
Error in opencv

### ISSUE THREAD

**Issue by karan3569** [googlesamples/assistant-sdk-python#285]
I installed opencv in ubuntu 18.04 but while compiling the code it shows the error
 Traceback (most recent call last):
  File "gesture1.py", line 1, in <module>
    import cv2
ImportError: No module named cv2
I installed all the libraries and tried all the commands but its till showing the error Help me

**Comment by Fleker** [comment]
I'm not sure what this has to do with the assistant-sdk-python project. You may want to consult the [guide on installing for your machine](https://opencv-python-tutroals.readthedocs.io/en/latest/py_tutorials/py_setup/py_table_of_contents_setup/py_table_of_contents_setup.html#py-table-of-content-setup).
