### ISSUE TITLE
Script it !

### ISSUE THREAD

**Issue by thib5** [googlesamples/assistant-sdk-python#287]
Ok 2 tricky question : 

First :  Can I script it to automate it. something like : 
`python3 textinput.py --device-id XXXXX --device-model-id XXXXXX -I "What time is it" `

Then if we can script it can we use it to lunch a Spotify playlist on a google home ? so let say every day at 5 pm I run that script : `python3 textinput.py --device-id XXXXX --device-model-id XXXXXX -I "Cast Radiohead playlist from Spotify to LIVINGROOM google home " `

Thanks

**Comment by Fleker** [comment]
I don't see why you couldn't do that.

**Comment by thib5** [comment]
the first one did not work... I received the error : Error: no such option: -i you have to run txtinput.py then write some command. the second one if I try it even after running txtinput.py nothing happen ...

**Comment by Fleker** [comment]
Okay, looking back at the [command line flags of the sample](https://github.com/googlesamples/assistant-sdk-python/blob/master/google-assistant-sdk/googlesamples/assistant/grpc/textinput.py) by default, there is no flag to pass in text. It would probably be easy to add this `-I` flag but the option is not there by default.

You are looking at the information for the library, [which is different from the service API](https://developers.google.com/assistant/sdk/overview#features). The [library sample](https://github.com/googlesamples/assistant-sdk-python/blob/master/google-assistant-sdk/googlesamples/assistant/library/hotword.py) does have a `send_text_query` method, although it's not shown in the sample right now.

**Comment by thib5** [comment]
so is it possible to do it ? will it be later ?

**Comment by Fleker** [comment]
It's possible today if you want to modify the scripts. Otherwise it'll probably be something to incorporate later into the stock sample.

**Comment by thib5** [comment]
Humm ... I don't think I'am able to modify the script ... 😔

**Comment by Fleker** [comment]
You can get the source code directly from this GitHub repository.
