### ISSUE TITLE
Google Assistant voice response in text in 16*1 LCD

### ISSUE THREAD

**Issue by bhavikbhansali** [googlesamples/assistant-sdk-python#289]
Hello, I set up google assistant in raspberry pi zero and its working great. Now I want to show the response in 16*1 LCD which I attached to raspberry pi zero. Any Help.

**Get the text of the Assistant's response
The Google Assistant SDK gives you the plain text of the Assistant response. Use this to provide feedback to the user by rendering the text to a display.

This text is located in the DialogStateOut.supplemental_display_text field.**

I got this in google developer guide but not getting how to do it.

**Comment by Fleker** [comment]
If you're using the Service API, it should be a field that you obtain as one of the responses from the Assistant, in addition to audio. You can take a look at [textinput.py](https://github.com/googlesamples/assistant-sdk-python/blob/master/google-assistant-sdk/googlesamples/assistant/grpc/textinput.py) as an example of [how to process the supplemental_display_text](https://github.com/googlesamples/assistant-sdk-python/blob/master/google-assistant-sdk/googlesamples/assistant/grpc/textinput.py#L119).

**Comment by bhavikbhansali** [comment]
I am pretty new to this can you please show me how to run it and modified it. It would be great for me. :-) Thanks for helping me.

**Comment by bhavikbhansali** [comment]
Hello @Fleker I tried to run textinput.py and I got error like below.

Traceback (most recent call last):
  File "textinput.py", line 22, in <module>
    import google.auth.transport.grpc
ImportError: No module named google.auth.transport.grpc

Any help on this?
I tried to figureout how to solve this but not get success.

**Comment by Fleker** [comment]
Looks like you should install all of the requirements in `requirements.txt`.

I don't know enough about your specific LCD implementation to give you the exact code that you need, but here's basically what you'd want to do:

```python
response_text, response_html = assistant.assist(text_query=query)
lcd.write(response_text)
```

**Comment by bhavikbhansali** [comment]
@Fleker Thanks for helping me.
sudo pip install -r assistant-sdk-python/google-assistant-sdk/googlesamples/assistant/grpc/requirements.txt 
will work for me. Let's see whether it will work or not? Right now it is installing all the requirement which is mentioned in requirements.txt

Thanks for helping. Will, back once it will finish.

**Comment by bhavikbhansali** [comment]
Hello,
After successful installation of the requirement, I tried below command which I found in a readme file.

python -m textinput --device-id 'my-device-identifier' --device-model-id 'my-model-identifier'

but it throws an error which is as below.

Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/pi/assistant-sdk-python/google-assistant-sdk/googlesamples/assistant/grpc/textinput.py", line 32, in <module>
    from . import (
ValueError: Attempted relative import in non-package

**Comment by Fleker** [comment]
It looks like an unusual importing error. Which directory are you running this in?

**Comment by bhavikbhansali** [comment]
Hello, @Fleker Thanks for the reply. I solved that error by `pip install --upgrade -r requirements.txt` applying this command.

Is there any way to get an only response instead of HTML?

**Comment by Fleker** [comment]
You can get the display text and the html as two separate output types. You get text or HTML depending on whether the [`screen_mode`](https://github.com/googlesamples/assistant-sdk-python/blob/master/google-assistant-sdk/googlesamples/assistant/grpc/textinput.py#L103) is set to OFF or PLAYING.

**Comment by bhavikbhansali** [comment]
![screenshot_20180905-015342](https://user-images.githubusercontent.com/11437390/45055922-ef46e900-b0ae-11e8-8d89-25f8858c3306.png)
So as in screenshot if I select it will give me output in term of text because right now it is in playing and it gives a HTML output.

Correct me if I am wrong.

**Comment by Fleker** [comment]
Yes if you change the ScreenMode it will change the responses that you get.

**Comment by bhavikbhansali** [comment]
When I get output in html page at that time in my terminal I got something written as below.

"Message: console message: file:///tmp/tmp1ka7ou2b/google-assistant-sdk-screen-out.html @49: TypeError: Map constructor does not accept arguments"

May I know from where I get .html file path?

**Comment by Fleker** [comment]
The file path [is generated randomly](https://github.com/googlesamples/assistant-sdk-python/blob/master/google-assistant-sdk/googlesamples/assistant/grpc/browser_helpers.py#L24) as a temporary file.

**Comment by bhavikbhansali** [comment]
Thank you @Fleker for you huge help. Around a week ago I done with my requirement. I was able to get a just required text from the response and print it on 16*1 Character LCD.

Thing I did is below:

1. Ask google like "Spell GITHUB"
2 Google reply like "GITHUB is spelled GITHUB"
3. Enable display which will give output in form of a webpage
4. I parse an entire webpage which is in HTML format.
5. Parsed word will be put on a variable on local python script.

Every this is modified under pushtotalk.py file.


For more in detailed information please visit the [bhavikbhansali.com](url) (I am preparing a blong on this so once its is ready will make it live)

**Comment by Fleker** [comment]
Great to hear! But you should also be able to change the ScreenMode so that you get the `supplemental_display_text` directly instead of having to parse the HTML. That'll make your code much simpler.

I'm looking forward to seeing your blog post. Post it here once it's ready. In the meantime I'll close the issue since everything seems to be working.
