### ISSUE TITLE
Google assistant not hearing the hotword.

### ISSUE THREAD

**Issue by Terobero** [googlesamples/assistant-sdk-python#290]
Google doesn't hear us saying "Ok google". It was working until this morning. We have tried to change the sensitive as the troubleshooting said but it didn't work. We deleting everything about google assistant and redownloaded via https://developers.google.com/assistant/sdk/guides/library/python/ but same thing. At the step Run the Sample Code, the sample code runs but couldn't hear us. The mic perfectly works, it worked at Configure and Test the Audio state. As I've said, it was working until this morning, and the test didn't even work. I'd be glad if anyone could help!

**Comment by Fleker** [comment]
Are there any logs in your console when running the sample project that may suggest an error in execution? Can you confirm that you're using the hotword sample?

**Comment by Terobero** [comment]
I am pretty sure I was using the hotword sample, we just used another SD card (It was on Raspberry Pi) and doing everything from start worked. It is working currently but I am still not sure it didn't work on the other card.
