### ISSUE TITLE
i'd like to know google assistant pushtotalk execute command help me

### ISSUE THREAD

**Issue by gudfkr123** [googlesamples/assistant-sdk-python#292]
how can i execute my edited pushtotalk.py file? what command?
i know this command python -m pushtotalk --device-id xxxxxx --device-model-id xxxxx . is that collect? but i don't know my device-id.  how can i check my device-id? or another command?

**Comment by Fleker** [comment]
Your device id is not too important, as long as you use the device-model-id that you created.
