### ISSUE TITLE
audio file input not working except sample test .riff files

### ISSUE THREAD

**Issue by lohriialo** [googlesamples/assistant-sdk-python#294]
Assistant doesn't seem to understand audio files other than `.riff ` test sample files provided in the sdk. For example: I ran a .wav file recorded from smartphone but assistant doesn't do anything, however if ran one of the `.riff ` test file, it work

`python -m audiofileinput --device-id 'my-device-identifier' --device-model-id 'my-model-identifier' -i whatstheweather.wav -o out.wav`

**Works:** https://github.com/googlesamples/assistant-sdk-python/blob/master/google-assistant-sdk/tests/data/whattimeisit.riff

**Doesn't work:** https://www.dropbox.com/s/mtrjd6g0jiuufb3/whatstheweather.wav?dl=0

How is those `.riff` test sample files created? Is there a tool we can use to create one ourself? It seems a bummer if the commonly used .`wav` files are not recognised by assistant

**Comment by Fleker** [comment]
I'd look at specific encoding practices in each audio file type, such as the sample rate. The sample reads in raw audio data, and sometimes audio tools will compress the data, but this sample doesn't do any decompression.

Using VLC, I have codec info for the included file [1] and the wave file you posted [2].

1. 
![image](https://user-images.githubusercontent.com/3291635/45589767-97935380-b8e0-11e8-9cd0-4adc38adb975.png)

2. 
![image](https://user-images.githubusercontent.com/3291635/45589769-aa0d8d00-b8e0-11e8-9976-74787f97ffc7.png)

**Comment by lohriialo** [comment]
@Fleker thanks for your help, If i reconvert the audio `Sample rate ` to about `11025hz` it does seem to work, would be really helpful if these stuffs are documented in the [Readme](https://github.com/googlesamples/assistant-sdk-python/blob/master/google-assistant-sdk/googlesamples/assistant/grpc/README.rst). Hard to figure out what was going on as audio files recorded straight from a smartphone failed to work

**Comment by Fleker** [comment]
I'll file a note to look into this in more depth.
