### ISSUE TITLE
unable to install flask-bootstrap

### ISSUE THREAD

**Issue by mwanduka** [googlesamples/assistant-sdk-python#305]
I tried to install bootstrap4 by this command:
pip install flask-bootstrap4

but it brought me this error:
Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/usr/local/lib/python3.6/dist-packages/visitor-0.1.3.dist-info'
Consider using the `--user` option or check the permissions.

**Comment by Fleker** [comment]
See #236
