### ISSUE TITLE
Custom action queryPatterns not working

### ISSUE THREAD

**Issue by d3o** [googlesamples/assistant-sdk-python#307]
My locale is "es". Sample blink working correctly, but I modify sample blink with my custom action, and It don't working. 

versions:

google-assistant-library (1.0.0)
google-assistant-sdk (0.5.0)

My actions.json:

```
{
	"manifest": {
		"displayName": "Execute Scene",
		"invocationName": "Execute Scene",
		"category": "PRODUCTIVITY"
	},
	"actions": [{
			"name": "com.example.actions.SCENE",
			"availability": {
				"deviceClasses": [{
						"assistantSdkDevice": {}
					}
				]
			},
			"intent": {
				"name": "com.example.intents.SCENE",
				"parameters": [{
						"name": "scene",
						"type": "Scene"
					}
				],
				"trigger": {
					"queryPatterns": [
						"escena $Scene:scene"
					]
				}
			},
			"fulfillment": {
				"staticFulfillment": {
					"templatedResponse": {
						"items": [{
								"simpleResponse": {
									"textToSpeech": "Ejecutada escena $scene"
								}
							}, {
								"deviceExecution": {
									"command": "com.example.commands.SCENE",
									"params": {
										"scene": "$scene"
									}
								}
							}
						]
					}
				}
			}
		}
	],
	"types": [{
			"name": "$Scene",
			"entities": [{
					"key": "NOCHE",
					"synonyms": [
						"noche"
					]
				},{
					"key": "AMANECER",
					"synonyms": [
						"amanecer"
					]
				}
			]
		}
	],
	"locale":"es"
}
```

Actions console registering correctly:

![image](https://user-images.githubusercontent.com/25180274/49257871-e22e6180-f433-11e8-944c-793756049a2a.png)

Start hotword.py and I say: "escena noche" and It response (I can´t help you - this in spanish):

```
ON_MUTED_CHANGED:
  {"is_muted": false}
ON_MEDIA_STATE_IDLE
ON_START_FINISHED
ON_CONVERSATION_TURN_STARTED

ON_END_OF_UTTERANCE
ON_RECOGNIZING_SPEECH_FINISHED:
  {"text": "escena noche"}
escena noche
ON_RESPONDING_STARTED:
  {"is_error_response": false}
ON_RESPONDING_FINISHED
ON_CONVERSATION_TURN_FINISHED:
  {"with_follow_on_turn": false}
```

The trigger Device Action not working.

**Comment by Fleker** [comment]
You've set the language of the Assistant SDK device to be Spanish?

**Comment by d3o** [comment]
> You've set the language of the Assistant SDK device to be Spanish?

Yes, I modified blink sample with locale "es" and It work fine. After that, I modified sample with my custom action, and It don't work.

**Comment by d3o** [comment]
I am solved my problem. gactions clir test expire (past more 30 days). 

Run command below again and I have changed my custom actions:

./gactions test --action_package actions.json --project project_id

It is neccesary return message of gactions cli when test mode expired, because it return that all right, and also to explain better with a message or info as "It is not allowed modify actions although actions console 
 it show them (https://console.actions.google.com/project/twisterbox-speak/overview)".

Thanks.
