### ISSUE TITLE
disabled_client ... app not yet configured to make OAuth requests ... OAuth consent screen

### ISSUE THREAD

**Issue by Digital-Thor** [googlesamples/assistant-sdk-python#309]
The [SDK instructions say fields are optional](https://developers.google.com/assistant/sdk/guides/library/python/embed/config-dev-project-and-account) and also the consent screen says that I can save without publishing, but when I use the google-oauthlib-tool, the resulting link tells me that I still need to configure the consent screen.  
`
Error:  "disabled_client  This app is not yet configured to make OAuth requests. To do that, set up the app’s OAuth consent screen in the Google Cloud Console."`

I want to use google assistant for home automation using the sample Google Assistant Library SDK and don't need to invite other users.  Can I use the API credentials with the SDK instead of OAUTH or will the API credentials also require the entire consent screen to be completed/published?

**Comment by Digital-Thor** [comment]
I managed to get this authorized without having to add the optional fields in the consent screen.  Possibly due to confusion in the instructions about _which_ json credentials file to use in the instructions.  I believe it is the *device* credentials json file that is needed.  Unfortunately, the test command: 
`
googlesamples-assistant-hotword --project-id my-dev-project --device-model-id my-model
`
now results in a segmentation fault.  I will create a new issue for that if I can't figure it out.

**Comment by Fleker** [comment]
You need to generate OAuth credentials, which includes setting up the OAuth consent screen, then using the google-oauthlib-tool to generate credentials from the device credentials for your account

**Comment by Digital-Thor** [comment]
Thanks. In fact, I got authorized even _without_ the optional fields in the consent screen.  The segfault went away when I invoked the program from within its library path.  :-)
