### ISSUE TITLE
google-assistant-library empty

### ISSUE THREAD

**Issue by ianno** [googlesamples/assistant-sdk-python#32]
The folder google-assistant-library is empty.
But it seems the library package is required to run googlesamples-assistant-hotword...

Running it returns:
```
  File "/home/pi/assistant-sdk-python/google-assistant-sdk/googlesamples/assistant/library/hotword.py", line 26, in <module>
    from google.assistant.library import Assistant
ImportError: No module named 'google.assistant.library'
```

**Comment by ianno** [comment]
Also, running 
`pip install --upgrade google_assistant_library-0.0.2-py2.py3-none-linux_armv7l.whl` 
on Raspberry pi 3 returns:
`google_assistant_library-0.0.2-py2.py3-none-linux_armv7l.whl is not a supported wheel on this platform.`

**Comment by proppy** [comment]
@ianno did you upgrade pip w/ `pip install --upgrade pip` ?

**Comment by ianno** [comment]
Upgrading pip worked!
Thanks!
