### ISSUE TITLE
Set Assistant Volume with command

### ISSUE THREAD

**Issue by mrbmi513** [googlesamples/assistant-sdk-python#335]
Would be nice to be able to set a default volume with a simple python command. In my application, anything lower than max is too low, and having to repeatedly say "set volume to max" gets very annoying very quickly.

**Comment by shivasiddharth** [comment]
https://github.com/googlesamples/assistant-sdk-python/blob/84995692f35be8e085de8dfa7032039a13ae3fab/google-assistant-sdk/googlesamples/assistant/library/hotword.py#L154  Use this to set the volume to max on start.

**Comment by mrbmi513** [comment]
`assistant.send_text_query` is not working when I insert it into  __main__.py
