### ISSUE TITLE
Error: Missing option "--device-model-id"

### ISSUE THREAD

**Issue by Shashank-Agrawal-1998** [googlesamples/assistant-sdk-python#344]
When I am running this code, it is showing me the following error.
=====================================
Usage: FB_BOT.py [OPTIONS]

Error: Missing option "--device-model-id".
=====================================

What changes should I make so that it can run successfully???

**Comment by Fleker** [comment]
Read the documentation on [creating a device model id](https://developers.google.com/assistant/sdk/guides/library/python/embed/register-device).

**Comment by rohitmsaxena** [comment]
@Fleker How is that different then --device-id ?

**Comment by Fleker** [comment]
The device model id is a classification of devices, like "Google Home". The device id is the specific instance of that device, like "Nick's kitchen Google Home".
