### ISSUE TITLE
How to change pytesseract language mac for OCR?

### ISSUE THREAD

**Issue by diodas2003** [googlesamples/assistant-sdk-python#346]
I am working on an ocr on python on mac. However, when I run the program it pytesseract recognises only english and not other languages.

My code is the following:

> from PIL import Image
> import pyscreenshot as ImageGrab
> import pytesseract
> 
> 
> if __name__ == '__main__':
>     im = ImageGrab.grab(bbox=(128,118,430,266))
>     im.save('34.png')
>     im.show()
> im = Image.open('34.png')
> text = pytesseract.image_to_string(im, lang = 'I should need Italian here')
> print(text)
> 

    
I need a way to make the ocr work even with other languages. Can someone help me?

**Comment by Fleker** [comment]
This is unrelated to this project
