### ISSUE TITLE
"play music" "play iHeartradio" "play TuneIn" are not supported yet?

### ISSUE THREAD

**Issue by zuowanbushiwo** [googlesamples/assistant-sdk-python#347]
My follow this guides、：
     https://developers.google.com/assistant/sdk/guides/library/python/
 setup  google assistant  on my  Ubuntu Desktop .
 it can  run normally, and ask some questions, it can give you an answer 。
but when I ask   "play music" "play iHeartradio" "play TuneIn"  like avs sdk client，it alway say  ”Sorry, something went wrong. When you're ready, give it another try."
Do you currently support these commands? or Need to make related settings for the account in my console，but I do not find some guidance?
 thanks！

**Comment by Fleker** [comment]
Music and radio playback is not supported.

**Comment by zuowanbushiwo** [comment]
@Fleker 
I am a developer of smart speaker ODMs from China. Our company has developed avs smart speaker products and recently plans to research Google's smart speaker solutions, like Google home. But we intend to develop on the Linux platform, mainly because our other smart speaker products are based on linux. I have been looking for Linux's smart speaker solution (can play music, news, radio) on the developers google platform recently, but I have not found it. Can you give some guidance?
