### ISSUE TITLE
How to make a smart speaker like Google home，JBL Link 300，sons one , bose home speaker 300？

### ISSUE THREAD

**Issue by zuowanbushiwo** [googlesamples/assistant-sdk-python#348]
Hi：
     I am a developer of smart speaker ODMs from China. Our company has developed avs smart speaker products and recently plans to research Google's smart speaker solutions, like Google Home，JBL Link 300，Sons One , Bose Home Speaker 300. But we intend to develop on the Linux platform, mainly because our other smart speaker products are based on linux. 
    I know  Google Assistant Library and  Google Assistant Service able to run on linux platform，But currently neither of these sdk components can play music and radio，which are very important for a smart speaker。
    I have been looking for Linux's smart speaker solution (can play music, news, radio) on the developers google platform recently, but I have not found it.  Are there other options for smart speaker ?  Can you give some guidance?
    thanks！
    Bose : https://www.bose.com/en_us/products/speakers/smart_home/bose-home-speaker-300.html?mc=25_PN_H3_GA_00_GO_
     Sonos: https://www.sonos.com/en-us/shop/one.html?utm_source=googleassistant&utm_medium=referral
      jbl: https://www.jbl.com/voice-activated-speaker/JBL+LINK+300.html

**Comment by Fleker** [comment]
You would need to enter a commercial agreement with Google to use the SDK for commercial purposes.
