### ISSUE TITLE
Orange Pi Zero support

### ISSUE THREAD

**Issue by bachoo786** [googlesamples/assistant-sdk-python#363]
Hello all

I have managed to install google assistant on orange pi zero and can communicate with the assistant using the pushtotalk.py file. However I wanted to use the "googlesamples-assistant-hotword" but it gives me an error saying Segmentation Fault.

Can someone please help with that? Has anyone installed google assistant on Orange Pi Zero?

Thanks.

**Comment by shivasiddharth** [comment]
Duplicate of #356

**Comment by Fleker** [comment]
Duplicate, closing.

**Comment by bachoo786** [comment]
Duplicate of 356? How?
