### ISSUE TITLE
textinput requests not working

### ISSUE THREAD

**Issue by SrDayne** [googlesamples/assistant-sdk-python#365]
I send command:
python -m textinput --device-id '1d4245daXXXXXX' --device-model-id 'home-862XXXX'

And I receive:
/home/pi/env/bin/python: No module named textinput

**Comment by Fleker** [comment]
Are you running it from the correct directory?

**Comment by SrDayne** [comment]
Yes, first of all I execute:
source env/bin/activate

**Comment by Fleker** [comment]
Then do you go to `google-assistant-sdk/googlesamples/assistant/grpc`?

**Comment by SrDayne** [comment]
No, where this folder should be? In what directory?

**Comment by Fleker** [comment]
The file you're trying to run is `google-assistant-sdk/googlesamples/assistant/grpc/textinput.py`. So to run `textinput`, you'll need to be in that directory or run it differently.

`python -m google-assistant-sdk.googlesamples.assistant.grpc.textinput ...`

**Comment by SrDayne** [comment]
But I don't have this directory.
These directories located in env directory:

drwxr-xr-x 2 pi pi 4096 Aug  1 00:01 bin
drwxr-xr-x 2 pi pi 4096 Jul 31 23:57 include
drwxr-xr-x 3 pi pi 4096 Jul 31 23:57 lib
-rw-r--r-- 1 pi pi   69 Jul 31 23:57 pyvenv.cfg
drwxr-xr-x 3 pi pi 4096 Jul 31 23:57 share

This is the way, where I can find textinput.py:
/home/pi/env/lib/python3.7/site-packages/googlesamples/assistant/grpc

So, when I go to this directory execute command as before, nothing changes.

**Comment by Fleker** [comment]
What do you mean nothing changes? Does `textinput.py` not exist?

**Comment by SrDayne** [comment]
Exists, but in this directory:
/home/pi/env/lib/python3.7/site-packages/googlesamples/assistant/grpc

**Comment by SrDayne** [comment]
I ran:
`python -m google-assistant-sdk.googlesamples.assistant.grpc.textinput --device-id '1d4245daXXXXXX' --device-model-id 'home-862XXXX'`
And it gives back:
`/home/pi/env/bin/python: Error while finding module specification for 'google-assistant-sdk.googlesamples.assistant.grpc.textinput' (ModuleNotFoundError: No module named 'google-assistant-sdk')`
When I go to the directory, where textinput.py located and execute:
`python -m google-assistant-sdk.googlesamples.assistant.grpc.textinput --device-id '1d4245daXXXXXX' --device-model-id 'home-862XXXX'`
It gives back:
`/home/pi/env/bin/python: Error while finding module specification for 'google-assistant-sdk.googlesamples.assistant.grpc.textinput' (ModuleNotFoundError: No module named 'google-assistant-sdk')`

So, what am I doing wrong?

**Comment by Fleker** [comment]
`python -m google-assistant-sdk.googlesamples.assistant.grpc.textinput`

is very similar to running

`python google-assistant-sdk/googlesamples/assistant/grpc/textinput.py`

So you should make sure you're directories line up.

**Comment by SrDayne** [comment]
Finally, I found the right way, deleting level by level, until I get the right directory:
python -m googlesamples.assistant.grpc.textinput --device-id 'XXXXXXXXXXX' --device-model-id 'XXXXXXXXXX'

Guys, you really need do renew readme. There is outdated information.
