### ISSUE TITLE
Install failure with armv6l architecture

### ISSUE THREAD

**Issue by frakman1** [googlesamples/assistant-sdk-python#37]
I followed all the [instructions ](https://developers.google.com/assistant/sdk/prototype/getting-started-pi-python/run-sample)faithfully until I got to "Get the library and sample code" and ran into this error:

``` diff
(env) pi@raspberrypi:~ $ python -m pip install --upgrade https://github.com/googlesamples/assistant-sdk-python/releases/download/0.3.0/google_assistant_library-0.0.2-py2.py3-none-linux_armv7l.whl
- google_assistant_library-0.0.2-py2.py3-none-linux_armv7l.whl is not a supported wheel on this platform
```
Note I am running on the latest Raspberry Pi Zero Wireless and latest Jessie image:
```
(env) pi@raspberrypi:~ $ uname -a
Linux raspberrypi 4.9.24+ #993 Wed Apr 26 17:56:54 BST 2017 armv6l GNU/Linux
```
I see that mine is armv6l and your release is for armv7l. 
```diff
+ Can you please add support for armv6l ?
```

**Comment by proppy** [comment]
@frakman1 can you try to update pip:
```
python -m pip install --upgrade pip setuptools
````

**Comment by frakman1** [comment]
What makes you think I am using an older version of pip? I already ran that command. Here is the log:

``` diff
+ pi@raspberrypi:~ $ env/bin/python -m pip install --upgrade pip setuptools
Downloading/unpacking pip from https://pypi.python.org/packages/b6/ac/7015eb97dc749283ffdec1c3a88ddb8ae03b8fad0f0e611408f196358da3/pip-9.0.1-py2.py3-none-any.whl#md5=297dbd16ef53bcef0447d245815f5144
  Downloading pip-9.0.1-py2.py3-none-any.whl (1.3MB): 1.3MB downloaded
Downloading/unpacking setuptools from https://pypi.python.org/packages/27/45/79618f80704497f74f2de1ca62216a5c3ffdbd49f43047c81c30e126a055/setuptools-35.0.2-py2.py3-none-any.whl#md5=54a3dac8fe9b912bb884a485d9a2e9cb
  Downloading setuptools-35.0.2-py2.py3-none-any.whl (390kB): 390kB downloaded
Downloading/unpacking appdirs>=1.4.0 (from setuptools)
  Downloading appdirs-1.4.3-py2.py3-none-any.whl
Downloading/unpacking packaging>=16.8 (from setuptools)
  Downloading packaging-16.8-py2.py3-none-any.whl
Downloading/unpacking six>=1.6.0 (from setuptools)
  Downloading six-1.10.0-py2.py3-none-any.whl
Downloading/unpacking pyparsing (from packaging>=16.8->setuptools)
  Downloading pyparsing-2.2.0-py2.py3-none-any.whl (56kB): 56kB downloaded
Installing collected packages: pip, setuptools, appdirs, packaging, six, pyparsing
  Found existing installation: pip 1.5.6
    Uninstalling pip:
      Successfully uninstalled pip
  Found existing installation: setuptools 5.5.1
    Uninstalling setuptools:
      Successfully uninstalled setuptools
Successfully installed pip setuptools appdirs packaging six pyparsing
Cleaning up...
+ pi@raspberrypi:~ $ source env/bin/activate
+ (env) pi@raspberrypi:~ $ python -m pip install --upgrade https://github.com/googlesamples/assistant-sdk-python/releases/download/0.3.0/google_assistant_library-0.0.2-py2.py3-none-linux_armv7l.whl
google_assistant_library-0.0.2-py2.py3-none-linux_armv7l.whl is not a supported wheel on this platform.
+ (env) pi@raspberrypi:~ $ uname -a
Linux raspberrypi 4.9.24+ #993 Wed Apr 26 17:56:54 BST 2017 armv6l GNU/Linux
+ (env) pi@raspberrypi:~ $ pip -V
- pip 9.0.1 from /home/pi/env/lib/python3.4/site-packages (python 3.4)

```

**Comment by proppy** [comment]
@frakman1 because something had a similar issue before: https://github.com/googlesamples/assistant-sdk-python/issues/32

> + (env) pi@raspberrypi:~ $ uname -a
Linux raspberrypi 4.9.24+ #993 Wed Apr 26 17:56:54 BST 2017 armv6l GNU/Linux

It appears that you're running a `armv6l` build of Raspbian on Raspberry Pi Zero Wireless, unfortunately the Google Assistant Library currently only supports ["devices with linux-armv7l architectures (like the Raspberry Pi 3 B)."](https://developers.google.com/assistant/sdk/overview#google_assistant_library_for_python).

Updating the issue to track suppot for other architecture.

**Comment by antoves** [comment]
I have created another issue but I think that it could be useful to write the same question here:

Since the new version of the GoogleAssistant SDK doesn't seem to be compatible with the raspberry pi zero w while the version 0.2.0 was compatible, is there any way to set up the old one instead of the newest?

Thank you for the attention

**Comment by frakman1** [comment]
Do you mean `git checkout` the 0.2.0 version of this repo? I will still need a compatible version of this file: `google_assistant_library-0.0.2-py2.py3-none-linux_armv7l.whl`
Where can I get a version of this file that I can use? It would need to be built for the `armv6l`

**Comment by proppy** [comment]
@antoves @frakman1 the grpc bindings (which was used in the old version) is now splitted in a separate package `google-assistant-grpc`: https://pypi.python.org/pypi/google-assistant-grpc

**Comment by proppy** [comment]
Filed #49 and #50 ope this will help to streamline the install process.

```
pip install google-assistant-library # will work on Raspberry Pi 3
```

```
pip install google-assistant-grpc # will work on Raspberry Pi Zero W
```
