### ISSUE TITLE
BENCH COMMAND NOT FOUND 

### ISSUE THREAD

**Issue by ezegde** [googlesamples/assistant-sdk-python#375]
erpnext@Mdui:/opt/erpnext$ bench init frappe-bench && cd frappe-bench
Command 'bench' not found, did you mean:
command 'dbench' from deb dbench (4.0-2build1)
command 'tbench' from deb dbench (4.0-2build1)
Try: sudo apt install

ARE THERE ANY ONE CAN HELP ME CONCERNING MY ERROR STATED ABOVE? P'SE

**Comment by Fleker** [comment]
This seems unrelated to the sample.
