### ISSUE TITLE
Assistant Library demo for google voice AIY kit not running 

### ISSUE THREAD

**Issue by ramankri** [googlesamples/assistant-sdk-python#377]
You need client secrets to use the Assistant API.
Follow these instructions:
    https://developers.google.com/api-client-library/python/auth/installed-app#creatingcred
and put the file at /home/pi/assistant.json

Every time I run the file I get this error I have the assistant.json file in pi.

**Comment by Fleker** [comment]
What error?

**Comment by ramankri** [comment]
As I assemble the google voice kit following the guide below 
https://aiyprojects.withgoogle.com/voice
I have followed the guide provided with it step by step 
verify audio works
get credentials was created as it was mentioned in guide
I can see the client id and client secret in assitant.json file 
-> But as i try to run one of example assitant_library_demo.py 

I get the above message. In actual it should have an open sign-in option for a google account.

**Comment by hkoffer** [comment]
I have same problem, how to fix?

**Comment by Franzgornac** [comment]
I have same problem, please help me fix it!
