### ISSUE TITLE
connection failure results in segfault and cryptic error message

### ISSUE THREAD

**Issue by giobauermeister** [googlesamples/assistant-sdk-python#38]
I'm getting the following error on the Raspberry Pi 3 with the new 0.2.0 release. After I say "Ok Google", it shows `ON_CONVERSATION_TURN_STARTED`. Then a few seconds after I make the query, the error shows.
```
(env) pi@raspberrypi:~ $ google-assistant-demo
ON_MUTED_CHANGED:
  {'is_muted': False}
ON_START_FINISHED

ON_CONVERSATION_TURN_STARTED
[2433:2444:ERROR:speech_processing_task.cc(340)] S3 connection has timed out: No data from S3
ON_ASSISTANT_ERROR:
  {'is_fatal': False}
[2433:2444:ERROR:assistant_output_handler.cc(589)] Failed with a general speech recognition error
ON_RESPONDING_STARTED:
  {'is_error_response': True}
Segmentation fault
```

**Comment by proppy** [comment]
Can you confirm that your Raspberry Pi is connected to internet, are you able to ping and curl `embeddedassistant.googleapis.com` ?

**Comment by giobauermeister** [comment]
@proppy I got it working connecting the Raspberry Pi directly to my router with Ethernet cable or WiFi network. 
I always ssh to my Raspberry Pi through a shared network on my laptop with DHCP server and so. I could install packages and also could ping and curl normally as you said but the the assistant didn't work though.

**Comment by proppy** [comment]
Glad you got it working.

Keeping the issue open because of the:
- Segmentation fault
- Cryptic error message
- missleading `ON_RESPONDING_STARTED` event.

**Comment by omercade** [comment]
This is related to not having the API enabled or loosing access to it. Enabling the Google assistant api on google apis website, solves the problem.

(error code could be more explicit)

**Comment by Rohankhairnar123** [comment]
I install google assistant on raspberry pi with noobs OS.
but i'm getting an error as follow:

[8468:8521:ERROR:audio_input_processor.cc(755)] Input error
/home/pi/AIY-projects-python/src/aiy/_drivers/_led.py:51: RuntimeWarning: This channel is already in use, continuing anyway.  Use GPIO.setwarnings(False) to disable warnings.
  GPIO.setup(channel, GPIO.OUT)
Say "OK, Google" then speak, or press Ctrl+C to quit...
Segmentation fault

If any one has any solutions or suggest please let me know..

thank you

**Comment by Rohankhairnar123** [comment]
i solved that all above error now i getting only error as folow:

[8468:8521:ERROR:audio_input_processor.cc(755)] Input error

**Comment by Fleker** [comment]
@Rohankhairnar123 you should take a look at our [audio configuration](https://developers.google.com/assistant/sdk/guides/library/python/embed/audio) page.

**Comment by Rohankhairnar123** [comment]
@Fleker thank you ...i'll check out that.

**Comment by noahwater** [comment]
same problem... https://embeddedassistant.googleapis.com/v1alpha2/projects/noahpi-19xx01/devices/86250A87CB146B18xx1EB7CF1EE75598 200 ON_MUTED_CHANGED: {'is_muted': False} ON_MUTED_CHANGED: {'is_muted': False} ON_START_FINISHED ON_START_FINISHED [5062:5091:ERROR:speech_recognition_activity.cc(605)] S3 connection has timed out: No data from S3 [5062:5091:ERROR:speech_recognition_activity.cc(605)] S3 connection has timed out: No data from S3

appreciate any help..Big thanks NoahWater
