### ISSUE TITLE
Continue conversation after audio file input

### ISSUE THREAD

**Issue by angusyuhin** [googlesamples/assistant-sdk-python#384]
I can successfully use a .wav file as an input of pushtotalk.py. Then, the program ended immediately.
So, I comment out the following lines.

`#if input_audio_file or output_audio_file:
            #assistant.assist()
            #return
`

After commenting out those lines, the program does not end after responding to the query. Instead, it acts normally but does not accept and detect the follow-up voice request anymore.

Is it possible to use an audio file as an input for the beginning of the conversation and continue it with the normal conversation?

**Comment by Fleker** [comment]
Yes, you could modify the code to check for the presence of [DIALOG_FOLLOW_ON](https://github.com/googlesamples/assistant-sdk-python/blob/master/google-assistant-sdk/googlesamples/assistant/grpc/pushtotalk.py#L55) in the response, telling you that there is the expectation of a response.

**Comment by angusyuhin** [comment]
Actually I am a newbie in programming, I can't fully understand how the pushtotalk.py works. But as I try to read through the program and test it my own. I got some guesses.

Logging for noraml voice conversation:
![image](https://user-images.githubusercontent.com/55238007/69694168-de9aec80-1112-11ea-9184-0153b468cf11.png)

Logging for starting with audio file:
![image](https://user-images.githubusercontent.com/55238007/69694248-143fd580-1113-11ea-92a3-a3bef84ca120.png)

Since I comment out those three lines of code, the conversation starts with the audio file will not stop with a single response. Then, I saw the logging of 'Expecting follow-on query from user.' when the conversation start with the audio file, so I guess the assist() have already check the presence of DIALOG_FOLLOW_ON and the result is positive, that's why the conversation continues after I comment out those three lines? But still, the program does not receive my voice anymore even though the logging 'Recording audio request' displayed.

[Side note: for other purposes, I also comment out the click.pause(info='Press Enter to send a new request...') to let the recording start automatically after response]

**Comment by angusyuhin** [comment]
Great! I found the cause, the reason why the mic stop listening to me is that the conversation source defined as follows:

```
if input_audio_file:
        audio_source = audio_helpers.WaveSource(
            open(input_audio_file, 'rb'),
            sample_rate=audio_sample_rate,
            sample_width=audio_sample_width
        )
    else:
        audio_source = audio_device = (
            audio_device or audio_helpers.SoundDeviceStream(
                sample_rate=audio_sample_rate,
                sample_width=audio_sample_width,
                block_size=audio_block_size,
                flush_size=audio_flush_size
            )
        )
```

The conversation_stream is fixed as the start, so I code a setConversationStream function inside the SampleAssistant class for setting the new conversation_stream after playing the response of the audio file. This way the assistant can record my voice after responding to the audio file input.

**Comment by prrotemzelig** [comment]
Hey angusyuhin @Fleker 
can you please publish the full solution and how you fixed this problem?
I have the same problem and I didn't understated how you fix this.


thanks
