### ISSUE TITLE
Is this a low level API?

### ISSUE THREAD

**Issue by laihuiyuan** [googlesamples/assistant-sdk-python#385]
Is this  a low level API? It won't return anything if I send a bit long text requests to the Assistant. This API can only return some simple results, such as Wikipedia or simple conversations. Or is it a problem with my settings?

**Comment by Fleker** [comment]
It should return audio results each time, and only sometimes return text responses regardless of input type.

**Comment by laihuiyuan** [comment]
> It should return audio results each time, and only sometimes return text responses regardless of input type.

Hi, Thank you very much for your reply. Actually, We can set the return format to html_response so that it will return the result every time. 
By the way, developers just can use the Google assistant API up to 500 queries/day.  I have tried to apply for more quota through Google Forms, but I did not receive any feedback. Do you know how I can apply for more quota?

**Comment by Fleker** [comment]
Okay, you can use the HTML response as well.
