### ISSUE TITLE
I was trying to upgrade pip but error occurred. the screenshot is attached. 

### ISSUE THREAD

**Issue by SwastiDahiya** [googlesamples/assistant-sdk-python#396]
![2020-03-22 (2)](https://user-images.githubusercontent.com/53172313/77252094-23c1cc00-6c78-11ea-9d17-1b72c64092fd.png)

Please tell me how to solve it.
Thank you

**Comment by Fleker** [comment]
This issue isn't related to this project.

**Comment by SwastiDahiya** [comment]
Can you please tell me in general irrespective of the project.

**Comment by Fleker** [comment]
Try running `pip install --upgrade pip --user`
