### ISSUE TITLE
Can’t get past the 'Verify audio setup' step

### ISSUE THREAD

**Issue by stursby** [googlesamples/assistant-sdk-python#4]
I'm trying to get this demo working, but getting stuck at the 'Verify audio setup' step.

I'm running this command --> `python -m googlesamples.assistant.audio_helpers`

And get the following output:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/pi/google-home-pi/env/lib/python2.7/site-packages/googlesamples/assistant/audio_helpers/__main__.py", line 94, in <module>
    main()
  File "/home/pi/google-home-pi/env/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/pi/google-home-pi/env/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/pi/google-home-pi/env/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pi/google-home-pi/env/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/pi/google-home-pi/env/lib/python2.7/site-packages/googlesamples/assistant/audio_helpers/__main__.py", line 67, in main
    flush_size=audio_flush_size)
  File "/home/pi/google-home-pi/env/local/lib/python2.7/site-packages/googlesamples/assistant/audio_helpers/__init__.py", line 140, in __init__
    blocksize=int(block_size/2),  # blocksize is in number of frames.
  File "/home/pi/google-home-pi/env/local/lib/python2.7/site-packages/sounddevice.py", line 1491, in __init__
    **_remove_self(locals()))
  File "/home/pi/google-home-pi/env/local/lib/python2.7/site-packages/sounddevice.py", line 1017, in __init__
    'Error opening {0}'.format(self.__class__.__name__))
  File "/home/pi/google-home-pi/env/local/lib/python2.7/site-packages/sounddevice.py", line 2671, in _check
    raise PortAudioError(msg)
sounddevice.PortAudioError: Error opening RawStream: Invalid sample rate
```

Setup:
- Raspberry Pi 3 (Model B)
- Raspbian Jessie Lite (4.4)
- Adafruit Mini USB Microphone ([link](https://www.adafruit.com/product/3367?gclid=CMGe2t3-x9MCFc-1wAodJNYDwg))

Any help/tips would be much appreciated! Thanks

**Comment by proppy** [comment]
Can you paste the content of your `.asoundrc` and the output of `aplay -l` `arecord -l`?

See also:
https://developers.google.com/assistant/sdk/prototype/getting-started-pi-python/configure-audio

**Comment by stursby** [comment]
@proppy, When I pasted the sample `.asoundrc` file, playback was failing, so I removed it. So assume I don't have one set. I'm currently using this [USB mic](https://www.adafruit.com/product/3367) and the 3.5mm headphone jack for output.

`aplay -l`

```
**** List of PLAYBACK Hardware Devices ****
card 0: ALSA [bcm2835 ALSA], device 0: bcm2835 ALSA [bcm2835 ALSA]
  Subdevices: 8/8
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
  Subdevice #4: subdevice #4
  Subdevice #5: subdevice #5
  Subdevice #6: subdevice #6
  Subdevice #7: subdevice #7
card 0: ALSA [bcm2835 ALSA], device 1: bcm2835 ALSA [bcm2835 IEC958/HDMI]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```

`arecord -l`

```
**** List of CAPTURE Hardware Devices ****
card 1: Device [USB PnP Sound Device], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```
Thanks so much for your help!

**Comment by oscartprom** [comment]
I am using the same setup. According to your output, your /home/pi/.asoundrc file should read:

```
pcm.!default {
  type asym
  capture.pcm "usb_mic"
  playback.pcm "jack_speaker"
}

pcm.usb_mic {
  type plug
  slave {
    pcm "hw:1,0"
  }
}

pcm.jack_speaker {
  type plug
  slave {
    pcm "hw:0,0"
  }
}
```
Note the modified lines `pcm "hw:card_number,device_number"`

**Comment by stursby** [comment]
@oscartprom Ok, I added that file. It seems to record just fine, however I'm not hearing anything played back when I run `aplay --format=S16_LE --rate=16k out.raw`.

I do however hear "front left, front left..." when running `speaker-test -t wav`

**Comment by szabodabo** [comment]
Hm... if you are hearing audio when you run `speaker-test` but nothing when you `aplay` a file, are you sure that the file you're passing to `aplay` isn't empty? How do you know the recording actually picked up sound?

Is the `Connect Failed` error persistent? Did it work for you before? Are you running any kind of local or network firewall?

**Comment by proppy** [comment]
Can you also try again after add the `.asoundrc` file?
```
python -m googlesamples.assistant.audio_helpers
```

**Comment by stursby** [comment]
@proppy Here's the output from that:

```
(env)pi@hatch-google-home:~/google-home-pi $ python -m googlesamples.assistant.audio_helpers
INFO:root:Starting audio test.
INFO:root:Recording samples.
INFO:root:Finished recording.
INFO:root:Playing back samples.
INFO:root:Finished playback.
INFO:root:audio test completed.
```
I do hear a brief second or two of static... what am I supposed to hear?

**Comment by proppy** [comment]
It's supposed to record something for 5 seconds and then replay it? Does it behave correctly?

**Comment by Reijnn** [comment]
I have the same issue. Running googlesamples.assistant.audio_helper or the actual assistant also gives me invalid sample rate. 

When attempting to record just an audio file: arecord --format=S16_LE --duration=5 --rate=16k --file-type=raw out.raw 
That gives me Unknown PCM Mic
arecord: main:722: audio open error: No such file or directory.

I am using the same microphone as OP.

**Comment by mayankshekhar111** [comment]
After reading the comments I changed the .asoundrc file accordingly. Now the mic and playback are working fine.
However on starting the SDK the same error pops up.

Now what to do??

**Comment by proppy** [comment]
> However on starting the SDK the same error pops up.

Can you paste the output of `python -m googlesamples.assistant.audio_helpers` and comment if it behaves correctly (record 5 seconds of audio and replay them).

**Comment by mayankshekhar111** [comment]
I'm able to record and playback the audio. No issues. But this error continues

Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/env/lib/python3.4/site-packages/googlesamples/assistant/audio_helpers/__main__.py", line 95, in <module>
    main()
  File "/root/env/lib/python3.4/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/root/env/lib/python3.4/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/root/env/lib/python3.4/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/env/lib/python3.4/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/root/env/lib/python3.4/site-packages/googlesamples/assistant/audio_helpers/__main__.py", line 67, in main
    flush_size=audio_flush_size)
  File "/root/env/lib/python3.4/site-packages/googlesamples/assistant/audio_helpers/__init__.py", line 179, in __init__
    blocksize=int(block_size/2),  # blocksize is in number of frames.
  File "/root/env/lib/python3.4/site-packages/sounddevice.py", line 1491, in __init__
    **_remove_self(locals()))
  File "/root/env/lib/python3.4/site-packages/sounddevice.py", line 1017, in __init__
    'Error opening {0}'.format(self.__class__.__name__))
  File "/root/env/lib/python3.4/site-packages/sounddevice.py", line 2671, in _check
    raise PortAudioError(msg)
sounddevice.PortAudioError: Error opening RawStream: Invalid sample rate

**Comment by mayankshekhar111** [comment]
How do I change the sample rate of the audio devices. I believe it should have been set to 16000 Hz as per this page
https://developers.google.com/assistant/sdk/best-practices/audio

**Comment by proppy** [comment]
`--audio-sample-rate` flag allow you to control the sample rate, but it should already default to `16000`.

> I'm able to record and playback the audio. 

Can you show past here the command you're using to record/playback audio.

**Comment by mayankshekhar111** [comment]
# Record a short audio clip.
arecord --format=S16_LE --duration=5 --rate=16k --file-type=raw out.raw

# Check the recording by replaying it.
aplay --format=S16_LE --rate=16k out.raw

**Comment by proppy** [comment]
@mayankshekhar111  can you share the content of your `.asoundrc`?

**Comment by proppy** [comment]
@stursby did you get it working?

**Comment by stursby** [comment]
I did not, however I haven't had much time to test again... will follow back up as I give it another shot! @mayankshekhar111 if you get it working, please share your findings! Thanks.

**Comment by stursby** [comment]
@proppy Still can't get it to work... here's my `.asoundrc` and output from `python -m googlesamples.assistant.audio_helpers`

```
(env) pi@hatch-google-home:~ $ cat .asoundrc 
pcm.!default {
  type asym
  capture.pcm "usb_mic"
  playback.pcm "jack_speaker"
}
pcm.usb_mic {
  type plug
  slave {
    pcm "hw:1,0"
  }
}
pcm.jack_speaker {
  type plug
  slave {
    pcm "hw:0,0"
  }
}
(env) pi@hatch-google-home:~ $ python -m googlesamples.assistant.audio_helpers
INFO:root:Starting audio test.
INFO:root:Recording samples.
INFO:root:Finished recording.
INFO:root:Playing back samples.
WARNING:root:SoundDeviceStream write underflow (size: 12800)
INFO:root:Finished playback.
INFO:root:audio test completed.
(env) pi@hatch-google-home:~ $ 
```

I only hear a quick static during the `INFO:root:Finished playback.` line, and `speaker-test -t wav` continues to work just fine.

**Comment by proppy** [comment]
@stursby can you do a test similar to what you did back in https://github.com/googlesamples/assistant-sdk-python/issues/4#issuecomment-298391216, and past the output here and attach the `out.raw` file?

```
arecord --format=S16_LE --duration=5 --rate=16k --file-type=raw out.raw
aplay --format=S16_LE --rate=16k out.raw
file out.raw
```

**Comment by stursby** [comment]
@proppy Still not hearing anything 😢 Here's the output.

```
pi@hatch-google-home:~ $ arecord --format=S16_LE --duration=5 --rate=16k --file-type=raw out.raw
Recording raw data 'out.raw' : Signed 16 bit Little Endian, Rate 16000 Hz, Mono
pi@hatch-google-home:~ $ aplay --format=S16_LE --rate=16k out.raw
Playing raw data 'out.raw' : Signed 16 bit Little Endian, Rate 16000 Hz, Mono
pi@hatch-google-home:~ $ file out.raw
out.raw: data
pi@hatch-google-home:~ $ 
```

**Comment by proppy** [comment]
@stursby can you try:
```
aplay --format=S16_LE --rate=16k -d dmix out.raw
```

**Comment by stursby** [comment]
@proppy Also... does it matter that I'm using Raspbian Jessie Lite? Do I need the full version for this to work?

**Comment by stursby** [comment]
@proppy Just tried `aplay --format=S16_LE --rate=16k -d dmix out.raw` ... silence.

**Comment by stursby** [comment]
@proppy Ok, I've got some good news! I just assumed that it couldn't be the USB mic that was the problem... it was. I had another USB mic (same make/model)... popped that one it, recording & playback totally work now!!! 💯 

However... I'm still having this issue when running the assistant:

```
(env) pi@hatch-google-home:~ $ python -m googlesamples.assistant
INFO:root:Connecting to embeddedassistant.googleapis.com
Press Enter to send a new request...
INFO:root:Recording audio request.
ERROR:root:grpc unavailable error: <_Rendezvous of RPC that terminated with (StatusCode.UNAVAILABLE, Connect Failed)>
INFO:root:Recording audio request.
^C
Aborted!
(env) pi@hatch-google-home:~ $ 
```

Any idea what `ERROR:root:grpc unavailable error: <_Rendezvous of RPC that terminated with (StatusCode.UNAVAILABLE, Connect Failed)>
INFO:root:Recording audio request.` means??

**Comment by proppy** [comment]
```
ERROR:root:grpc unavailable error: <_Rendezvous of RPC that terminated with (StatusCode.UNAVAILABLE, Connect Failed)> 
```
That happens when the connection timeout and we automatically retry the connection (with https://github.com/googlesamples/assistant-sdk-python/commit/7da41cfbcd4f5aa0e0e34aa01a1ea1fdfb04b83b).

That shouldn't be fatal or impact the operation of the sample, but we could definitely use a better error message, filed #40
