### ISSUE TITLE
communication error

### ISSUE THREAD

**Issue by sweetmeats83** [googlesamples/assistant-sdk-python#41]
I'm having trouble getting assistant to work. Assistant responds to ok google and hey google with something went wrong.

`
(env) pi@google:~ $ google-assistant-demo
ON_MUTED_CHANGED:
  {'is_muted': False}
ON_START_FINISHED
[14761:14772:ERROR:speech_processing_task.cc(340)] S3 connection has timed out: No data from S3
[14761:14772:ERROR:speech_processing_task.cc(646)] Detected communication error: Downstream closed prematurely.

ON_CONVERSATION_TURN_STARTED
[14761:14772:ERROR:speech_processing_task.cc(646)] Detected communication error: Downstream closed prematurely.
[14761:14772:ERROR:assistant_output_handler.cc(589)] Failed with a general speech recognition error
ON_ASSISTANT_ERROR:
  {'is_fatal': False}
ON_RESPONDING_STARTED:
  {'is_error_response': True}
ON_RESPONDING_FINISHED
ON_CONVERSATION_TURN_FINISHED:
  {'with_follow_on_turn': False}

`
Im connected via ssh on home wifi

**Comment by proppy** [comment]
Are you able to access the internet from the pi, can you try:

```
ping embeddedassistant.googleapis.com
curl embeddedassistant.googleapis.com
```

**Comment by sweetmeats83** [comment]
`(env) pi@google:~ $ ping embeddedassistant.googleapis.com
PING googleapis.l.google.com (172.217.3.42) 56(84) bytes of data.
64 bytes from iad23s57-in-f42.1e100.net (172.217.3.42): icmp_seq=1 ttl=50 time=248 ms
64 bytes from iad23s57-in-f42.1e100.net (172.217.3.42): icmp_seq=2 ttl=50 time=141 ms
64 bytes from iad23s57-in-f42.1e100.net (172.217.3.42): icmp_seq=3 ttl=50 time=235 ms
64 bytes from iad23s57-in-f42.1e100.net (172.217.3.42): icmp_seq=4 ttl=50 time=351 ms
64 bytes from iad23s57-in-f42.1e100.net (172.217.3.42): icmp_seq=5 ttl=50 time=280 ms
64 bytes from iad23s57-in-f42.1e100.net (172.217.3.42): icmp_seq=6 ttl=50 time=408 ms
64 bytes from iad23s57-in-f42.1e100.net (172.217.3.42): icmp_seq=7 ttl=50 time=289 ms
64 bytes from iad23s57-in-f42.1e100.net (172.217.3.42): icmp_seq=8 ttl=50 time=238 ms
64 bytes from iad23s57-in-f42.1e100.net (172.217.3.42): icmp_seq=9 ttl=50 time=453 ms
64 bytes from iad23s57-in-f42.1e100.net (172.217.3.42): icmp_seq=10 ttl=50 time=403 ms
64 bytes from iad23s57-in-f42.1e100.net (172.217.3.42): icmp_seq=11 ttl=50 time=197 ms
^C
--- googleapis.l.google.com ping statistics ---
12 packets transmitted, 11 received, 8% packet loss, time 11014ms
rtt min/avg/max/mdev = 141.820/295.406/453.704/93.049 ms
(env) pi@google:~ $ curl embeddedassistant.googleapis.com
<!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 404 (Not Found)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>404.</b> <ins>That’s an error.</ins>
  <p>The requested URL <code>/</code> was not found on this server.  <ins>That’s all we know.</ins>
`

**Comment by sweetmeats83** [comment]
When I entered the authorization code it did not give me 
`OAuth credentials initialized`
It said instead
`credentials saved: /home/pi/.config/google-oauthlib-tool/credentials.json`

**Comment by proppy** [comment]
Seems similar to #38.

**Comment by sweetmeats83** [comment]
connected to Ethernet cable still same issues.
can ping  and curl

**Comment by sweetmeats83** [comment]
I solved this problem by recreating a new project and credentials. I then went through the authentication process again. Google assistant is now working on my raspberry pi.
