### ISSUE TITLE
Problems with Jabra 510 USB speaker: high pitch when answering

### ISSUE THREAD

**Issue by claudioita** [googlesamples/assistant-sdk-python#43]
The speakerphone works perfectly with other programs, and also during the test (arecord and aplay).

When launching the program, the mic part works well (you can read it recognized the wake word and the query), it also issues the right commands (I turn on a Hue light with it), but the speaker part is with a very high pitch, like if the frequency or rate are totally wrong.

How to solve?

**Comment by claudioita** [comment]
this is the log, but the problem is in the high pitch


(env) pi@raspberrypi:~ $ google-assistant-demo
ON_MUTED_CHANGED:
  {'is_muted': False}
ON_START_FINISHED

ON_CONVERSATION_TURN_STARTED
ON_END_OF_UTTERANCE
ON_RECOGNIZING_SPEECH_FINISHED:
  {'text': 'what time is it'}
ON_RESPONDING_STARTED:
  {'is_error_response': False}
WriteDataToAlsa: Under-run occurred; attempting to recover.
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
WriteDataToAlsa: Under-run occurred; attempting to recover.
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
WriteDataToAlsa: Under-run occurred; attempting to recover.
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
WriteDataToAlsa: Under-run occurred; attempting to recover.
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
WriteDataToAlsa: Under-run occurred; attempting to recover.
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
WriteDataToAlsa: Under-run occurred; attempting to recover.
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
WriteDataToAlsa: Under-run occurred; attempting to recover.
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
WriteDataToAlsa: Under-run occurred; attempting to recover.
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
WriteDataToAlsa: Under-run occurred; attempting to recover.
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
WriteDataToAlsa: Under-run occurred; attempting to recover.
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
WriteDataToAlsa: Under-run occurred; attempting to recover.
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
WriteDataToAlsa: Under-run occurred; attempting to recover.
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
WriteDataToAlsa: Under-run occurred; attempting to recover.
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
WriteDataToAlsa: Under-run occurred; attempting to recover.
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
WriteDataToAlsa: Under-run occurred; attempting to recover.
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
WriteDataToAlsa: Under-run occurred; attempting to recover.
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
WriteDataToAlsa: Under-run occurred; attempting to recover.
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
WriteDataToAlsa: Under-run occurred; attempting to recover.
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
WriteDataToAlsa: Under-run occurred; attempting to recover.
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
WriteDataToAlsa: Under-run occurred; attempting to recover.
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
ON_RESPONDING_FINISHED
ON_CONVERSATION_TURN_FINISHED:
  {'with_follow_on_turn': False}

**Comment by jacksonsevendelta** [comment]
It seems like a problem with your power.

**Comment by claudioita** [comment]
what do you mean?

It is connected to the PI3 USB port, but should have enough charge (will check that). But nevertheless if I use aplay it play correctly ...

Can you elaborate?

**Comment by jacksonsevendelta** [comment]
Ah sorry, didn't see that it worked using aplay before. There's a lot of other threads on Raspberry Pi forums about people attaching speakers that drain a lot of power and asking why it won't work.

It seems like there might be a problem with your .asoundrc file. Could you `sudo nano /home/pi/.asoundrc` and check if you have a pre-existing file there? Or you could create a new one using [Google's guide to configure audio.](https://developers.google.com/assistant/sdk/prototype/getting-started-pi-python/configure-audio)

**Comment by claudioita** [comment]
Yes I think the problem is there. I managed (with lots of difficulties) to make it work when I installed AlexaPi or AssistantPi (now I am not sure), and I do not remember what I have done precisely.

This is my file. I put, as suggested by others, but is not working ... maybe some other configuration file somewhere, but I do not know where to look

pcm.jabbra {
    type hw
    card 0
    device 0
    rate 48000
}
pcm.!default {
  type asym
   playback.pcm {
     type plug
     slave.pcm "jabbra"
   }
   capture.pcm {
     type plug
     slave.pcm "hw:0,0"
   }
}

**Comment by Steve9F** [comment]
I'm experiencing a similar issue using a USB connected Polycom speaker / mic. It works fine when testing with arecord and aplay, It also plays back correctly using audio_helpers.py and googlesamples-assistant-pushtotalk. However when using googlesamples-assistant-hotword the playback is garbled and I get the same stream of "WriteDataToAlsa: Under-run occurred; attempting to recover" and "ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred" messages above.

**Comment by jacksonsevendelta** [comment]
Try google-assistant-demo instead of googlesample-assistant-hotword. It just might work.

**Comment by claudioita** [comment]
I haven't found a solution yet

**Comment by proppy** [comment]
@claudioita can you confirm which soundcard you're using?

(dump of `dmesg | sound` or `lspci` would help).

**Comment by Steve9F** [comment]
Looking into this some more it looks like both googlesamples-assistant-hotword and google-assistant-demo use libassistant_embedder_armv71.so compiled library whereas googlesamples-assistant-audiotest and googlesamples-assistant-pushtotalk which work use the Python embedded library so appears to be an issue that Google will need to fix.

FWIW my USB device is (play & record):

card 1: CX100 [Polycom CX100], device 0: USB Audio [USB Audio]                                                      
  Subdevices: 1/1                                                                                                   
  Subdevice #0: subdevice #0

**Comment by claudioita** [comment]
interesting. Yes that could be. Any action to fix it from my side?

**Comment by pradeepprakash** [comment]
I have got a very similar problem with my setup.
I got everything setup. 
- All the setup steps recommended by Google is performed successfully. 
- arecord and aplay is successful. 
- Google demo assistant detection working fine - in the sense - that it prints the string after converting sound to text. 
- But when responding, I hear only a crackling sound on the speaker. Also, I see the below errors - clearly ALSA is being starved of data.
- googlesamples-assistant-audiotest is working fine. It is recording my audio and playing it back just fine.

I'm running a NOOB + installed Google Python SDK. It's a raspberry pi 3 + USB audio dongle.

Other test files played using aplay, mpg321 or any other tool plays just fine.

Any other suggestions/solutions to try out? 

ON_CONVERSATION_TURN_STARTED ON_END_OF_UTTERANCE ON_RECOGNIZING_SPEECH_FINISHED: {'text': 'what is the weather today'} ON_RESPONDING_STARTED: {'is_error_response': False} ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred ON_RESPONDING_FINISHED ON_CONVERSATION_TURN_FINISHED: {'with_follow_on_turn': False}

**Comment by jacksonsevendelta** [comment]
I can't really say much as I play audio through the 3.5mm jack, but could you try playing through there and check if it still outputs good audio? I have Assistant on the Pi with a USB mic and a portable speaker, and all works well. It might just be a problem with Assistant outputting audio through the USB port and not a problem with your Assistant setup in general.

**Comment by claudioita** [comment]
>I can't really say much as I play audio through the 3.5mm jack, but could you try playing through there >and check if it outputs good audio? 

3,5mm female jack in Jabra 510 is output only (is for an external headset), so is not for Audio in.

I guess you would need an adapter female USB to male 3,5mm to connect the jabra to the pi3 through the 3,5mm female and not the USB.

This could be tested, although a bit akward, I am sure it should be possible to fix it with some software command

**Comment by jacksonsevendelta** [comment]
Oh, I didn't mean with the Jabra, but if you have a spare set of headphones or earbuds or something you sould be able to plug them into the jack.

**Comment by claudioita** [comment]
The purpose of the Jabra is to have a hands free speaker/mic from which to launch commands for Google Home/Assistant.

Using a headphones attached to the pi3 is very inconvenient for Google Home usage

**Comment by pradeepprakash** [comment]
@claudioita i think @jacksonsevendelta meant only for testing purposes to narrow down the issue and not as a permanent solution. 

@jacksonsevendelta - sure will give it a try today evening once I am back from regular day job. Thanks.

**Comment by Fleker** [comment]
Are you still seeing this issue? I'm going to close for now.
