### ISSUE TITLE
Raspberry pi zero installation

### ISSUE THREAD

**Issue by antoves** [googlesamples/assistant-sdk-python#44]
Hello, 
does it exist a method to set up the old version of GoogleAssistantSDK? (I mean the 0.2.0)
That's because it seems to support the pi zero architecture.

Thank you very much for reading.

**Comment by proppy** [comment]
The grpc bindings should work on the pi zero, see https://pypi.python.org/pypi/google-assistant-grpc and the sample [here](https://github.com/googlesamples/assistant-sdk-python/tree/master/google-assistant-sdk/googlesamples/assistant/grpc).

**Comment by proppy** [comment]
Related #37.

Filed #49 and #50, hope this will help streamline to install process.
