### ISSUE TITLE
error with googlesamples-assistant-hotword

### ISSUE THREAD

**Issue by erikson-minnni** [googlesamples/assistant-sdk-python#444]
when I run googlesamples-assistant-hotword --device-model-id XXXXXXXXXX I get this error:

`usage: googlesamples-assistant-hotword [-h] [--credentials OAUTH2_CREDENTIALS_FILE]
googlesamples-assistant-hotword: error: unrecognized arguments: --device-model-id  XXXXXXXXXX `

Can someone help me please?

**Comment by bfromm440** [comment]
any answers?
