### ISSUE TITLE
Install failure in armv71 architecture

### ISSUE THREAD

**Issue by Kiszaner** [googlesamples/assistant-sdk-python#45]
Hi, I was following [the installation guide](https://developers.google.com/assistant/sdk/prototype/getting-started-pi-python/run-sample) and I encountered with this error message:

> google_assistant_library-0.0.2-py2.py3-none-linux_armv71.whl is not a supported wheel on this platform.

Prior this error, none showed up while I was following the guide. I'm using a Raspberry Pi 3 model B (armv71) and I already updated pip as said in #37 , which seems to be a similar problem but in different architecture.
Any idea what's wrong?

**Comment by proppy** [comment]
@Kiszaner can you conirm you're running `pip install` from a virtualenv, and can you confirm the version of python and pip you're using?

Thanks in advance.

**Comment by Kiszaner** [comment]
@proppy yes sure, I did the pip install from the virtualenv and I run the commands both with python and python3 variants (just in case, my rasp have python 2.7 also), but none worked. Here are the versions

> pi@rpi:~ $ source env/bin/activate
> (env) pi@rpi:~ $ pip -V
> pip 9.0.1 from /home/pi/env/lib/python3.4/site-packages (python 3.4)
> (env) pi@rpi:~ $ python -V
> Python 3.4.2
> (env) pi@rpi:~ $ uname -a
> Linux rpi 4.9.24-v7+ #993 SMP Wed Apr 26 18:01:23 BST 2017 armv7l GNU/Linux

These were the versions I used yesterday and it didn't work, but today I did again the .whl step and it worked without doing any update/upgrade, so not sure what happened.

**Comment by proppy** [comment]
Filed #49, hope this will help to streamline the installation process.
