### ISSUE TITLE
sample fails to launch under Python IDLE

### ISSUE THREAD

**Issue by vatcalLK** [googlesamples/assistant-sdk-python#46]
When i launch pushtotalk.py i get the following error.
(cannot import name 'assistant_helpers')

this is the code line
try:
    from . import (
        assistant_helpers,
        audio_helpers
    )
except SystemError:
    import assistant_helpers
    import audio_helpers

**Comment by proppy** [comment]
@vatcalLK can you paste the command line you're launching and the associated logs?

**Comment by vatcalLK** [comment]
I got it to work. It worked after i called the python script from command
line (-py pushtotalk).
But it gives the error when running from the Python IDE.


On May 21, 2017 11:27 AM, "Johan Euphrosine" <notifications@github.com>
wrote:

@vatcalLK <https://github.com/vatcallk> can you paste the command line
you're launching and the associated logs?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/googlesamples/assistant-sdk-python/issues/46#issuecomment-302917144>,
or mute the thread

**Comment by proppy** [comment]
Which Python IDE are you using?

**Comment by vatcalLK** [comment]
The normal IDE python 3.6

**Comment by proppy** [comment]
IDLE ?

**Comment by vatcalLK** [comment]
Yeah

**Comment by vatcalLK** [comment]
And do you by any chance know how to get text to speech with the google
assistance voice.
I checked out the gTTS but the voice on that isn't like the assistant voice
:/

**Comment by proppy** [comment]
@vatcalLK I'm not totally clear on what you other question is, do you mind clarifying on a new post on https://stackoverflow.com/questions/tagged/google-assistant-sdk ?

**Comment by vatcalLK** [comment]
Its like this
After the assistant has recorded my voice it translates it to text yeah?
So, i Trigger one of my own custom python scripts to do some 'stuff' based
on what the text was. And this all works great, but i after i have
completed doing the 'stuff' i want the assistant to say something like
'okay' and for this i would have to use Text to Speech. Google has a sdk
called gTTS (GOOGLE TEXT TO SPEECH) but the voice on this is not similar to
the assistant voice

My question, is there a way to make the assistant speak a custom text?  And
after sending the my recorded voice  to google servers the response of the
assistant is this a wav file or a text?
Meaning is the response of the assistant coming in a text format or a audio
file format?

Thanks in Advance.
Would really appreciate it :)

**Comment by proppy** [comment]
@vatcalLK https://developers.google.com/actions/ can allow you to customize the response of the assistant.

**Comment by proppy** [comment]
renamed the issue to better track the original report.

**Comment by vatcalLK** [comment]
Say I create a custom action
I say "Hey Google, talk to 'myproject'"
And Google passes me over to my custom actions app. From there i would like
to achieve this. My Client says "Turn on 'somthing'" i want the app to
update a SQL database value, and each of my clients have different SQL
databases. Can i achieve this with google apps? Say i created a server with
.Net and host it online which can update a sql database. My main problem
would be, how would i pass my clients 'name/email address' to my online
server. ASSUMING i have 5 clients with 5 different databases which needs to
be updated. Can google apps pass my clients email address? If i was able to
pass either the name or the email address to my server directly from google
apps i would be able to map which database for which client from my server
itself.

Hope you can help :)

**Comment by proppy** [comment]
@vatcalLK I think that this would be better discussed on g.co/actionsdev or https://stackoverflow.com/questions/tagged/actions-on-google: this issue tracker is for tracking bugs and feature request with the Assistant SDK samples.

**Comment by jacksonsevendelta** [comment]
To @vatcalLK: you can use [IFTTT](https://ifttt.com). It can talk to almost any smart device.

**Comment by alejandrosolver** [comment]
Hi vatcalLK, I'm new here and I've been looking for how to read the string that comes from google assistant and I failed in all my attempts, Could you please tell me how you did it? I'll appreciate it. Thanks

**Comment by Fleker** [comment]
We've added support for the supplemental_display_text from the AssistResponse.
