### ISSUE TITLE
Assistant not responding to hotword

### ISSUE THREAD

**Issue by sondresorbye0111** [googlesamples/assistant-sdk-python#47]
I have installed the Google assistant on my raspberry pi 3.I have followed the documentation for the google assistant sdk, but it does not work. The assistant is not responding when I say "Ok, Google"

The output when I try to start the assistant is:

```
(env) pi@raspberrypi:~ $ google-assistant-demo

ON_MUTED_CHANGED:
  {'is_muted': False}
ON_START_FINISHED  
```

When I test the recording, the recording is being played too fast. Can this be the problem that the Google assistant is not responsing?

I am also getting an error in the google cloud console: Method google.internal.speech.S3OnePlatform.Assistant

**Comment by proppy** [comment]
Can you share the full error log that you're getting and your `.asoundrc` configuration?

**Comment by MAGSON** [comment]
**The .asounrc file:**

```
pcm.!default {
  type asym
  capture.pcm "mic"
  playback.pcm "speaker"
}
pcm.mic {
  type plug
  slave {
    pcm "hw:1,0"
  }
}
pcm.speaker {
  type plug
  slave {
    pcm "hw:0,1"
  }
}
```
Here is a link to a picture of the error I receive in the cloud console: [](https://drive.google.com/open?id=0B92FVcqvLD_YaHNQbEZSMlJuZUk )

**Comment by WellyHong** [comment]
I encountered this same problem and below is my .asoundrc file.
`pcm.!default {
  type asym
  capture.pcm "mic"
  playback.pcm "speaker"
}
pcm.mic {
  type plug
  slave {
    pcm "hw:1,0"
  }
}
pcm.speaker {
  type plug
  slave {
    pcm "hw:0,1"
  }
}`

I also tried "googlesamples-assistant-audiotest --record-time 10" and "googlesamples-assistant-pushtotalk". It performed well. 
But "google-assistant-demo" and "googlesamples-assistant-hotword" didn't work.
BTW, pre-testing for mic/speaker are all good.

**Comment by chris-gunawardena** [comment]
Same issue, the response code is 499 and the method is google.internal.speech.S3OnePlatform.Assistant

**Comment by jacksonsevendelta** [comment]
I also had the same issue, but for some reason it worked when I restarted.

**Comment by chris-gunawardena** [comment]
No luck after restarting and I don't have a .asoundrc file.

**Comment by jacksonsevendelta** [comment]
Try [this page](https://developers.google.com/assistant/sdk/prototype/getting-started-pi-python/configure-audio), that Google made. If you don't have an `.asoundrc` file, you can make one and put this code in it (courtesy of google):

`pcm.!default {
  type asym
  capture.pcm "mic"
  playback.pcm "speaker"
}
pcm.mic {
  type plug
  slave {
    pcm "hw:<card number>,<device number>"
  }
}
pcm.speaker {
  type plug
  slave {
    pcm "hw:<card number>,<device number>"
  }
}`

**Comment by chris-gunawardena** [comment]
Thanks @jacksonsevendelta, still not working. I'm getting the following error `[496:523:ERROR:mic_failure_detector.cc(120)] Channel 1 has failed. Powers -inf and -inf` now.

**Comment by Simon856** [comment]
Just got the same issue. It started after the Google Assistant crashed and I tried to restart it. A reboot fixes this issue, though.

**Comment by jacksonsevendelta** [comment]
Yes. I know I'm hijacking, but why can't you kill it with CTRL-C? It should be implemented.

**Comment by vixriihi** [comment]
I've got this issue as well. `google-assistant-demo` hangs with ON_START_FINISHED status and doesn't continue from there. Cloud console is showing 100% error google.internal.speech.S3OnePlatform.Assistant

Recording and playback is working just fine when I test using the "Configure and Test the Audio"-page. 
I'm using PI 3.

**Comment by proppy** [comment]
@vixriihi can you confirm that the hotword "Ok, Google" or "Hey, Google" are not recognized?

Also did you try to raise the microphone sensibility according to the [troubleshooting instructions](https://developers.google.com/assistant/sdk/prototype/getting-started-pi-python/troubleshooting)

**Comment by vixriihi** [comment]
@proppy Nice it's working. I thought that the status text would change to something else, but indeed it's now working just fine. Thanks

**Comment by capitalfuse** [comment]
From #70, After activating alsa plug-ins dmix and dsnoop, works well on orange pi pc on both of hotword and demo sample code, but under these activating conditions, pushtotalk sample code is stuck.

**Comment by proppy** [comment]
@capitalfuse can you share your `.asoundrc` with `dsnoop` and `dmix` enabled that you're trying with the pushtotalk sample?

**Comment by capitalfuse** [comment]
@proppy 
.asoundrc in the case of
1. gRPC pushtotalk sample code
---------->
pcm.!default {
  type asym
  capture.pcm "mic"
  playback.pcm "speaker"
}
pcm.mic {
  type plug
  slave {
    pcm "hw:0,0"
  }
}
pcm.speaker {
  type plug
  slave {
    pcm "hw:0,0"
  }
}

2. demo or hotword sample code, as I need to use vol control with remote, added softvol plugin.
---------->
 pcm.!default {
   type asym
   playback.pcm "plug:softvol"
   capture.pcm "plug:dsnooper"
 }
 pcm.dmixer {
      type dmix
      ipc_key 321456 #any unique value
      ipc_key_add_uid true
      slave {
		pcm "hw:0,0"
		rate 44100
      }
      bindings {
          0 0
          1 1
      }
 }
 pcm.dsnooper {
      type dsnoop
      ipc_key 821456
      slave {
		pcm "hw:0,0"
		channels 2
		rate 8000
      }
      bindings {
		0 0
		1 1	
      }	
 }
 pcm.softvol {
      type softvol
      slave { pcm "dmixer" }
      control {
          name "Master"
          card 0
      }
 }
 ctl.softvol {
   type hw
   card 0
 }

**Comment by capitalfuse** [comment]
After deleting rate 44100 from dmix and dsnoop, works well in all sample commands.
Finally fixed .asoundrc like the following,

```
 pcm.!default {
   type asym
   playback.pcm "plug:softvol"
   capture.pcm "plug:dsnooper"
 }
 pcm.dmixer {
      type dmix
      ipc_key 321456 #any unique value
      ipc_key_add_uid true
      slave {
		pcm "hw:0,0"
      }
      bindings {
          0 0
          1 1
      }
 }
 pcm.dsnooper {
      type dsnoop
      ipc_key 821456
      slave {
		pcm "hw:0,0"
		channels 2
      }
 }
 pcm.softvol {
      type softvol
      slave { pcm "dmixer" }
      control {
          name "Master"
          card 0
      }
 }
 ctl.softvol {
   type hw
   card 0
 }
 ctl.!default {
   type hw
   card 0
 }
```

**Comment by MAGSON** [comment]
I made it work by buying a new mic. My previous one was very old.

**Comment by capitalfuse** [comment]
fixed pcm.dsnooper in .asoundrc. please see the above.
```
 pcm.dsnooper {
      type dsnoop
      ipc_key 821456
      slave {
		pcm "hw:0,0"
		channels 2
      }
      bindings {　# for output mono sound to 2ch right and left speaker, need this item.
              0 0
              1 1
      }
```

**Comment by rkstrach** [comment]
Chris - how did you solve your issue?

I'm having the same problem:

(env) pi@raspberrypi:~ $ googlesamples-assistant-hotword
ON_MUTED_CHANGED:
  {'is_muted': False}
ON_START_FINISHED
[3128:3145:ERROR:mic_failure_detector.cc(120)] Channel 1 has failed. Powers -inf and -inf

**Comment by chris-gunawardena** [comment]
@rkstrach I got it working by following the instructions [here](https://bbs.nextthing.co/t/google-assistant-on-c-h-i-p/17229/) on a fresh 4.4 and using the config posted [here](https://bbs.nextthing.co/t/google-assistant-on-c-h-i-p/17229/15).

**Comment by tkamaal** [comment]
@vixriihi Can you please explain what helped you to fix it? or what steps you specifically followed to fix it? 

I had google assistant sdk working on raspberry pi 3 by following the instructions provided [here](https://developers.google.com/assistant/sdk/develop/python/hardware/setup) . I tested it few times and it was working fine. I'm using new MIC and speaker. I turned off the Pi for few days and wanted to demo it again but I started running into the below issues 

(env) pi@raspberrypi:~ $ google-assistant-demo

ON_MUTED_CHANGED:
  {'is_muted': False}
ON_START_FINISHED 

I am also getting an error in the google cloud console: Method google.internal.speech.S3OnePlatform.Assistant


Please provide some inputs to help me fix this issue.

**Comment by tkamaal** [comment]
Just shutdown Pi and turned on again, fixed it. I wonder what changed. Please provide some information if anyone of you know what actually happened. 

I'm a bit confused about what actually fixed it.

**Comment by Fleker** [comment]
Can you try with the latest version of the library?

google-assistant-library 0.1.0

**Comment by sxy2069** [comment]
![image](https://user-images.githubusercontent.com/19299869/34353718-c22a7920-ea64-11e7-91c0-de0efad01642.png)

**Comment by ndmax** [comment]
I'm getting the same error.  I've tried the [Assistant SDK (Python)](https://developers.google.com/assistant/sdk/guides/library/python/), the [AIY Projects Raspbian repository](https://github.com/google/aiyprojects-raspbian/issues/448), as well as the [AIY Voice Kit image and instructions](https://aiyprojects.withgoogle.com/voice-v1/).  Nothing works.  After two days and a lot of frustration, I haven't managed to get a response from "Okay Google."

The AIY Projects page estimates you'll be up and running in an hour and a half, while the Assistant SDK calls it a "turnkey solution," and the Rasbian Project promises an "easy-to-use API."  I'm sorry, but no.

**Comment by Fleker** [comment]
Since the initial issue, we've updated the Python library multiple times. Any bugs with audio configurations may have been resolved. If you are still having issues, please make a new issue.

**Comment by Antonzlo** [comment]
Hello, have same problem. Mic test is good, bot google can't recognize me. -audiotest result is confusing.
![image](https://user-images.githubusercontent.com/43794515/65835343-dc243e00-e2ed-11e9-9e8e-8d3fcbe74c4e.png)
.asoundrc is here:

pcm.!default {
  type asym
  capture.pcm "mic"
  playback.pcm "speaker"
}
pcm.mic {
  type plug
  slave {
    pcm "hw:1,0"
  }
}
pcm.speaker {
  type plug
  slave {
    pcm "hw:0,0"
  }
}
