### ISSUE TITLE
How to make Smart home action on google like smart home skill on alexa ?

### ISSUE THREAD

**Issue by Kinjalk** [googlesamples/assistant-sdk-python#48]
I have tried making Smart home action but it does not show up in google home app . can you please help me ?

**Comment by proppy** [comment]
Did you try asking the question on https://stackoverflow.com/questions/tagged/actions-on-google? This repository is for the Google Assistant SDK for Python (python package that helps you to build your own assistant device).

**Comment by jacksonsevendelta** [comment]
I know that you've been redirected by @proppy, but I want to say that you can program simple actions (including smart home actions) using [IFTTT](ifttt.com). It's surprising easy and the changes are integrated to Google Assistant after restart.

Disclaimer: I don't work for IFTTT. Just use it a lot with Assistant on my Pi.

**Comment by Fleker** [comment]
You can take a look at the [smart home API](https://developers.google.com/actions/smarthome/) for the Google Assistant.
