### ISSUE TITLE
Respond time delay

### ISSUE THREAD

**Issue by cxlwill** [googlesamples/assistant-sdk-python#57]
Just install the GA in my Pi 3B with Raspbian and everything works fine except GA responded too fast that the first 2~3 words is missing when output the audio. I guess it is resulted from launch time conflict between GA and audio output device. (ie. audio output is 2 seconds slower than GA robot respond.) I am not sure it only happens on me or others have the same issue.

I have tried HDMI output and 3.5MM headphone, the result keeps the same. Are there any variable in library I could change to avoid this issue? Or is it  just a bug?

**Comment by proppy** [comment]
Can you confirm which ``package`` version and attach the output of the sample you're running? 

Thanks in advance.

**Comment by krsnaa** [comment]
@cxlwill if you save the output to a file, do you see the same behavior?

**Comment by janpIFMS** [comment]
In the repo (https://github.com/google/aiyprojects-raspbian) I created a work around for this issue by repeating a line of code like this:
   aplay.stdin.write(audio_bytes)
   aplay.stdin.write(audio_bytes)
this line 152 in audio.py from the src dir in aiy...
I can't find any equivalent to try in this repo.
This repo does not lose as much of the response though.  But still annoying.

**Comment by cxlwill** [comment]
Thanks for all reply. Well, this problem solved automatic when the usage of RAM goes down. But I still seek a possibility to delay GA's respond time. BTW, I am using latest package as always.
