### ISSUE TITLE
Is there a way to get the Assistant output displayed on the screen?

### ISSUE THREAD

**Issue by shaunakg** [googlesamples/assistant-sdk-python#63]
I was wondering if the screen could look something like this:
`"Will I need an umbrella?"`
`"ASSISTANT_RESPONSE: "No, you will not need an umbrella. It is 57 degrees and sunny."`

**Comment by proppy** [comment]
Currently the assistant response is not systematically included in the `ConverseResult`.

I encourage you to discuss this topic with the team on in the [Google+ community](https://g.co/assistantsdkdev).

**Comment by Fleker** [comment]
You can now get both rich visual outputs and [supplemental display text](https://developers.google.com/assistant/sdk/reference/rpc/google.assistant.embedded.v1alpha2#google.assistant.embedded.v1alpha2.DialogStateOut).
