### ISSUE TITLE
How can I make the assistant run on start up on a raspberry pi?

### ISSUE THREAD

**Issue by HarvsG** [googlesamples/assistant-sdk-python#66]

**Comment by jacksonsevendelta** [comment]
Yes! My time has come!

I made a GitHub repo and script for basically this purpose. You can see it [here.](https://github.com/jacksonsevendelta/GooglePi)

**Comment by HarvsG** [comment]
Thank you very much, a great help! As you have already seen I have forked it and made a couple of changes and ironed a few bugs that I was getting in headless mode!

Thank you once again

**Comment by proppy** [comment]
Looks like @jacksonsevendelta provide a nice example. Closing this issue.
