### ISSUE TITLE
Start up error

### ISSUE THREAD

**Issue by tianbastion** [googlesamples/assistant-sdk-python#67]
When I run the command google-assistant-demo I get this error:

ON_MUTED_CHANGED:
  {'is_muted': False}
ON_START_FINISHED
[16902:16919:ERROR:mic_failure_detector.cc(120)] Channel 1 has failed. Powers -inf and -inf
[16902:17481:ERROR:mic_failure_detector.cc(120)] Channel 1 has failed. Powers -inf and -inf
[16902:17643:ERROR:mic_failure_detector.cc(120)] Channel 1 has failed. Powers -inf and -inf

My mic is running fine, I can hear myself when recording.

**Comment by jacksonsevendelta** [comment]
There's a similar issue already open. [Here you go.](https://github.com/googlesamples/assistant-sdk-python/issues/47#issuecomment-304508044)

**Comment by Simonx22** [comment]
Same issue when I use nohup.

**Comment by tianbastion** [comment]
Still not running properly after making .asoundrc file. Is there another debug mode I can use?

**Comment by jacksonsevendelta** [comment]
@tianbastion This might be a bit drastic, but you could clean install Raspbian.

**Comment by proppy** [comment]
@tianbastion can you copy the content of your `.asoundrc` here and report if the [audio configuration steps in the documentation](https://developers.google.com/assistant/sdk/prototype/getting-started-pi-python/configure-audio) were successful.

**Comment by tianbastion** [comment]
pcm.!default {
  type asym
  capture.pcm "mic"
  playback.pcm "speaker"
}
pcm.mic {
  type plug
  slave {
    pcm "hw:1,0"
  }
}
pcm.speaker {
  type plug
  slave {
    pcm "hw:0,0"
  }
}

**Comment by tianbastion** [comment]
speaker and mic recording fine

**Comment by dm1010111** [comment]
I just got the same problem with Respeaker 2 mic and Raspberry Pi 3 board.  I tried solution here but did not work.  My error is:
 google-assistant-demo --device_model_id 4micberry
 
device_model_id: 4micberry
device_id: ACDCBE4E571C34433D72A4DB1AFC502C

ON_MUTED_CHANGED:
  {'is_muted': False}
ON_START_FINISHED
[1771:1803:ERROR:mic_failure_detector.cc(140)] [assistant] Channel 1 has failed. Powers -inf and -inf


Any help will be highly appreciate.

**Comment by Fleker** [comment]
Are you able to hear any microphone output as per [the documentation](https://developers.google.com/assistant/sdk/guides/library/python/embed/audio)?

```
arecord --format=S16_LE --duration=5 --rate=16000 --file-type=raw out.raw
aplay --format=S16_LE --rate=16000 out.raw
```

**Comment by dm1010111** [comment]
@Fleker Yes.  I can run the echo test arecord -f cd -Dhw:1 | aplay -Dhw:1 no problem.

**Comment by dm1010111** [comment]
I tried both arecord and splay.  But aplay does not play any thing.

**Comment by Fleker** [comment]
So there may be a problem with your microphone or speaker. If you run `speaker-test -t wav` and don't hear anything from your speaker then there is a speaker issue, but I'm going to guess your microphone is not configured properly.

**Comment by dm1010111** [comment]
Yes. I found the rootcause in my setup.  I changed .asoundrc file to make the capture and playback card as 1. This change solved the problem.  Thank you very much.
