### ISSUE TITLE
Error: Could not find a version that satisfies the requirement google-assistant-library

### ISSUE THREAD

**Issue by danielcn** [googlesamples/assistant-sdk-python#69]
Hi, 
I'm running google-assistant-library with:

pip install --upgrade google-assistant-library

I get this message:
Collecting google-assistant-library
  Could not find a version that satisfies the requirement google-assistant-library (from versions: )
 Could not find a version that satisfies the requirement google-assistant-library
No matching distribution found for google-assistant-library

Thanks!

**Comment by proppy** [comment]
What platform are you running on?

Currently the `google-assistant-library` package is only available on Raspberry Pi 3.

**Comment by apkelly** [comment]
Are there plans to support the Raspberry Pi Model B any time soon? Is the lack of current support due to slower hardware on the older Pi models?

**Comment by danielcn** [comment]
pi@raspberrypi:~ $ cat /proc/cpuinfo 
processor	: 0
model name	: ARMv6-compatible processor rev 7 (v6l)
BogoMIPS	: 697.95
Features	: half thumb fastmult vfp edsp java tls 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xb76
CPU revision	: 7

Hardware	: BCM2708
Revision	: 000e
Serial		: 000000003f05925a

**Comment by mbolanos** [comment]
cat /proc/cpuinfo
processor	: 0
model name	: ARMv6-compatible processor rev 7 (v6l)
BogoMIPS	: 697.95
Features	: half thumb fastmult vfp edsp java tls 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xb76
CPU revision	: 7

Hardware	: BCM2835
Revision	: 9000c1
Serial		: 00000000f143296a

**Comment by mbolanos** [comment]
I'm running on a Raspberry Pi Zero W, I heard it may work with almost all versions of the Pi?

**Comment by proppy** [comment]
@mbolanos https://pypi.python.org/pypi/google-assistant-grpc should work on all versions of the Pi but https://pypi.python.org/pypi/google-assistant-library only works on the Pi 3 (ARMv7).

**Comment by JordanJTW** [comment]
@mbolanos  @danielcn the Raspberry Pi Zero is not currently supported in the library. It uses an older ARMv6 core and just is not up to running our audio pipeline at full speed currently. We are exploring ways to optimize our pipeline and will hopefully add support in the future, thank you for your patience and sorry for the inconvenience.

**Comment by xtools-at** [comment]
I'm running the 0.2.1 version of the SDK on a RPi Zero W. I don't get the mentioned error, but everytime I make a request, it tells me to check my Google Home settings. Auth is done succesfully, Activity Controls are set up properly, still it won't answer.
Can you give me a hint if this is because of the Pi0 or because of changes in the API in the 0.3 -releases?

Many thanks in advance!

**Comment by Gilliotti718** [comment]
I notice everyone is running this on Pi, I'm trying to run this using Fedora 25.. is this not possible? I assumed Linux, Python, and a terminal was pretty standard across the board?

**Comment by theLMGN** [comment]
@Gilliotti718 The binary file has only been compiled for ARM processors.

**Comment by Fleker** [comment]
The library should work on ARMv7 and x86_64 processors.

**Comment by pthurmond** [comment]
So what about running this code from a MacBook Pro? I have the same problem there. I am trying to fiddle with the code on my primary machine before transferring to my Raspberry Pi.

**Comment by proppy** [comment]
@pthurmond The [Google Assistant Service](https://developers.google.com/assistant/sdk/guides/service/python/) (the gRPC API) should work on MacOSX, it's the `google-assistant-library` (the library with hotwording support) which is only available on linux (arm/x86_64) for now.

**Comment by pkalebu** [comment]
Is there an update on this? Does Linux include aarch64? I tried installing google-assistant-library on a prototyping device (Snapdragon 820 development kit) running Android 8.0, but I got the same error: Could not find a version that satisfies the requirement google-assistant-library (from versions: )
No matching distribution found for google-assistant-library

**Comment by dikkedimi** [comment]
So i get this error on a Raspi 3B running the latest raspbian image.

I don't want to use the prefab image because it obscures some of the workings of the package.

but I can't get it to install using the instructions found in [HACKING.md](https://github.com/google/aiyprojects-raspbian/blob/aiyprojects/HACKING.md)

I believe it is related to the issue concerning python-wheels, as I'm getting this error:
```
sudo apt-get install -y aiy-python-wheels
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  aiy-python-wheels
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 18.2 MB of archives.
After this operation, 21.4 MB of additional disk space will be used.
Get:1 https://dl.google.com/aiyprojects/deb stable/main armhf aiy-python-wheels all 1.1-1 [18.2 MB]
Fetched 18.2 MB in 17s (1,023 kB/s)
Selecting previously unselected package aiy-python-wheels.
(Reading database ... 113546 files and directories currently installed.)
Preparing to unpack .../aiy-python-wheels_1.1-1_all.deb ...
Unpacking aiy-python-wheels (1.1-1) ...
Setting up aiy-python-wheels (1.1-1) ...
protobuf-3.6.1-cp35-cp35m-linux_armv6l.whl is not a supported wheel on this platform.
dpkg: error processing package aiy-python-wheels (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 aiy-python-wheels
E: Sub-process /usr/bin/dpkg returned an error code (1)
```
which does not seem to have a relevant solution on the forums


when I try to follow the remaining steps this keeps popping up.
`protobuf-3.6.1-cp35-cp35m-linux_armv6l.whl is not a supported wheel on this platform.`

Look
```
sudo apt-get install -y git
Reading package lists... Done
Building dependency tree
Reading state information... Done
git is already the newest version (1:2.11.0-3+deb9u4).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Setting up aiy-python-wheels (1.1-1) ...
protobuf-3.6.1-cp35-cp35m-linux_armv6l.whl is not a supported wheel on this platform.
dpkg: error processing package aiy-python-wheels (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 aiy-python-wheels
E: Sub-process /usr/bin/dpkg returned an error code (1)
```
See?
```
pi@raspberrypi:~ $ sudo pip3 install -e AIY-projects-python/src
Obtaining file:///home/pi/AIY-projects-python/src
Requirement already satisfied: RPi.GPIO in /usr/lib/python3/dist-packages (from aiy-projects-python==1.2)
Collecting google-assistant-grpc==0.2.0 (from aiy-projects-python==1.2)
  Downloading https://files.pythonhosted.org/packages/d3/3c/4a44b54b196fb7f23335f17fdfd3ce477cbff2404324df2ef9ef1f3e4bd3/google_assistant_grpc-0.2.0-py2.py3-none-any.whl
Collecting google-assistant-library==1.0.1 (from aiy-projects-python==1.2)
  Could not find a version that satisfies the requirement google-assistant-library==1.0.1 (from aiy-projects-python==1.2) (from versions: 0.0.2, 0.0.3, 0.1.0, 0.1.1, 1.0.0)
No matching distribution found for google-assistant-library==1.0.1 (from aiy-projects-python==1.2)
```
I'm using the first generation HAT, which is no longer mentioned in any of the documentation. So i guess google deems it useless now? it would be helpful if there'd be a package for that as well.. you know, so it doesn't become yet another piece of hardware rusting away in a landfill..

I'll try using the prefab image but something tells me it won't easily work on my raspi3b with 1st gen HAT.

**Comment by Fleker** [comment]
The first generation HAT doesn't provide anything special. It should work fine with the system image provided.

You shouldn't be prevented from running the code from source. However, it seems like the AIY team is requiring `1.0.1`, which [is an invalid version](https://pypi.org/project/google-assistant-library/). It may be preferable to clone this repo directly and use the provided samples.

**Comment by janvda** [comment]
I am getting same error as in previous comment.  I share the frustration.
```
[main]     Setting up aiy-python-wheels (1.1-1) ...
[main]     protobuf-3.6.1-cp35-cp35m-linux_armv6l.whl is not a supported wheel on this platform.
```

**Comment by johanhenselmans** [comment]
Workaround on rapberry-pi3:
first do
----
sudo ln -s /opt/aiy/python-wheels/protobuf-3.6.1-cp35-cp35m-linux_armv6l.whl /opt/aiy/python-wheels/protobuf-3.6.1-cp35-cp35m-linux_armv7l.whl
----

Then in 
/var/lib/dpkg/info/aiy-python-wheels.postinst

replace 
----
/opt/aiy/python-wheels/protobuf-3.6.1-cp35-cp35m-linux_armv6l.whl
----
with 
----
/opt/aiy/python-wheels/protobuf-3.6.1-cp35-cp35m-linux_armv7l.whl
----

then do:
----
sudo dpkg --configure -a
----
