### ISSUE TITLE
google-assistant-demo  googlesamples-assistant-hotword stuck.

### ISSUE THREAD

**Issue by capitalfuse** [googlesamples/assistant-sdk-python#70]
<Device&OS>
Linux orangepipc 3.4.113-sun8i #10 SMP PREEMPT Thu Feb 23 19:55:00 CET 2017 armv7l armv7l armv7l GNU/Linux

I tried this SDK under python3-venv, all install will be OK, but I wonder the followings might be not good. 
1. googlesamples-assistant-pushtotalk works well but displayed "WARNING:root:SoundDeviceStream read overflow (3200, 6400)"

2. The following samples have been stuck.

$ google-assistant-demo
ON_MUTED_CHANGED:
  {'is_muted': False}
ON_START_FINISHED

$ googlesamples-assistant-hotword
ON_MUTED_CHANGED:
  {'is_muted': False}
ON_START_FINISHED

As the above item 1 works well, so any other problems related to item 2???

**Comment by proppy** [comment]
> 2. The following samples have been stuck.

Did you try to say "Ok, Google" or "Hey, Google" to trigger a new conversation?

**Comment by proppy** [comment]
Related #47.

**Comment by capitalfuse** [comment]
Tweaked the .asoundrc like the following. 

>  pcm.!default {
>    type asym
>    playback.pcm "plug:softvol"
>    capture.pcm "plug:dsnooper"
>  }
>  pcm.dmixer {
>       type dmix
>       ipc_key 321456 #any unique value
>       ipc_key_add_uid true
>       slave {
>           pcm "hw:0,0"
>           rate 44100
>       }
>       bindings {
>           0 0
>           1 1
>       }
>  }
>  pcm.dsnooper {
>       type dsnoop
>       ipc_key 821456
>       slave {
>           pcm "hw:0,0"
> 	  channels 2
>           rate 16000
>       }
>       bindings {
> 	0 0
> 	1 1	
>       }	
>  }
>  pcm.softvol {
>       type softvol
>       slave { pcm "dmixer" }
>       control {
>           name "Master"
>           card 0
>       }
>  }
>  ctl.!default {
>    type hw
>    card 0
>  }
>  ctl.softvol {
>    type hw
>    card 0
>  }
>  ctl.dmixer {
>    type hw
>    card 0
>  }

But after "ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred", again stuck.

> ON_MUTED_CHANGED:
>   {'is_muted': False}
> ON_START_FINISHED
> 
> ON_CONVERSATION_TURN_STARTED
> ON_END_OF_UTTERANCE
> ON_RECOGNIZING_SPEECH_FINISHED:
>   {'text': 'station'}
> ON_RESPONDING_STARTED:
>   {'is_error_response': False}
> ON_RESPONDING_FINISHED
> ON_CONVERSATION_TURN_FINISHED:
>   {'with_follow_on_turn': False}
> 
> 
> ON_CONVERSATION_TURN_STARTED
> ON_END_OF_UTTERANCE
> ON_RECOGNIZING_SPEECH_FINISHED:
>   {'text': 'timetable'}
> ON_RESPONDING_STARTED:
>   {'is_error_response': False}
> ON_RESPONDING_FINISHED
> ON_CONVERSATION_TURN_FINISHED:
>   {'with_follow_on_turn': False}
> 
> 
> ON_CONVERSATION_TURN_STARTED
> ON_END_OF_UTTERANCE
> ON_RECOGNIZING_SPEECH_FINISHED:
>   {'text': 'what is periodic table'}
> ON_RESPONDING_STARTED:
>   {'is_error_response': False}
> WriteDataToAlsa: Under-run occurred; attempting to recover.
> ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
> ON_RESPONDING_FINISHED
> ON_CONVERSATION_TURN_FINISHED:
>   {'with_follow_on_turn': False}
> 
> 
> ON_CONVERSATION_TURN_STARTED
> ON_END_OF_UTTERANCE
> ON_RECOGNIZING_SPEECH_FINISHED:
>   {'text': 'bus stop'}
> ON_RESPONDING_STARTED:
>   {'is_error_response': False}
> ON_RESPONDING_FINISHED
> ON_CONVERSATION_TURN_FINISHED:
>   {'with_follow_on_turn': False}  ---------------> stuck here, no response of saying "OK Google"
