### ISSUE TITLE
Support for x86 platforms

### ISSUE THREAD

**Issue by mhalano** [googlesamples/assistant-sdk-python#71]
The idea is allow x86 devices be able to install dependencies and run the demo.

**Comment by proppy** [comment]
Note that the `google-assistant-grpc` [package](https://pypi.python.org/pypi/google-assistant-grpc) and [sample](https://github.com/googlesamples/assistant-sdk-python/tree/master/google-assistant-sdk/googlesamples/assistant/grpc) should work on x86.

**Comment by JordanJTW** [comment]
@mhalano we are working on x86 support and it should be released shortly, thank you for your patience!

**Comment by Fleker** [comment]
We released support for x86 chipsets.
