### ISSUE TITLE
Can't run 0.3.1 samples in virtualenv - wrong urllib3 version

### ISSUE THREAD

**Issue by drigz** [googlesamples/assistant-sdk-python#72]
Steps to reproduce:

1. Start with a fresh Raspbian 2017-04-10 image
1. `sudo apt-get install -y python3-virtualenv portaudio19-dev libffi-dev libssl-dev`
1. `python3 -m virtualenv -p python3 env`
1. `env/bin/pip install --upgrade pip`
1. `env/bin/pip install --upgrade google-assistant-sdk[samples]`
1. `env/bin/googlesamples-assistant-pushtotalk`

Fails with:

`RuntimeError: Requests dependency 'urllib3' must be version >= 1.21.1, < 1.22!`

This appears to be because [google-assistant-grpc](https://github.com/googlesamples/assistant-sdk-python/blob/master/google-assistant-sdk/googlesamples/assistant/grpc/requirements.txt) pulls in urlli3b 1.20. I don't know what path the deps follow to lead to a version of requests that requires urllib3 1.21.

**Comment by proppy** [comment]
Fixed with https://github.com/googlesamples/assistant-sdk-python/releases/tag/0.3.2
