### ISSUE TITLE
googlesamples-assistant-pushtotalk gives error

### ISSUE THREAD

**Issue by shirish47** [googlesamples/assistant-sdk-python#73]
I am trying google assistant with raspberry pi ..I have followed all steps https://github.com/googlesamples/assistant-sdk-python/tree/master/google-assistant-sdk

`ERROR:root:Error loading credentials: [Errno 2] No such file or directory: /home/pi/.config/google-oauthlib-tool/credentials.json
ERROR:root:Run google-oauthlib-tool to initialize new OAuth 2.0 credentials.`

I have attached downloaded credentials from Google's https://console.developers.google.com/
like this 
`google-oauthlib-tool --client-secrets home/pi/Downloads/client_secret_XXXXX.json --scope https://www.googleapis.com/auth/assistant-sdk-prototype --save --headless
googlesamples`

how do I solve this?

**Comment by capitalfuse** [comment]
After implementing the command "google-oauthlib-tool", shows the link address for getting the encrypted characters. You should copy and paste this address in the browser, and follow the procedure.

**Comment by shirish47** [comment]
yes the browser opens up automatically asking for allowing the app.. I follow and it successful but still that command does not work.

**Comment by proppy** [comment]
@shirish47 can you paste the output of the `google-oauthlib-tool` tool?

**Comment by capitalfuse** [comment]
In the case of Linux terminal, after showing up the "output characters" on the browser, back to the terminal and copy and paste these characters to which should be entered.

**Comment by shirish47** [comment]
after the command of google-authlib-tool ... it asks: for use your google assistant: board access to your google acount I click allow. then browser shows the authenticatiion flow has completed you may close this window.and then I do googlesamples-assistant-pushtotalk and thn that error I posted above. I am doing it on raspberry pi.

**Comment by shirish47** [comment]
Also I don't get anthing similar to this terminal shows {"token": .......... other credential stuff}<img width="860" alt="screen shot 2017-06-03 at 10 21 42 am" src="https://cloud.githubusercontent.com/assets/6296507/26750712/7b965c38-4846-11e7-9501-cd3e94eee7e0.png">

**Comment by capitalfuse** [comment]
Your attached image shows "Enter the authorization code: ". You must enter the code you got on the browser. Would you like to access the site not to click the link, but copy and paste the address? Or you might ready another auth ID for  {"token": .......... other credential stuff}.

**Comment by shirish47** [comment]
@capitalfuse thats the image of the document ....I did not get that .. well we restarted all from fresh OS image and things seems to work now . I might have miss one or two steps some where but I did tried it for 1 whole day after deciding to redo all .

**Comment by proppy** [comment]
@shirish47 are you sure you were passing the `--save` flag?

**Comment by shirish47** [comment]
yes surelly I was I have written complete comand at the top.

**Comment by Fleker** [comment]
Can you try with the updated version of the SDK?

google-assistant-sdk 0.4.0

**Comment by shirish47** [comment]
Oh thanks for the reply :) @Fleker  currently I am working on other things so I would check this later. but I think that time we made it work. I just don't remember how we resolved this.
