### ISSUE TITLE
Change language?

### ISSUE THREAD

**Issue by JanLoebel** [googlesamples/assistant-sdk-python#79]
Hi there,

I just wanted to ask if it is possible to change the language the Google assistant is using. The hot word detection can be done with "American English", but the question itself should be recognized for example in German, and the assistant, of course, should response in German. Is this currently possible?

Best regards and many thanks!

**Comment by Simonx22** [comment]
The Google Assistant for Google Home is only available in English right now. Other languages will come later in this Summer. So you can propably expect that other languages will come soon.

**Comment by proppy** [comment]
@JanLoebel I also encourage you to discuss this topic w/ the product team on the [Google+ community](http://g.co/assistantsdkdev).

**Comment by aycgit** [comment]
the other way around is possible using snowboy

**Comment by Robomate** [comment]
Other languages will come later in this Summer . Ok Summer is over , where are the other languages?

**Comment by vettorazi** [comment]
nothing...

**Comment by Netfreak25** [comment]
I would really love to get german support!

**Comment by martinklein** [comment]
Please implement the "German" support !!

**Comment by Fleker** [comment]
Thanks for your feedback. As others have said, currently the SDK only supports the `en-US` locale right now. We do want to make it easier for other locales to use the SDK as well. Thank you for your patience.

**Comment by Enzoinventor** [comment]
Hello, when could we also have the Italian language?
thank you

**Comment by Fleker** [comment]
You can now manually set the locale in the gRPC request. This allows developers to use it in German, French, and all other Assistant-supported locales.

It can also be changed in the Assistant settings for a particular device.

**Comment by Enzoinventor** [comment]
thanks for the reply, but I did not understand in which file do you have to intervene exactly? you're not referring to the i18n.py file, right?

**Comment by Fleker** [comment]
You can do it directly in the command line for `pushtotalk.py` with the `--lang en-US` flag or set the `language_code` in the `DialogStateIn`

https://github.com/googlesamples/assistant-sdk-python/blob/master/google-assistant-sdk/googlesamples/assistant/grpc/pushtotalk.py#L175

**Comment by Enzoinventor** [comment]
thanks for the reply, on my rpi3 I installed the image aiyprojects-2017-09-11.img and the file you linked me contains different information. just edit the pushtotalk.py file or do I have to copy all the code you've linked to the RPI3?
thank you so much

**Comment by Fleker** [comment]
You may need to update the pushtotalk sample and make sure you're using the latest version of the gRPC version.

**Comment by Enzoinventor** [comment]
hello, sorry again, I tried to update from the link you gave me with sudo pip install --upgrade google-assistant-library. although the rpi3 has done everything, the library does not contain updated new files like pushtotalk.py.
do I forget something?
thank you

**Comment by JulianMined** [comment]
Is there a way to change the language for the Hotword sample?
If i change it in the Assistant App, it hat no effect

**Comment by zhengpenghu** [comment]
Hi @JulianMined, we fixed the issue with a new release https://pypi.python.org/pypi/google-assistant-sdk/0.4.1 See proppy's comment in #146 for detailed instruction.

**Comment by zhengpenghu** [comment]
@Enzoinventor Assistant SDK library only supports changing language from Assistant App. If you want more flexibility in selecting language, you can try SDK service API.

**Comment by Enzoinventor** [comment]
Thanks for the info. even if I do not find it correct to exclude several users who do not have at least android 6.0 to install the app assistant and change the language. what do you mean as api sdk?

**Comment by zhengpenghu** [comment]
Here is what I mean 
https://developers.google.com/assistant/sdk/guides/service/python/
https://developers.google.com/assistant/sdk/release-notes

**Comment by martinklein** [comment]
Many thanks for this guidance. However I am sure most of us entered this road with "The MagPi Essentials AIY Projects" that could be ordered from the Magpi Magazine as a nice and easy cardboard package.
Your guidance has little in common with the instructions in the booklet of this package.
For me the question is now if I have to restart from scratch or if I can upgrade the code that came with this package. In the booklet it states that it is based on the github.com/google/aiyprojects-raspian/tree/voicekit
The essential test of the Cloud Speech API is done with the "cloudspeech_demo.py" and this is propably what needs to be updated for additional languages besides the update of the installed sdk.

Many thanks for any help on this
Martin Klein

**Comment by zhengpenghu** [comment]
This is a new version of Assistant SDK and some fields get changed, together with some new fields. The github link you give doesn't work, but I know that project. Assistant SDK is not built on top of Cloud Speech API, and it supports multi language by itself now, without cloud speech API support. 
What I can suggest now, is either start from a scratch by yourself, or probably wait for an official migration guide.

**Comment by Mr-Pioupiou** [comment]
Hello, any new information regarding the language selection ?

**Comment by Fleker** [comment]
https://stackoverflow.com/questions/48017507/how-do-i-change-the-language-locale-in-the-google-assistant-sdk

**Comment by pvklink** [comment]
Hi,
When i try
googlesamples-assistant-pushtotalk --device-id <id> --lang it-IT it works, it speaks Italian!

But 
googlesamples-assistant-pushtotalk --device-id <id> --lang nl-NL it DOES NOT work!
Strange because my google assistant app on my tablet does speak Dutch!
Somebody an idea ?

**Comment by Fleker** [comment]
For which spoken languages are supported in the service, you can visit [this reference page](https://developers.google.com/assistant/sdk/reference/rpc/languages).
