### ISSUE TITLE
ImportError: No module named 'google.protobuf'

### ISSUE THREAD

**Issue by gamehelp16** [googlesamples/assistant-sdk-python#8]
When running `python3 -m googlesamples.assistant` I got the following error:

    Traceback (most recent call last):
      File "/usr/lib64/python3.5/runpy.py", line 193, in _run_module_as_main
        "__main__", mod_spec)
      File "/usr/lib64/python3.5/runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "/usr/lib/python3.5/site-packages/googlesamples/assistant/__main__.py", line 21, in <module>
        from google.assistant.embedded.v1alpha1 import embedded_assistant_pb2
      File "/usr/lib/python3.5/site-packages/google/assistant/embedded/v1alpha1/embedded_assistant_pb2.py", line 6, in <module>
        from google.protobuf import descriptor as _descriptor
    ImportError: No module named 'google.protobuf'

I have protobuf already installed since running `python3 -m pip install protobuf` gives:

    Requirement already satisfied: protobuf in /usr/lib64/python3.5/site-packages
    Requirement already satisfied: six>=1.9 in /usr/lib/python3.5/site-packages (from protobuf)
    Requirement already satisfied: setuptools in /usr/lib/python3.5/site-packages (from protobuf)
    Requirement already satisfied: appdirs>=1.4.0 in /usr/lib/python3.5/site-packages (from setuptools->protobuf)
    Requirement already satisfied: packaging>=16.8 in /usr/lib/python3.5/site-packages (from setuptools->protobuf)
    Requirement already satisfied: pyparsing in /usr/lib/python3.5/site-packages (from packaging>=16.8->setuptools->protobuf)

Also the `python3 -m googlesamples.assistant.audio_helpers` command works fine.

**Comment by proppy** [comment]
Are you running `python3 -m googlesamples.assistant` from a virtualenv?

**Comment by gamehelp16** [comment]
No I didn't. By the way, looks like installing the 3.1.0 version (`sudo pip3 install protobuf==3.1.0`) fixes the problem.

**Comment by proppy** [comment]
@gamehelp16 yep, the sample currently transitively depends on `protobuf==3.3.0`
