### ISSUE TITLE
Trying to run on mac

### ISSUE THREAD

**Issue by arashbi** [googlesamples/assistant-sdk-python#83]
I am trying to run this on mac to get a sense of the api.
I create an env and installed dependencies etc. Cloned the sample. Now when I try to run 
`python -m pushtotalk`

I get this error:
`source/googleassistant/env/lib/python3.6/site-packages/google/auth/transport/grpc.py", line 28, in <module>
    class AuthMetadataPlugin(grpc.AuthMetadataPlugin):
AttributeError: module 'grpc' has no attribute 'AuthMetadataPlugin'`

**Comment by proppy** [comment]
@arashbi can you confirm which version of the `grpcio` package you've installed by pasting the output of `pip freeze` run from the virtualenv?

**Comment by Fleker** [comment]
Closing this issue for now. If you see more problems, please make a new issue.
