### ISSUE TITLE
Why is assistant not working on Windows now?

### ISSUE THREAD

**Issue by techwindow** [googlesamples/assistant-sdk-python#85]
I get following error when trying to run Google Assistant on Windows.

C:\Users\Admin>python -m googlesamples.assistant
C:\Users\Admin\AppData\Local\Programs\Python\Python36-32\python.exe: No module n
amed googlesamples.assistant.__main__; 'googlesamples.assistant' is a package an
d cannot be directly executed

What is the cause? What is the solution? Thanks in advance.

**Comment by proppy** [comment]
Which instructions are you following? Which version of the SDK are you using?

**Comment by techwindow** [comment]
I am following the XDA guide and how do I check the version? pip install --upgrade google-assistant-sdk
says everything is up to date.

**Comment by techwindow** [comment]
One more thing now googlesamples-assistant-pushtotalk seems to work. That's all I have to do? I tried from this guide https://pypi.python.org/pypi/google-assistant-sdk/0.3.0. However, the hotward thing is still not working.

**Comment by techwindow** [comment]
Hey just checked the version and its 0.3.2

**Comment by TheNameIsEaston** [comment]
Not on windows, but I cannot get hotword to work either on armbian.

**Comment by Fleker** [comment]
Can you try with the updated version of the sdk?

google-assistant-sdk 0.4.0

**Comment by qreeves** [comment]
```
> pip show google-assistant-sdk
Name: google-assistant-sdk
Version: 0.4.4
Summary: Samples and Tools the Google Assistant SDK
Home-page: https://github.com/googlesamples/assistant-sdk-python
Author: Google Assistant SDK team
Author-email: proppy+assistant-sdk@google.com
License: Apache 2.0
Location: c:\tools\python36\lib\site-packages
Requires: google-auth-oauthlib
Required-by:
```
And:
```
> pip search google-assistant-library
google-assistant-library (0.1.1)              - Google Assistant Library Python wrapper
google-assistant-grpc (0.1.0)                 - Google Assistant API gRPC bindings
  INSTALLED: 0.1.0 (latest)
google-assistant-sdk (0.4.4)                  - Samples and Tools the Google Assistant SDK
  INSTALLED: 0.4.4 (latest)
```
The problem being:
```
> pip show google-assistant-library
[no output]
```

**Comment by qreeves** [comment]
Alrighty, sorry I missed the bits where that was explained on my first pass through.

I'm a Windows-based FOSS dev, anything I can do to help?

**Comment by proppy** [comment]
@qreeves you should be able to use the Google Assistant Service on Windows:
https://developers.google.com/assistant/sdk/guides/service/python/

You can find the difference between the Google Assistant Service and the Google Assistant Library listed here:
https://developers.google.com/assistant/sdk/overview

**Comment by qreeves** [comment]
Thanks for the quick response.

I'm aware of the gRPC platforms, but it lacks the "hands-free" (hotword) detection that everyone seems to be after, so I thought maybe I could port the python `google-assistant-library` to Windows.

I'm asking because there might be some technical reason or obstacle that is preventing this that I don't know about, or perhaps it is better to focus on adding it to the gRPC supported methods?

**Comment by Fleker** [comment]
There are certain platform-specific parts in the library that will prevent it from being ported to Windows. Integrating with gRPC, perhaps incorporating a 3P hotword library, is the best way.

**Comment by tng99** [comment]
found this one from 2019, work great and very detail  https://www.lifewire.com/google-assistant-on-windows-4628292
bonus: my path
d:\Program Files\Python37\Lib\site-packages\googlesamples\assistant\grpc\audio_helpers.py
d:\Program Files\Python37\Scripts\googlesamples-assistant-devicetool.exe
nb: if this failed
Error: Failed to register model: 409
Could not create the device model. A model with the same device_model_id (GA4W) already exists.

just rename GA4W to 88GA4W or something else.
