### ISSUE TITLE
external hotword support

### ISSUE THREAD

**Issue by aycgit** [googlesamples/assistant-sdk-python#86]
I was trying to port over [this](https://github.com/warchildmd/google-assistant-hotword-raspi) project to the newest assistant sdk but i sadly wasn't able to accomplish that. If any of you have some spare time i would really like if any of you could take a look into fixing it.

you can close this if this is not what you want in your issues section but i am just requesting to take a look at it since it would help a lot of people with a better assistant experience.

**Comment by aycgit** [comment]
sorry just found it that this isnt currently possible because the dev needs to upgrade to pyhon 3 because you only support 3. sorry

**Comment by proppy** [comment]
@aycgit the https://pypi.python.org/pypi/google-assistant-grpc package does support Python 2.x and could be used to make call to the Google Assistant API.

**Comment by aycgit** [comment]
weird....


is there a way to run this project but then be able to select which python to use?
