### ISSUE TITLE
Shopping list can be added to but not deleted

### ISSUE THREAD

**Issue by sheridat** [googlesamples/assistant-sdk-python#87]
Using a PI with the AIY kit. You can add items to your shopping list but you cannot delete them or reflect that they have been purchased.

**Comment by proppy** [comment]
@sheridat which version of the SDK are you using?

**Comment by sheridat** [comment]
Hi, I am using a the Google AIY kit.  In /home/pi/assistant-sdk-python/google-assistant-sdk there is a changelog. The last change is 

0.3.2
--------
- Bump urllib3 dependency.

**Comment by Fleker** [comment]
I think this may be a limitation of the shopping list implementation, not related to the Assistant SDK.
