### ISSUE TITLE
Commute is never correct.

### ISSUE THREAD

**Issue by sheridat** [googlesamples/assistant-sdk-python#88]
I am using the Assistant on a Raspberry PI - with the Google AIY kit and I am connected to the internet via an ISP. 
If I say "OK Google - Good Morning" I get the usual greeting, then the weather, then details of my commute. BUT I am sitting in my own home - I don't need to commute - I am already there. If I ask the assistant where I live it has my address absolutely pinned down (from my google account).

The commute information is always wrong - it must be based upon my derived location using some kind of geolocation software (presumably based upon my ISP's allocated IP address). According to the assistant - the distance I have to commute varies from 7 to 16 miles.

Telling me what my commute to my home is - when I am sitting in my home - is a farce. To make matters worse I cannot find any way to tell the assistant to stop telling me about my non existent commute - HELP it is driving me bananas.

**Comment by proppy** [comment]
@sheridat sorry for the late followup, can you confirm which sample you're running?

**Comment by sheridat** [comment]
@proppy  Hello. As you can see above I've asked the AIY folk to confirm what I am running but I think it is google-assistant-grpc==0.0.2 but I don't really know.

**Comment by sheridat** [comment]
@proppy Hi I heard back and can confirm that is is google-assistant-grpc==0.0.2. I've just upgrade to 0.0.3 and that has the same behaviour

**Comment by giraygokirmak** [comment]
Same behaviour applies to me also for python sdk library

**Comment by Fleker** [comment]
Can you try with the updated version of the library or gRPC?
We've added support for custom setting of location or street address, so responses should be more accurate.

google-assistant-library 0.1.0
google-assistant-grpc 0.1.0

**Comment by Fleker** [comment]
If you're still seeing issues, you can manually set your location in each request with the gRPC [DeviceLocation](https://developers.google.com/assistant/sdk/reference/rpc/google.assistant.embedded.v1alpha2#devicelocation) message.
