### ISSUE TITLE
Assistant gets confused when asked for address twice

### ISSUE THREAD

**Issue by sheridat** [googlesamples/assistant-sdk-python#89]
Using Raspberry PI AIY and SDK 0.2

If i ask "where is my nearest petrol station" the assistant correctly tells me. If I then ask "what is my address" - you have guessed - it tells me the petrol stations address. If I wait 20 seconds and do it again - it again tells me the petrol stations address. 

Bug

**Comment by proppy** [comment]
@sheridat can you confirm which sample you're running?

**Comment by sheridat** [comment]
@proppy Hi I am not sure is the answer. I think it is google-assistant-grpc==0.0.2 but I am not sure.
I've asked the AIY folk to confirm - I use whatver gets invoked when you use the Hey Google hotword. See https://github.com/google/aiyprojects-raspbian/issues/114

**Comment by sheridat** [comment]
Hi it is google-assistant-grpc 0.0.2 see https://github.com/google/aiyprojects-raspbian/issues/114#issuecomment-319094877. 
I just upgrade to 0.0.3 and the same fault exists.
One piece of good news is that if i say good morning after telling me everything it used to say at the end "here is the latest news" followed by silence. The here the latest news is gone - yippeee - that was driving me nuts as well

**Comment by Fleker** [comment]
Can you try on the latest version of the gRPC API, version 0.4.0?

**Comment by Fleker** [comment]
There is now support for [manually setting the address](https://developers.google.com/assistant/sdk/reference/rpc/google.assistant.embedded.v1alpha2#devicelocation), so this issue is probably no longer valid. Let me know if this is still happening.
