### ISSUE TITLE
Error when using 48,000 sample rate

### ISSUE THREAD

**Issue by parkerlreed** [googlesamples/assistant-sdk-python#9]
I am running Assistant on a device that seems to only be capable of 48,000 sample rate.

If I run 

````
python3 -m googlesamples.assistant.audio_helpers --audio-sample-rate 48000
````

It works perfectly capturing my voice and playing it back. 

When I try to run the Assistant the same way, I get an invalid same rate error. Does the server not accept 48,000?

````
python3 -m googlesamples.assistant --audio-sample-rate 48000
INFO:root:Connecting to embeddedassistant.googleapis.com
Press Enter to send a new request...
INFO:root:Recording audio request.
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.6/site-packages/googlesamples/assistant/__main__.py", line 273, in <module>
    main()
  File "/usr/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/googlesamples/assistant/__main__.py", line 234, in main
    grpc_deadline):
  File "/usr/lib/python3.6/site-packages/grpc/_channel.py", line 363, in __next__
    return self._next()
  File "/usr/lib/python3.6/site-packages/grpc/_channel.py", line 357, in _next
    raise self
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.INVALID_ARGUMENT, Invalid 'audio_in_config': bad sample_rate_hertz.)>
````

**Comment by parkerlreed** [comment]
Ahh seems I'll have to resample https://developers.google.com/assistant/sdk/reference/rpc/google.assistant.embedded.v1alpha1#google.assistant.embedded.v1alpha1.AudioInConfig

**Comment by parkerlreed** [comment]
For anybody else running into this. Investigate your microphone. The USB mic I was using seems ton only support 8,000 and 48,000Hz. Switched mics and it's working great.

**Comment by bernardyip** [comment]
Leaving this fix as i recently have this issue but do not have the luxury of getting a different mic. In fact, it's because of the rpi's sound card which does not allow me to record at 16000 Hz rather than the mic itself.

The main idea is to trick the SoundDeviceStream by hard coding the sample_rate in audio_helpers.py to the sampling rate supported by my sound card. Then solve the input/output by upsampling/downsampling as read/write occurs. I used samplerate package in the example below.

In audio_helpers.py

    <snip>
    class SoundDeviceStream(object):
        """Audio stream based on an underlying sound device.

        It can be used as an audio source (read) and a audio sink (write).
    
        Args:
          sample_rate: sample rate in hertz.
          sample_width: size of a single sample in bytes.
          block_size: size in bytes of each read and write operation.
          flush_size: size in bytes of silence data written during flush operation.
        """
        def __init__(self, sample_rate, sample_width, block_size, flush_size):
            if sample_width == 2:
                audio_format = 'int16'
            else:
                raise Exception('unsupported sample width:', sample_width)
            ######## We say its 16000, but we need to record at 48000 due to limitations ########
            self._audio_stream = sd.RawStream(
                samplerate=48000, dtype=audio_format, channels=1,
                blocksize=int(block_size/2),  # blocksize is in number of frames.
            )
            ########
            self._block_size = block_size
            self._flush_size = flush_size
            self._sample_rate = sample_rate
    <snip>

Then in ConversationStream in the same file

    <snip>
        def read(self, size):
            """Read bytes from the source (if currently recording).
            """
            with self._source_lock:
                data = self._source.read(size)
                # Convert to numpy array, downsample, then convert back
                new_data = np.frombuffer(data, dtype=np.int16)
                new_data = sr.resample(new_data, 16000/48000)
                new_data = new_data.astype(np.int16)
                new_data = new_data.tobytes()
                return new_data
    
        def write(self, buf):
            """Write bytes to the sink (if currently playing).
            """
            buf = align_buf(buf, self._sample_width)
            buf = normalize_audio_buffer(buf, self.volume_percentage)
            # Convert to numpy array, up sample, then convert back
            new_data = np.frombuffer(buf, dtype=np.int16)
            new_data = sr.resample(new_data, 48000 / 16000)
            new_data = new_data.astype(np.int16)
            new_data = new_data.tobytes()
            return self._sink.write(new_data)
    
        def close(self):
    <snip>

Hope that helps anyone that encounters this issue too as I was stuck on this for 2 weeks!
