### ISSUE TITLE
No module named enum

### ISSUE THREAD

**Issue by mortenmoulder** [googlesamples/assistant-sdk-python#91]
I'm not sure if this is because I installed Google Assistant on my Raspberry Pi before the newest update, but take a look:

When I then do the final step of running `google-assistant-demo`, I get a Python error saying:

>ImportError: No module named enum

However, when I do:

    (env) pi@raspberrypi:~ $ python
    >>> from enum import Enum

I get no import error. Same for `python3`. What could the issue be? The full error is here:

    (env) pi@raspberrypi:~ $ google-assistant-demo
    Traceback (most recent call last):
      File "/usr/local/bin/google-assistant-demo", line 7, in <module>
        from google.assistant.__main__ import main
      File "/usr/local/lib/python2.7/dist-packages/google/assistant/__main__.py", li                                                            ne 26, in <module>
        from google.assistant.library import Assistant
      File "/usr/local/lib/python2.7/dist-packages/google/assistant/library/__init__                                                            .py", line 17, in <module>
        from .assistant import Assistant
      File "/usr/local/lib/python2.7/dist-packages/google/assistant/library/assistan                                                            t.py", line 21, in <module>
        from .event import Event, IterableEventQueue
      File "/usr/local/lib/python2.7/dist-packages/google/assistant/library/event.py                                                            ", line 17, in <module>
        from enum import Enum
    ImportError: No module named enum

Any clue why?

**Comment by proppy** [comment]
Seems that it doesn't execute the demo from the virtual environment.

Can you try to run:
```
which python
````
After activating the environment?

Can you also try to run:
```
env/bin/google-assistant-demo
```
Without entering the virtual environment.

**Comment by mortenmoulder** [comment]
@proppy I'm getting:

>/home/pi/env/bin/python

and 

>pi@raspberrypi:~ $ env/bin/google-assistant-demo
>-bash: env/bin/google-assistant-demo: No such file or directory

**Comment by proppy** [comment]
@mortenmoulder it seems like you installed `google-assistant-library` system wide in `/usr/local/bin/google-assistant-demo` and not in the virtual environment.

Can you try:
```
env/bin/pip install --upgrade setuptools pip
env/bin/pip install google-assistant-library
env/bin/google-assistant-demo
```

**Comment by mortenmoulder** [comment]
@proppy Worked perfectly! Thanks a lot.

**Comment by proppy** [comment]
Happy to help! Thanks for trying out the SDK and keep the feedback coming :)

**Comment by prayagupd** [comment]
Hi @proppy installing `google-assistant-library` is failing for me, 

```bash
$ googlesamples-assistant-pushtotalk
Traceback (most recent call last):
  File "/usr/local/bin/googlesamples-assistant-pushtotalk", line 7, in <module>
    from googlesamples.assistant.grpc.pushtotalk import main
  File "/usr/local/lib/python3.6/site-packages/googlesamples/assistant/grpc/pushtotalk.py", line 27, in <module>
    from google.assistant.embedded.v1alpha1 import embedded_assistant_pb2
ModuleNotFoundError: No module named 'google.assistant'

$ pip3 install google-assistant-library
Collecting google-assistant-library
  Could not find a version that satisfies the requirement google-assistant-library (from versions: )
No matching distribution found for google-assistant-library
```

following are the modules i have

```
pip3 list

cachetools (2.0.1)
certifi (2017.7.27.1)
cffi (1.11.0)
chardet (3.0.4)
click (6.7)
google-assistant-sdk (0.3.3)
google-auth (1.1.0)
google-auth-oauthlib (0.1.1)
grpcio (1.6.0)
idna (2.6)
oauthlib (2.0.4)
pip (9.0.1)
protobuf (3.4.0)
pyasn1 (0.3.5)
pyasn1-modules (0.1.4)
pycparser (2.18)
requests (2.18.4)
requests-oauthlib (0.8.0)
rsa (3.4.2)
setuptools (36.5.0)
six (1.11.0)
sounddevice (0.3.8)
urllib3 (1.22)
```

**Comment by proppy** [comment]
@prayagupd which OS/architecture? (The library is only availble on GNU/Linux/arm7/x86-64)

**Comment by r67** [comment]
@prayagupd same problem for me, @proppy I'm trying to run it on ubuntu 17 on x86_64, any update?

**Comment by prayagupd** [comment]
@proppy Im on MacOS x86_64.

```bash
$ uname -a
Darwin MACC02V82BPHTD7 16.7.0 Darwin Kernel Version 16.7.0: Wed Oct  4 00:17:00 PDT 2017; root:xnu-3789.71.6~1/RELEASE_X86_64 x86_64
```

Is there no SDK for MacOS?
