### ISSUE TITLE
Memory Leak in network_status_tracker.c:48

### ISSUE THREAD

**Issue by eduncan911** [googlesamples/assistant-sdk-python#93]
We are using the AIYProjects repo that uses this Assistant SDK.  Occasionally, once a week or more frequently, when we say, *Hey Google*, she responds instantly with:

> Sorry, something went wrong.  Please try again in a few seconds.

And many other variants similar to this to "retry" in a few seconds.

Reviewing the journal log, I found this:

```
Jun 25 09:22:43 spee python3[13710]: [2017-06-25 09:22:43,596] INFO:root:ON_CONVERSATION_TURN_STARTED
Jun 25 09:22:43 spee python3[13710]: [2017-06-25 09:22:43,597] INFO:main:listening...
Jun 25 09:22:43 spee python3[13710]: E0625 09:22:43.971572259   15218 network_status_tracker.c:48] Memory leaked as all network endpoints were not shut down
Jun 25 09:22:43 spee python3[13710]: [13710:15218:ERROR:speech_processing_task.cc(646)] Detected communication error: Downstream closed prematurely.
Jun 25 09:22:43 spee python3[13710]: [13710:15218:ERROR:assistant_output_handler.cc(589)] Failed with a general speech recognition error
Jun 25 09:22:43 spee python3[13710]: [2017-06-25 09:22:43,973] INFO:root:ON_ASSISTANT_ERROR:
Jun 25 09:22:43 spee python3[13710]: {'is_fatal': False}
Jun 25 09:22:43 spee python3[13710]: [2017-06-25 09:22:43,974] INFO:root:ON_RESPONDING_STARTED:
Jun 25 09:22:43 spee python3[13710]: {'is_error_response': True}
Jun 25 09:22:43 spee kernel: voicehat-codec voicehat-codec: Enabling audio amp...
Jun 25 09:22:47 spee python3[13710]: [2017-06-25 09:22:47,821] INFO:root:ON_RESPONDING_FINISHED
Jun 25 09:22:47 spee python3[13710]: [2017-06-25 09:22:47,822] INFO:root:ON_CONVERSATION_TURN_FINISHED:
Jun 25 09:22:47 spee python3[13710]: {'with_follow_on_turn': False}
Jun 25 09:22:47 spee kernel: voicehat-codec voicehat-codec: Disabling audio amp...
Jun 25 09:22:47 spee python3[13710]: [2017-06-25 09:22:47,823] INFO:main:ready...
```

Do note that the speech that comes back is the Google-streamed or "Real" Assistant SDK voice - not the cheap-robot-sounding local commands version of the voice.  So it is reaching the SDK.

You can see in the error log that the stacktrace includes the `C` files - there aren't any C files in the AIY Projects repo.  So I'm guessing this is coming from the Assistant SDK here.

Cross-posted the issue [over in the AIYProject](https://github.com/google/aiyprojects-raspbian/issues/88).

**Comment by eduncan911** [comment]
Update: seems to be an issue with the gRPC bindings.

**Comment by proppy** [comment]
@eduncan911 the logs seems to indicate you're using the `google-assistant-library` not `google-assistant-grpc`.

Can you confirm which version of the packages you have installed?

**Comment by eduncan911** [comment]
@proppy humm.  pip freeze shows both:

```
google-assistant-grpc==0.0.2
google-assistant-library==0.0.2
google-auth==1.0.1
google-auth-oauthlib==0.1.0
googleapis-common-protos==1.5.2
gpiozero==1.3.2
grpc-google-cloud-speech-v1beta1==0.14.0
grpcio==1.4.0
```

I am just using the Google VoiceKit, which has the default code from https://github.com/google/aiyprojects-raspbian Google project.  

I believe that project is using `google-assistant-library`, and not the grpc bindings, because I use the `OK Google` hotword detection, which from what I read is only available in the library.

**Comment by Fleker** [comment]
Are you still seeing this happen?

**Comment by eduncan911** [comment]
@Fleker we haven't used the library in almost a year because of all the different errors.  We've basically built our own devices at this point.

May try later though.
