### ISSUE TITLE
googlesamples.assistant.grpc.pushtotalk shows warning SoundDeviceStream read overflow

### ISSUE THREAD

**Issue by 5aikat** [googlesamples/assistant-sdk-python#94]
googlesamples.assistant.grpc.pushtotalk shows warning SoundDeviceStream read overflow. And then i am not able to hear the audio output.  Some gibberish noise plays on speaker after which it prints : Finished playing assistant response. How do i fix this ?

**Comment by thecodingwizard** [comment]
I'm having the read overflow issue too. However, for me, the audio output still plays, and the error only happens the first time around.

**Comment by proppy** [comment]
Can you paste more details about the microphone and hardware you're using?

**Comment by Noob-101** [comment]
Try to use the option "--audio-block-size=0". That's how I got it to work on a banana pi

**Comment by Fleker** [comment]
Can you try with the updated version of the library?

google-assistant-grpc 0.4.0
