### ISSUE TITLE
Choppy audio using grpc on raspberry pi

### ISSUE THREAD

**Issue by thecodingwizard** [googlesamples/assistant-sdk-python#95]
Using the grpc library, the audio output is choppy. However, using the google assistant library, it is very smooth.

Changing the sample rate doesn't seem to help much. **However**, if I run pushtotalk.py with the -o command (redirecting the audio output to a file) and then play back the file, everything runs fine. Could it possibly be a problem with [this library](https://python-sounddevice.readthedocs.io/en/0.3.7/) and the raspberry pi?

My audio output is coming from a speaker plugged into the 3.5mm audio jack.

Note: aplay, arecord, sound tests etc. all have smooth playback.

(Similar issue: https://github.com/googlesamples/assistant-sdk-python/issues/77)

**Comment by thecodingwizard** [comment]
I tried to switch the library (python-sounddevice) to pyaudio. Same problem.

**Comment by proppy** [comment]
@thecodingwizard we had better result with the recommended hardware:
https://www.adafruit.com/product/3369

We should investigate if running the `sounddevice` sample over line-out exhibit the same issue, and possibly investigate switching to their async API.

**Comment by thecodingwizard** [comment]
Yeah, using a USB speaker seems to fix the issue. I recall reading somewhere that the Raspberry Pi likes USB audio output more than the audio jack, but I might be mistaken.

**Comment by thecodingwizard** [comment]
I switched to a USB soundcard. All the choppiness issues solved, though I'm not sure why...
