### ISSUE TITLE
Audio to Chromecast?

### ISSUE THREAD

**Issue by tstasevych** [googlesamples/assistant-sdk-python#98]
Is there any way to output audio on Chromecast enabled speaker instead of speaker connected directly to RPi3?

Thanks

**Comment by proppy** [comment]
@tstasevych This type of question might be more suited for https://stackoverflow.com/questions/tagged/google-assistant-sdk, this repository is more about reporting issues about the "samples" themselves.

**Comment by aycgit** [comment]
The assistant uses alsa so if you find a way to tunnel your alsa audio to you chromecast then that is what you want to do

**Comment by Fleker** [comment]
Right now you can do remote casting of content on other surfaces through the library. There is no direct way to output audio to a Chromecast, but as stated in the comments you may be able to pipe ALSA audio to a cast-enabled device.
