### ISSUE TITLE
How to get audio on Windows?

### ISSUE THREAD

**Issue by CCninja86** [googlesamples/assistant-sdk-python#99]
Is there a way to install the required audio dependencies on Windows? I don't have sudo apt-get. Everything works except for audio.

**Comment by proppy** [comment]
If you already have Python for Windows installed, did you try to skip the `apt-get` instructions and just install the python package the in virtualenv?

**Comment by CCninja86** [comment]
I don't have a requirements.txt file, where do I get that?

**Comment by proppy** [comment]
@CCninja86 which instructions are you following?

**Comment by CCninja86** [comment]
https://github.com/googlesamples/assistant-sdk-python/tree/master/google-assistant-sdk/googlesamples/assistant/library

**Comment by CCninja86** [comment]
Am I missing something? I've got it authorized and everything, I just can't get audio working

**Comment by proppy** [comment]
`google-assistant-library` isn't yet support on windows.

You could try the instructions for the gRPC bindings here:
https://github.com/googlesamples/assistant-sdk-python/tree/master/google-assistant-sdk/googlesamples/assistant/grpc

After cloning the repository:
git clone https://github.com/googlesamples/assistant-sdk-python.git
cd assistant-sdk/python/google-assistant-sdk/googlesamples/assistant/grpc

**Comment by CCninja86** [comment]
Weird, it used to work fine. Did it change and remove support?

**Comment by proppy** [comment]
There is no windows build for the `google-assistant-library`(the library that support hotwording, "Ok Google").

Which version of the software were you using and what are the getting started instructions that you used at that time?

**Comment by CCninja86** [comment]
https://www.xda-developers.com/how-to-get-google-assistant-on-your-windows-mac-or-linux-machine/

Worked fine. Then I heard it changed and you had to do some extra stuff and it no longer worked.

**Comment by CCninja86** [comment]
I've just tried the grpc one and there's no audio because I can't install portaudio like the instructions

**Comment by proppy** [comment]
> I've just tried the grpc one and there's no audio because I can't install portaudio like the instructions


On windows, it seems that installed sounddevice should install the portaudio library automatically.
See https://python-sounddevice.readthedocs.io/en/0.3.8/#installation

Did you already try to run this from the virtualenv?
```
pip install sounddevice
```

**Comment by CCninja86** [comment]
Yes. It says it's already installed.

**Comment by proppy** [comment]
@CCninja86 what happens when you try to run the sample? Can you share verbose logs?

**Comment by CCninja86** [comment]
@proppy it runs but I can't hear any audio when it plays it back

**Comment by proppy** [comment]
can you try to run:
```
googlesamples-assistant-audiotest --record-time 10
```
to validate the audio setup?

**Comment by CCninja86** [comment]
@proppy that worked

**Comment by proppy** [comment]
@CCninja86 can you run `googlesamples-assistant-hotword   --verbose` and paste the log here?

**Comment by qreeves** [comment]
```
> googlesamples-assistant-hotword --verbose
Traceback (most recent call last):
  File "c:\tools\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\tools\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Tools\Python36\Scripts\googlesamples-assistant-hotword.exe\__main__.py", line 5, in <module>
  File "c:\tools\python36\lib\site-packages\googlesamples\assistant\library\hotword.py", line 27, in <module>
    from google.assistant.library import Assistant
ModuleNotFoundError: No module named 'google.assistant.library'
```

**Comment by proppy** [comment]
@qreeves as commented in https://github.com/googlesamples/assistant-sdk-python/issues/99#issuecomment-318953097 there is no windows build of the `google-assistant-library` package, so `googlesamples-assistant-hotword` only works on Linux (arm and x86_64).
